### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by Fadikhayo1995** [bharat-biradar/Google-Ml-Kit-plugin#102]

**Comment by Fadikhayo1995** [comment]
I have updated to the latest versions but still no luck on having face detection on iOS devices.

**Comment by ReubenBeeler2** [comment]
I am also having trouble on iOS. Unfortunately, I have no idea what problem you are experiencing, as you did not mention anything other than 'face detection', which makes it pretty much impossible for anyone to help you. Please indicate (specifically) what the problem is.

**Comment by SelanDeemantha** [comment]
@ReubenBeeler2, Did you able to do face detection in IOS device

**Comment by doanbh** [comment]
Same issues, Is there any way to solve this problem?

**Comment by fbernaly** [comment]
Face detection in the latest plugin version: 

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_face_detection

Try the example app but make sure to read the [Getting Started](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit/example#getting-started)

More details here:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
