### ISSUE TITLE
Can't run the example

### ISSUE THREAD

**Issue by detzioni** [bharat-biradar/Google-Ml-Kit-plugin#105]
I am trying to run the example on Android with the following setting:
----
### flutter doctor -v 
[✓] Flutter (Channel master, 2.5.0-2.0.pre.113, on macOS 11.5.1 20G80
    darwin-x64, locale en-US)
    • Flutter version 2.5.0-2.0.pre.113 at /Users/up/Development/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0abf02f855 (3 days ago), 2021-07-30 17:44:02 -0700
    • Engine revision 29f9df723f
    • Dart version 2.14.0 (build 2.14.0-368.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/up/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (5 available)
    • SM A505F (mobile) • R58M36PRCDL        • android-arm64  • Android 11 (API
      30)
    • macOS (desktop)   • macos              • darwin-x64     • macOS 11.5.1
      20G80 darwin-x64
    • Chrome (web)      • chrome             • web-javascript • Google Chrome
      92.0.4515.107

• No issues found!
----

### I get an error when running flutter run  --verbose-system-logs  
----
Launching lib/main.dart on SM A505F in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /Users/up/Development/samples/Google-Ml-Kit-plugin/example/android/app/src/debug/google-services.json
  /Users/up/Development/samples/Google-Ml-Kit-plugin/example/android/app/src/google-services.json
  /Users/up/Development/samples/Google-Ml-Kit-plugin/example/android/app/src/Debug/google-services.json
  /Users/up/Development/samples/Google-Ml-Kit-plugin/example/android/app/google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Running Gradle task 'assembleDebug'...                              3.4s
Exception: Gradle task assembleDebug failed with exit code 1

----

**Any** help will be appreciated on what should be in the _google-services.json_

**Comment by bharat-biradar** [comment]
@detzioni It is due to missing firebase's `google-services.json` file. You can add your own JSON file from any of you existing firebase project.

**Comment by detzioni** [comment]
Thank you
