### ISSUE TITLE
How is my app able to run face detect even when libface_detector_v2_jni.so is not included ?

### ISSUE THREAD

**Issue by radha1990kumari** [bharat-biradar/Google-Ml-Kit-plugin#108]
I built an app earlier (using only face detection) and built a release apk (with excluding  unused models ) ,the size of my apk was 35.6 mb ,but after making some changes to app and building the apk I notice size to increase to 53.8 ,on analyzing apk  I find that my earlier apk didn't include `libface_detector_v2_jni.so` file and still my app was able to detect face .
Code for face detection
```dart 
  final InputImage inputImage = InputImage.fromFilePath(pickedFile.path);
      final FaceDetector faceDetector = GoogleMlKit.vision
          .faceDetector(FaceDetectorOptions(mode: FaceDetectorMode.accurate));
      List<Face> outputFaces = await faceDetector.processImage(inputImage);
```
#### Old apk size :
![old](https://user-images.githubusercontent.com/80261855/128054314-2bbe979a-d8b7-4a8e-b989-3ba9b5a1a250.png)
#### New apk size :
![new](https://user-images.githubusercontent.com/80261855/128054424-7e5eabb5-4d04-47c1-bdae-672838951286.png)
@bharat-biradar , I am only using face detection to get the bounding box (no contour detection, smile detection ,etc) how can I reduce the size of my app further ?

#### Difference
![diff](https://user-images.githubusercontent.com/80261855/128170904-ca91b03e-9ef7-45b3-8a47-08697dd6be4b.png)

**Comment by radha1990kumari** [comment]
Using the version `0.7.0`  doesn't bundles the models and this seems to give same  files as my old apk , but it gives this error
```
E/flutter (18628): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(FaceDetectorError, com.google.mlkit.common.MlKitException: Internal error has occurred when executing ML Kit tasks, null, null)
```

**Comment by bharat-biradar** [comment]
@radha1990kumari What version did your old apk use.

**Comment by radha1990kumari** [comment]
@bharat-biradar , I was using `0.7.0` and  I found the issue earlier my app was able to also run on emulator but sometime after when I tried again it crashed my app , hence I suspected  it will also crash in my release apk but it doesn't so for the time being I am closing the issue

**Comment by fbernaly** [comment]
We released a new version of [google_ml_kit](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit) in which we have split all the plugins in multiple plugins to avoid removing the models for API you are not using, go to our readme and start using the new plugin you need.

More details here:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
