### ISSUE TITLE
After 0.7.0 App Crashes on Image Processing Due to Firebase dependency

### ISSUE THREAD

**Issue by sikandernoori** [bharat-biradar/Google-Ml-Kit-plugin#109]
════════ Exception caught by widgets library ═══════════════════════════════════
The following CameraException was thrown building ValueListenableBuilder<CameraValue>(dirty, state: _ValueListenableBuilderState<CameraValue>#1501f):
CameraException(Disposed CameraController, buildPreview() was called on a disposed CameraController.)

The relevant error-causing widget was
CameraPreview
lib/VisionDetectorViews/camera_view.dart:121
When the exception was thrown, this was the stack
#0      CameraController._throwIfNotInitialized
package:camera/src/camera_controller.dart:775
#1      CameraController.buildPreview
package:camera/src/camera_controller.dart:529
#2      CameraPreview.build.<anonymous closure>
package:camera/src/camera_preview.dart:34
#3      _ValueListenableBuilderState.build
package:flutter/…/widgets/value_listenable_builder.dart:187
#4      StatefulElement.build
package:flutter/…/widgets/framework.dart:4691
...

...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Incorrect use of ParentDataWidget.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
A CameraController was used after being disposed.
════════════════════════════════════════════════════════════════════════════════
[Camera] Failed to read exposureBiasesByMode dictionary: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL}
8.4.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI). Read more: https://goo.gl/ctyzm8.

*** Terminating app due to uncaught exception 'FIRAppNotConfigured', reason: 'The default Firebase app instance must be configured. To configure, call `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) in the App Delegate's `application:didFinishLaunchingWithOptions:` (`application(_:didFinishLaunchingWithOptions:)` in Swift).'
*** First throw call stack:
(0x189671298 0x19d3cb480 0x189572bd0 0x103f0019c 0x103f01a10 0x103f01990 0x102dd4f84 0x102dd5210 0x102dd57a4 0x102f39bd4 0x102f3906c 0x102f392c4 0x102f37728 0x102f375cc 0x10483eccc 0x106d2c390 0x106d2c1e4 0x106d28740 0x109b1ea60 0x10982fd7c 0x109b39070 0x109ad31d4 0x109ad59fc 0x1895f10f0 0x1895f0cf0 0x1895f01c4 0x1895ea4fc 0x1895e9818 0x19fcef570 0x18bf150e8 0x18bf1a664 0x102dd387c 0x1892c8140)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001b4d9e7b0 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1b4d9e7b0 <+8>:  b.lo   0x1b4d9e7cc               ; <+36>
    0x1b4d9e7b4 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1b4d9e7b8 <+16>: mov    x29, sp
    0x1b4d9e7bc <+20>: bl     0x1b4d7b1fc               ; cerror_nocancel
Target 0: (Runner) stopped.
Lost connection to device.

**Comment by pjbwchn** [comment]
I had the same error. It would be great to get this fixed to work independently of Firebase. 

I did manage to remove this error, not an ideal fix:

1. In AppDelegate.swift file:
add: import FirebaseCore and add FirebaseApp.configure(),
for example:

import UIKit
import Flutter
import FirebaseCore

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    
    GeneratedPluginRegistrant.register(with: self)
    FirebaseApp.configure()
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)

  }

}

2. In Xcode copy 'FirebaseCore' folder from another Firebase project in to the 'iOS/Pods' folder

3. Create a GoogleService-Info.plist file from the Firebase website and copy it into the folder: iOS/Runner

**Comment by sikandernoori** [comment]
Not a Good Idea.
this Package is already too heavy due to unwanted libraries and now adding Firebase libs on top of it for No reason.

Use 0.60 version Instead.

**Comment by CaoGiaHieu-dev** [comment]
hi . i getting this issue too . i using object detector but it only used on version 0.7.0 . anything suggest ?

**Comment by ranulfo** [comment]
> import FirebaseCore

this work for me, thanks

**Comment by fbernaly** [comment]
We released a new version of [google_ml_kit](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit) in which we have split all the plugins in multiple plugins to avoid removing the models for API you are not using, go to our readme and start using the new plugin you need.


Also, noticed that if you are using [Image Labeling](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_image_labeling) or [Object Detection and Tracking](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_object_detection) you still need to have a Firebase dependency for the custom models that the Google's API offers:

- [Custom Models for Image Labeling](https://developers.google.com/ml-kit/vision/image-labeling/custom-models/ios)
- [Custom Models for  Object Detection](https://developers.google.com/ml-kit/vision/object-detection/custom-models/ios)

For that reason the example app still requires you to add `GoogleService-Info.plist` to run it in iOS just as @pjbwchn  mentioned above.

More details here:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
