### ISSUE TITLE
Crashing app when running  `facedetection` in Image stream function of `camera` plugin .   

### ISSUE THREAD

**Issue by radha1990kumari** [bharat-biradar/Google-Ml-Kit-plugin#110]
ML-kit version `0.7.0`
```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdc8f70cc
    r0 dc8f70cc  r1 c7794c00  r2 00000077  r3 00000000
    r4 c7794c00  r5 c77820ef  r6 00000002  r7 000000a0
    r8 00000001  r9 00000002  sl 00000001  fp dc8f70cc
    ip fffffec0  sp c6bf9588  lr 000000f0  pc ca0eb460  cpsr 200d0010
backtrace:
    #00 pc 003d7460  /data/data/com.google.android.gms/app_chimera/m/0000005e/n/armeabi-v7a/libface_detector_v2_jni.so
Tombstone written to: /data/tombstones/tombstone_08
```

**Comment by devtronic** [comment]
> @bharat-biradar ,downgrading to `0.6.0` works but it bloats my apk even after adding ignore code in gradle, how can I remove the models folder (containing models for contours ,etc ) without breaking my app. I am only using face detection, to get bounding boxes around all the faces in the image.

You can remove it in the build.gradle. More details:
https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/26

**Comment by fbernaly** [comment]
We released a new version of [google_ml_kit](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit) in which we have split all the plugins in multiple plugins to avoid removing the models for API you are not using, go to our readme and start using the new plugin you need.

More details here:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
