### ISSUE TITLE
Can we use this plugin to check if a video has inappropriate content like nudity or violence

### ISSUE THREAD

**Issue by aytunch** [bharat-biradar/Google-Ml-Kit-plugin#111]
Hi thanks for this library @bharat-biradar 
I want to do this on the device not on the cloud.
Our users record and chooses videos from their camera or internal storage.
I want to process these videos and check if they are safe before uploading them to Firebase storage.
By using ffmpeg i can make the videos in to many images so I can feed them to this plugin.
Do I need a seperate model for the inappropriate filtering?

Could you please direct me to the right path?

EDIT: I have seen a product called `SafeSearch` in Google Cloud Vision
https://cloud.google.com/blog/products/ai-machine-learning/filtering-inappropriate-content-with-the-cloud-vision-api
Does this help with Flutter and doing it in the client?
It gives results very suitable for my case: 

```
"safeSearchAnnotation" : {
      "spoof" : "VERY_UNLIKELY",
      "medical" : "UNLIKELY",
      "adult" : "VERY_UNLIKELY",
      "violence" : "VERY_UNLIKELY"
   }
```

**Comment by bharat-biradar** [comment]
@aytunch I looked at the API, `safe-search` is not supported by the standalone kit. If you want it to use with `image-labeling` maybe you would need a custom model (I am not sure as I don't have much knowledge with ml) which detects something like labels like `spoof`, `medical`, `adult` etc... with a given confidence score. And you can then decide likely and unlikely based on the confidence score. Also you would have to make sure the model is [compatible](https://developers.google.com/ml-kit/custom-models#model-compatibility) with the ml kit.

The second option might be to use [this](https://cloud.google.com/vision/docs/detecting-safe-search#explicit_content_detection_on_a_local_image) or to use the [googleapi](https://pub.dev/packages/googleapis) package provided by google, this seems like a better option. I found an [issue](https://github.com/google/googleapis.dart/issues/67) on using cloud vision, hope this helps. I am closing the issue as it's not related to our plugin.
