### ISSUE TITLE
Text Detection is not working on ios while on android it is working.

### ISSUE THREAD

**Issue by HamadBangash353** [bharat-biradar/Google-Ml-Kit-plugin#113]
```
final inputImage = InputImage.fromFile(widget.imgPath!);

    TxtExtractionLoader(context);
    final RecognisedText recognisedText =
    await textDetector.processImage(inputImage);
    extractedText = recognisedText.text;

    for (TextBlock block in recognisedText.blocks) {
      final Rect rect = block.rect;
      final List<Offset> cornerPoints = block.cornerPoints;
      final String text = block.text;
      final List<String> languages = block.recognizedLanguages;

      for (TextLine line in block.lines) {
        // Same getters as TextBlock
        for (TextElement element in line.elements) {
         print("helooooooooo");
         extractedText=element.text;
        }
      }

    }
    print(extractedText);
```

**Comment by pvkhaijvb** [comment]
[this is my solution](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/94#issuecomment-898934212)

**Comment by bharat-biradar** [comment]
@pvkhaijvb If possible, can you please open a PR with your solution, so we may check and merge it? It will be helpful to others in the future as well.

**Comment by noeama** [comment]
This is working fine on Android but not on iOS:

`Future<String> textFromImage(File image) async {
    final InputImage inputImage = InputImage.fromFile(image);
    final TextDetector textDetector = GoogleMlKit.vision.textDetector();
    RecognisedText recognisedText;
    String returnText = '';

    try {
      recognisedText = await textDetector.processImage(
          inputImage);
    }catch(e){
      print('TEXT FROM IMAGE ERROR: ${e.toString()}');
      return 'No Detected Text';
    }

    for (TextBlock block in recognisedText.blocks) {
      returnText += block.text;
      print('TEXT FROM IMAGE BLOCK: ${block.text}');
      for (TextLine line in block.lines) {
        print('TEXT FROM IMAGE LINE: ${line.text}');
        for (TextElement element in line.elements) {
          print('TEXT FROM IMAGE ELEMENT: ${element.text}');
        }
      }
    }
    return returnText;
  }`

I have set up iOS as described on pub.dev and I am using google_ml_kit 0.7.3. Am I missing something?

**Comment by fbernaly** [comment]
We released a new version of [google_ml_kit](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit) in which we have split all the plugins in multiple plugins to avoid removing the models for API you are not using, go to our readme and start using the new plugin you need.

More details here:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_text_recognition
