### ISSUE TITLE
[iOS] GooggleService-Info.plist is needed building iOS app 

### ISSUE THREAD

**Issue by goodsw4all** [bharat-biradar/Google-Ml-Kit-plugin#114]
First of all, thank you for the plug-in. 👍 

I get this error message while buidling for iOS
error: Build input file cannot be found: '/Volumes/MultiMediaHDD/Projects/FlutterProjects/Google-Ml-Kit-plugin/example/ios/Runner/GoogleService-Info.plist' (in target 'Runner' from project 'Runner')

In order to solve this issue, I had to download 'GoogleService-Info.plist' from Firebase and copy it into Runner
I'm a little confused that ML kit standalone version also need that file?

Any Idea would be helpful for me.
Thanks

**Comment by CaoGiaHieu-dev** [comment]
seem like a image labelling in version 0.7.0 need firebase to doing something on that . you can find that in change log https://pub.dev/packages/google_ml_kit/changelog 
every else seem like not doing anything on firebase .

**Comment by fbernaly** [comment]
@CaoGiaHieu-dev : you are right the example app needs the `GoogleService-Info.plist` to demo a feature for image labeling using a remote model, but when you are using the plugin for your app you do not need the `GoogleService-Info.plist` unless you need Firebase.

**Comment by CaoGiaHieu-dev** [comment]
@fbernaly 
i still need to add GoogleService-Info.plist when using version 0.7.0 . i still not know how to ignore image labeling .
btw could you mirgate ios in package . i see that its using something call libstdc++ (sorry im not good at ios and im stucking in this issue for 2 week ). i really need support ASAP
