### ISSUE TITLE
iOS MLKInvalid Local Model

### ISSUE THREAD

**Issue by Pranet-Hiranandani** [bharat-biradar/Google-Ml-Kit-plugin#115]
Hi, my app is running fine on android but on iOS I am getting an error, 'Terminating due to uncaught exception "MLKInvalidLocalModel" reason: Local model path (model.tflite) is invalid." 
My tflite file is placed is ios/Runner/Resources/model.tflite. Model is showing in Copy Bundle Resources. I experimented with trying to use flutter_assets/ and with CustomLocalModel.file and CustomLocalModel.asset. My google_ml_kit version- 0.7.0 and have followed all the steps for installation. Can somebody please help me with this issue. I have been trying for a long while without any luck.

**Comment by Pranet-Hiranandani** [comment]
The model is working and runs fine on Android. Only getting this issue on iOS

**Comment by Pranet-Hiranandani** [comment]
Hi, can someone please help me with this issue, I'm really struggling a lot. @bharat-biradar

**Comment by fbernaly** [comment]
We released a new version of [google_ml_kit](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit) in which we have split all the plugins in multiple plugins to avoid removing the models for API you are not using, go to our readme and start using the new plugin you need.

More details here:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
