### ISSUE TITLE
This lib contain all ML libs, it should be divided 

### ISSUE THREAD

**Issue by tim-teacher** [bharat-biradar/Google-Ml-Kit-plugin#116]
This lib contain all ML libs, it should be divided to be able use only desired parts.

**Comment by bharat-biradar** [comment]
@tim-teacher Yes this has been a long-standing problem and we have already received complaints regarding this issue. We have yet to decide if we should split. But please feel free to open a PR with suggested changes.

**Comment by nombrekeff** [comment]
Yeah, something should be done as it's a pain to deal with.

**Comment by Parthib** [comment]
I know there are a few solutions to reduce the apk size in Android according to this thread: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/26. It helped reduce my apk size significantly.

Anyone know if a similar solution exists for iOS?

**Comment by fbernaly** [comment]
We released a new version of [google_ml_kit](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit) in which we have split all the plugins in multiple plugins to avoid removing the models for API you are not using, go to our readme and start using the new plugin you need.

More details here:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
