### ISSUE TITLE
cant not use pose detection

### ISSUE THREAD

**Issue by CaoGiaHieu-dev** [bharat-biradar/Google-Ml-Kit-plugin#119]
hi . im using pose detection and face detection in one func and get this error when build on ios 

<details>
<summary>error log</summary>

```
I0819 11:57:47.312956       2 gl_context.cc:348] GL version: 3.0 (OpenGL ES 3.0 Metal - 68.8)
I0819 11:57:47.313870       4 gl_context.cc:348] GL version: 3.0 (OpenGL ES 3.0 Metal - 68.8)
I0819 11:57:47.312968       3 gl_context.cc:348] GL version: 3.0 (OpenGL ES 3.0 Metal - 68.8)
I0819 11:57:47.321819       5 gl_context.cc:348] GL version: 3.0 (OpenGL ES 3.0 Metal - 68.8)
I0819 11:57:47.332369       6 gl_context.cc:348] GL version: 3.0 (OpenGL ES 3.0 Metal - 68.8)
I0819 11:57:47.341228       7 gl_context.cc:348] GL version: 3.0 (OpenGL ES 3.0 Metal - 68.8)
I0819 11:57:47.350565       8 gl_context.cc:348] GL version: 3.0 (OpenGL ES 3.0 Metal - 68.8)
Initialized TensorFlow Lite runtime.
INFO: Initialized TensorFlow Lite runtime.
Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
I0819 11:57:47.381343       9 gl_context.cc:348] GL version: 3.0 (OpenGL ES 3.0 Metal - 68.8)
I0819 11:57:47.432566      10 gl_context.cc:348] GL version: 3.0 (OpenGL ES 3.0 Metal - 68.8)
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(Error 2, com.google.mlkit, Detection failed because the detector was deallocated, null)
#0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:597
#1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:158
<asynchronous suspension>
#2      PoseDetector.processImage
package:google_ml_kit/…/vision/pose_detector.dart:35
<asynchronous suspension>
#3      FaceDetectorConfig._processImage
package:ekyc_flutter/…/face_detector/face_detector_config.dart:426
<asynchronous suspension>
#4      FaceDetectorConfig._processCameraImage
package:ekyc_flutter/…/face_detector/face_detector_config.dart:279
<asynchronous suspension>

```

</details>
version : google_ml_kit: ^0.7.0

**Comment by bharat-biradar** [comment]
@CaoGiaHieu-dev In your code are you trying to use the detector after calling `close()`? Because the log says it was failed because the detector was deallocated.

**Comment by CaoGiaHieu-dev** [comment]
@bharat-biradar 
No i didn't . i'm just init then process though the camera streamImage . It work fine with face detection but not pose detection

**Comment by bharat-biradar** [comment]
can you provide me the code snippet you are using?

**Comment by CaoGiaHieu-dev** [comment]
@bharat-biradar 
sure .
``
void init(){
 _faceDetector =
      GoogleMlKit.vision.faceDetector(const FaceDetectorOptions(
    enableClassification: true,
    enableTracking: true,
    enableLandmarks: true,
    mode: FaceDetectorMode.accurate,
  ));
  _poseDetector = GoogleMlKit.vision.poseDetector(
      poseDetectorOptions: PoseDetectorOptions(
    model: PoseDetectionModel.base,
    mode: PoseDetectionMode.singleImage,
  ));
}
...
 Future<void> _processImage(InputImage inputImage, CameraImage image) async {
    if (_isBusyProcess) return;

    final faces = await _faceDetector.processImage(inputImage);
    final poses = await _faceDetector.processImage(inputImage); // error in here
    ....
 ``

**Comment by fbernaly** [comment]
We released a new version of [google_ml_kit](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit) in which we have split all the plugins in multiple plugins to avoid removing the models for API you are not using, go to our readme and start using the new plugin you need.

Start using: 

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_face_detection
https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_pose_detection

More details here:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
