### ISSUE TITLE
Support for iOS

### ISSUE THREAD

**Issue by ak111in** [bharat-biradar/Google-Ml-Kit-plugin#12]
Do you plan to add iOS support also in the package?

**Comment by bharat-biradar** [comment]
@ak111in Thanks for opening an issue. Sorry for replying late. Yes I plan to ad IOS support but it may take some time.

**Comment by fbernaly** [comment]
are you open to contribution? I am interested in using iOS as well

**Comment by bharat-biradar** [comment]
Yes I am but currently I am not taking IOS contributions as I am in the process of learning myself. I'll notify you within 10-15 days. Thanks for showing your interest.

**Comment by festapp86** [comment]
We would also be highly interested in having a iOS version, too. Also willing to contribute to the project. Please give us an update any time soon. Thanks

**Comment by AlexHartford** [comment]
Yes, with firebase_ml_vision getting sacked I'm quite positive you'll have a line of us wanting to contribute to get this production ready.

**Comment by fbernaly** [comment]
@AlexHartford, @festapp86: we have a couple of PR in the line for some refactors, and after I will give you green light to start helping with some iOS features. I already added some, you can check the README, but I will need help with the rest.

**Comment by fbernaly** [comment]
@AlexHartford , @festapp86 : we just released 0.5.0. That includes some iOS features, but we need your collaboration if you want to help us with some of the NL features. Pick one and let me know which one you are taking.

**Comment by AlexHartford** [comment]
@fbernaly I have no experience with iOS so I won't be very helpful on this front, but I'll be keeping an eye out for future issues that I can tackle for you. Appreciate your work on this package, it's likely going to blow up soon!
