### ISSUE TITLE
Throw an exception about downloading module

### ISSUE THREAD

**Issue by sgsm74** [bharat-biradar/Google-Ml-Kit-plugin#120]
Hey guys I wrote a program based on example project, but every time I faced this exception:
`PlatformException (PlatformException(TextDetectorError, com.google.mlkit.common.MlKitException: Waiting for the text optional module to be downloaded. Please wait., null, null))`

what should I do?

**Comment by sonth-bhsoft** [comment]
Hello,
I got the same issue. Any idea?

**Comment by sonth-bhsoft** [comment]
@sgsm74 I found that the issue only happens on Emulator. It works well on a real device.

**Comment by sgsm74** [comment]
> @sgsm74 I found that the issue only happens on Emulator. It works well on a real device.

No, for me it doesnt work even on real device.

**Comment by MenaRaafat** [comment]
I think we need a way to query the download status in general, in order to properly display a message for the user. Like "Still downloading model" or "Please turn on Internet connection to download model" etc.

**Comment by fbernaly** [comment]
We released a new version of [google_ml_kit](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit) in which we have split all the plugins in multiple plugins to avoid removing the models for API you are not using, go to our readme and start using the new plugin you need.

Start using: 
https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_text_recognition

More details here:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
