### ISSUE TITLE
[iOS] - App is crashing while trying to use barcode scanner

### ISSUE THREAD

**Issue by julian-wpt** [bharat-biradar/Google-Ml-Kit-plugin#123]
**Bug description**
I have implemented the plugin in version 0.7.1 to use the barcode scanner. In Android this works without problems. When I start the app, I get the following error on iOS (I implemented the requirements in readme): 

8.6.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI). Read more: https://goo.gl/ctyzm8.
*** Terminating app due to uncaught exception 'FIRAppNotConfigured', reason: 'The default Firebase app instance must be configured. To configure, call `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) in the App Delegate's `application:didFinishLaunchingWithOptions:` (`application(_:didFinishLaunchingWithOptions:)` in Swift).'
*** First throw call stack:
(0x19ffab298 0x1b3d05480 0x19feacbd0 0x1031750fc 0x103176970 0x1031768f0 0x102049f94 0x10204a1f0 0x10204a73c 0x1021aeb34 0x1021adfcc 0x1021ae224 0x1021ac688 0x1021ac52c 0x102060bec 0x105f947b8 0x105f944b0 0x105f9ccf8 0x108e0ea60 0x108b1fd7c 0x108e29070 0x108dc31d4 0x108dc59fc 0x19ff2b0f0 0x19ff2acf0 0x19ff2a1c4 0x19ff244fc 0x19ff23818 0x1b6629570 0x1a284f0e8 0x1a2854664 0x102048a18 0x19fc02140)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001cbd557b0 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1cbd557b0 <+8>:  b.lo   0x1cbd557cc               ; <+36>
    0x1cbd557b4 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1cbd557b8 <+16>: mov    x29, sp
    0x1cbd557bc <+20>: bl     0x1cbd321fc               ; cerror_nocancel
Target 0: (Runner) stopped.
Lost connection to device.

**Flutter information**
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale de-DE)
    • Flutter version 2.2.3 at /Users/wipotec/src/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/wipotec/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • iPhone von Julian (mobile) • ba28530691c427572254fe27337252cf63b209b7 • ios            • iOS 14.6
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 92.0.4515.159

• No issues found!

**Device information**
iPhone 7, iOS 14.6

**Comment by KevinBeckers** [comment]
I experienced the same issue. Changing `ResolutionPreset.veryHigh` to `ResolutionPreset.medium` on the CameraController solved it for me.

**Comment by julian-wpt** [comment]
I get the error at every `ResolutionPreset`, even with `ResolutionPreset.low` or `ResolutionPreset.medium`.

**Comment by natalia-dev** [comment]
Same problem here. Changing `ResolutionPreset ` made no difference.

**Comment by natalia-dev** [comment]
Downgraded to version 0.6.0 and it worked

**Comment by julian-wpt** [comment]
I retried it with version 0.7.2, but the error is still present. The problem with version 0.6.0 is, that it does not yet include the `BarcodeFormat` (in `BarcodeValue`) in the `Barcode` result.

**Comment by hugopretorius914** [comment]
I too have this issue, should I just configure firebase? That seems like a lot...

**Comment by paj-co** [comment]
I have just opened new issue with the same problem. Didn't noticed that the problem was already issued and exists for so long. 
Is it a sign that this library has been somewhat neglected? 🤔

**Comment by fbernaly** [comment]
We released a new version of [google_ml_kit](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit) in which we have split all the plugins in multiple plugins to avoid removing the models for API you are not using, go to our readme and start using the new plugin you need.

Start using:
https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_barcode_scanning

More details here:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
