### ISSUE TITLE
MLKitTextRecognitionCommon.MLKTextElement

### ISSUE THREAD

**Issue by officialFlutterDeveloper** [bharat-biradar/Google-Ml-Kit-plugin#124]
Launching lib/main.dart on iPhone 12 in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           12.5s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[50997]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1fd2dfad8) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1140882b8). One of the two will be used. Which one is undefined.
    objc[50997]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1fd2dfb28) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x114088308). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **

Xcode's output:
↳
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    /Users/farhan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/google_ml_kit-0.7.0/ios/Classes/vision/TextRecognizer.m:91:26: error: declaration of 'MLKTextRecognizedLanguage' must be imported from module 'MLKitTextRecognitionCommon.MLKTextRecognizedLanguage' before it is required
          languages:(NSArray<MLKTextRecognizedLanguage *> *)languages
                             ^
    In module 'MLKitTextRecognition' imported from /Users/farhan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/google_ml_kit-0.7.0/ios/Classes/vision/TextRecognizer.m:3:
    In module 'MLKitTextRecognitionCommon' imported from /Users/farhan/AndroidStudioProjects/ml_advice_app/ios/Pods/MLKitTextRecognition/Frameworks/MLKitTextRecognition.framework/Headers/MLKTextRecognizer+Latin.h:4:
    /Users/farhan/AndroidStudioProjects/ml_advice_app/ios/Pods/MLKitTextRecognitionCommon/Frameworks/MLKitTextRecognitionCommon.framework/Headers/MLKTextRecognizedLanguage.h:7:12: note: declaration here is not visible
    @interface MLKTextRecognizedLanguage : NSObject
               ^
    /Users/farhan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/google_ml_kit-0.7.0/ios/Classes/vision/TextRecognizer.m:28:41: warning: 'textRecognizer' is deprecated: Please use `textRecognizer(options:)` instead. [-Wdeprecated-declarations]
        textRecognizer = [MLKTextRecognizer textRecognizer];
                                            ^
    In module 'MLKitTextRecognition' imported from /Users/farhan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/google_ml_kit-0.7.0/ios/Classes/vision/TextRecognizer.m:3:
    /Users/farhan/AndroidStudioProjects/ml_advice_app/ios/Pods/MLKitTextRecognition/Frameworks/MLKitTextRecognition.framework/Headers/MLKTextRecognizer+Latin.h:21:5: note: 'textRecognizer' has been explicitly marked deprecated here
        __deprecated_msg("Please use `textRecognizer(options:)` instead.");
        ^
    In module 'UIKit' imported from /Users/farhan/AndroidStudioProjects/ml_advice_app/ios/Pods/Target Support Files/google_ml_kit/google_ml_kit-prefix.pch:2:
    In module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
    In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/usr/include/sys/cdefs.h:200:48: note: expanded from macro '__deprecated_msg'
            #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                          ^
    /Users/farhan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/google_ml_kit-0.7.0/ios/Classes/vision/TextRecognizer.m:40:42: error: definition of 'MLKText' must be imported from module 'MLKitTextRecognitionCommon.MLKText' before it is required
            textResult[@"text"] = visionText.text;
                                             ^
    In module 'MLKitTextRecognition' imported from /Users/farhan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/google_ml_kit-0.7.0/ios/Classes/vision/TextRecognizer.m:3:
    In module 'MLKitTextRecognitionCommon' imported from /Users/farhan/AndroidStudioProjects/ml_advice_app/ios/Pods/MLKitTextRecognition/Frameworks/MLKitTextRecognition.framework/Headers/MLKTextRecognizer+Latin.h:4:
    /Users/farhan/AndroidStudioProjects/ml_advice_app/ios/Pods/MLKitTextRecognitionCommon/Frameworks/MLKitTextRecognitionCommon.framework/Headers/MLKText.h:9:12: note: definition here is not reachable
    @interface MLKText : NSObject
               ^
    /Users/farhan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/google_ml_kit-0.7.0/ios/Classes/vision/TextRecognizer.m:47:33: error: definition of 'MLKTextBlock' must be imported from module 'MLKitTextRecognitionCommon.MLKTextBlock' before it is required
                 cornerPoints:block.cornerPoints
                                    ^
    In module 'MLKitTextRecognition' imported from /Users/farhan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/google_ml_kit-0.7.0/ios/Classes/vision/TextRecognizer.m:3:
    In module 'MLKitTextRecognitionCommon' imported from /Users/farhan/AndroidStudioProjects/ml_advice_app/ios/Pods/MLKitTextRecognition/Frameworks/MLKitTextRecognition.framework/Headers/MLKTextRecognizer+Latin.h:4:
    /Users/farhan/AndroidStudioProjects/ml_advice_app/ios/Pods/MLKitTextRecognitionCommon/Frameworks/MLKitTextRecognitionCommon.framework/Headers/MLKTextBlock.h:11:12: note: definition here is not reachable
    @interface MLKTextBlock : NSObject
               ^
    /Users/farhan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/google_ml_kit-0.7.0/ios/Classes/vision/TextRecognizer.m:57:36: error: definition of 'MLKTextLine' must be imported from module 'MLKitTextRecognitionCommon.MLKTextLine' before it is required
                     cornerPoints:line.cornerPoints
                                       ^
    In module 'MLKitTextRecognition' imported from /Users/farhan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/google_ml_kit-0.7.0/ios/Classes/vision/TextRecognizer.m:3:
    In module 'MLKitTextRecognitionCommon' imported from /Users/farhan/AndroidStudioProjects/ml_advice_app/ios/Pods/MLKitTextRecognition/Frameworks/MLKitTextRecognition.framework/Headers/MLKTextRecognizer+Latin.h:4:
    /Users/farhan/AndroidStudioProjects/ml_advice_app/ios/Pods/MLKitTextRecognitionCommon/Frameworks/MLKitTextRecognitionCommon.framework/Headers/MLKTextLine.h:11:12: note: definition here is not reachable
    @interface MLKTextLine : NSObject
               ^
    /Users/farhan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/google_ml_kit-0.7.0/ios/Classes/vision/TextRecognizer.m:67:43: error: definition of 'MLKTextElement' must be imported from module 'MLKitTextRecognitionCommon.MLKTextElement' before it is required
                         cornerPoints:element.cornerPoints
                                              ^
    In module 'MLKitTextRecognition' imported from /Users/farhan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/google_ml_kit-0.7.0/ios/Classes/vision/TextRecognizer.m:3:
    In module 'MLKitTextRecognitionCommon' imported from /Users/farhan/AndroidStudioProjects/ml_advice_app/ios/Pods/MLKitTextRecognition/Frameworks/MLKitTextRecognition.framework/Headers/MLKTextRecognizer+Latin.h:4:
    /Users/farhan/AndroidStudioProjects/ml_advice_app/ios/Pods/MLKitTextRecognitionCommon/Frameworks/MLKitTextRecognitionCommon.framework/Headers/MLKTextElement.h:13:12: note: definition here is not reachable
    @interface MLKTextElement : NSObject
               ^
    1 warning and 5 errors generated.
    In file included from /Users/farhan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/google_ml_kit-0.7.0/ios/Classes/GoogleMlKitPlugin.m:1:
    /Users/farhan/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/google_ml_kit-0.7.0/ios/Classes/GoogleMlKitPlugin.h:40:22: warning: unused function 'getFlutterError' [-Wunused-function]
    static FlutterError *getFlutterError(NSError *error) {
                         ^
    1 warning generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

Could not build the application for the simulator.
Error launching application on iPhone 12.

app works on ANDROID but can not make the build on iOS

**Comment by Aaron009** [comment]
I also encountered this problem, is it solved?

**Comment by officialFlutterDeveloper** [comment]
@Aaron009 no it’s not fixed and I doubt it will ever get fixed I been waiting for a fix for a whole month I thought this plugin was made by official google employee seems like it was made by and worked on by 2 people who don’t have time to fix issues

**Comment by meomap** [comment]
Man, we should respect hard works of all developers out there 🙏

I don't know anything about obj-c or cocoa pod but it seems there's a dependencies problem here. The latest ml kit versions are not supported by plugin yet: 

```
MLKitTextRecognition (v2) | 1.4.0-beta1 | 08/11/2021
MLKitTextRecognitionCommon | 1.0.0-beta1 | 08/11/2021
```

My fix is to use the same dependencies as plugin's developers.  Just keep your `ios/Podfile.lock` and [example/ios/Podfile.lock](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/4c2ca1f42ee4d8287dee8862b6220ec14e331517/example/ios/Podfile.lock) in sync. 

Pin the exact version of `MLKitTextRecognition` and other related ml kit dependencies. Then rerun `pod install`

**Comment by fbernaly** [comment]
We released a new version of [google_ml_kit](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit) in which we have split all the plugins in multiple plugins to avoid removing the models for API you are not using, go to our readme and start using the new plugin you need.

Start using:
https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_text_recognition

More details here:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
