### ISSUE TITLE
Use classifier with MLKit Pose detector

### ISSUE THREAD

**Issue by sbis04** [bharat-biradar/Google-Ml-Kit-plugin#128]
The official page for MLKit Pose Detection also talks about a [pose classification option](https://developers.google.com/ml-kit/vision/pose-detection/classifying-poses) by uploading a CSV file. We have generated a CSV file and tested it in that demo native Android app, but want to use it along with this plugin as our app is mostly in Flutter.

Is there a way to use classifier with a CSV file in this plugin, or any way to add it?

**Comment by caofuqing** [comment]
How to compare the two poses?

**Comment by fbernaly** [comment]
@caofuqing: The Google's Pose Detection API only returns the landmarks, what you see in this [post](https://developers.google.com/ml-kit/vision/pose-detection/classifying-poses) is outside the scope of the original API and therefore of this plugin. To do something like that you need to use the landmarks (the output of this plugin) and feed them into a model you have trained. In that example they are using MediaPipe Colab. 

In a similar reported issue #212 , someone suggested using `https://pub.dev/packages/tflite_flutter_helper` to do that. But that is outside the scope of this plugin.
