### ISSUE TITLE
Support for iOS Language Identification

### ISSUE THREAD

**Issue by nachtmaar** [bharat-biradar/Google-Ml-Kit-plugin#129]
Hi @bharat-biradar, first of all I wanted to thank you for your work on this plugin!
I just migrated to it coming from the `firebase_ml_vision` package.

With this ticket, I want to start a conversation on the plans and possible time when the [Natural Language](https://developers.google.com/ml-kit/language/identification) features, especially the `Language Identification` is going to be implemented for iOS (they are already implemented on Android).

I migrated a custom and private implementation for `Language Identification` just to mlkit. That means I have a basic version which is working for iOS. However it is written in Swift. I can open that up, if that helps.

**Comment by bharat-biradar** [comment]
@nachtmaar Thank you for interest in plugin. Please feel free to open a PR or a draft PR if you have if you implemented a basic version but it's not yet completed even of ots written in swift. After opening a pr or to discuss what features to add in a pr please ping @fbernaly. He'll take a look when he's free (I am not good with iOS sode of things 😅).

**Comment by fbernaly** [comment]
@nachtmaar : let me know when your PR is ready for review

**Comment by nachtmaar** [comment]
Anything else we need to do in order to close this issue?
A release note about the exception for the Android side is required IMHO. Because people might already have used it and should prepare for the change in behaviour (throwing an exception then no language is detected)

**Comment by fbernaly** [comment]
@nachtmaar : I think we can close this issue

**Comment by bharat-biradar** [comment]
@fbernaly Shall I publish a new version with current changes or wait for anything else to be added?
