### ISSUE TITLE
How can i use CameraImage (camera.startImageStream) to detect pose?

### ISSUE THREAD

**Issue by huuthongdev** [bharat-biradar/Google-Ml-Kit-plugin#13]
Big thanks for your solution.

I don't know how to convert CameraImage to InputImage to use poseDetector.

**Comment by bharat-biradar** [comment]
@huuthongdev Thanks for opening an issue. I can tell how to convert camera image to input image, but it does not detect any poses with camera stream due to some problem. I have mentioned this in the README.
