### ISSUE TITLE
Chinese Text Recognition

### ISSUE THREAD

**Issue by kouseralamin** [bharat-biradar/Google-Ml-Kit-plugin#130]
I tried to OCR Chinese text with this plugin, but I was not able to do it. Can we get an update with on device text recognition for Chinese text?

This is Text Recognition v2 [LINK](https://developers.google.com/ml-kit/vision/text-recognition/v2). It works for Chinese Text on device, but there is no flutter one.

**Comment by bharat-biradar** [comment]
@kouseralamin Thank you for opening the issue. I was unaware of this release, I'll add it as soon as possible, currently I'm busy with other things.

**Comment by kouseralamin** [comment]
@bharat-biradar Thank you for your reply. I hope everything will go smoothly.

**Comment by kouseralamin** [comment]
Thank you for this update. I tested it in an android. It is working. Is there any plan for ios?

**Comment by drneamati** [comment]
May you add v2 to ios please?

**Comment by fbernaly** [comment]
We released a new version of [google_ml_kit](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit) in which we have split all the plugins in multiple plugins to avoid removing the models for API you are not using, go to our readme and start using the new plugin you need.

Start using:
https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_text_recognition 

More details here:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit

https://developers.google.com/ml-kit/vision/text-recognition/v2/languages
