### ISSUE TITLE
operating problem

### ISSUE THREAD

**Issue by cogitoo** [bharat-biradar/Google-Ml-Kit-plugin#133]
An error is reported when running the project

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Users\Lenovo\Documents\Google-Ml-Kit-plugin\example\android\app\src\debug\google-services.json
  C:\Users\Lenovo\Documents\Google-Ml-Kit-plugin\example\android\app\src\google-services.json
  C:\Users\Lenovo\Documents\Google-Ml-Kit-plugin\example\android\app\google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1

How can I solve it?

**Comment by bharat-biradar** [comment]
@cogitoo Add the google-services.json file from any of your firebase projects in `example/android/app/`. This should solve your issue.

**Comment by cogitoo** [comment]
Thank you for opening the issue.

**Comment by cogitoo** [comment]
@bharat-biradar I can't find google-services.json. I'm trying other solutions

**Comment by bharat-biradar** [comment]
@cogitoo You can get the google-services.json file from a firebase project

**Comment by cogitoo** [comment]
@bharat-biradar Thank you very much. The problem has been solved
