### ISSUE TITLE
Converting an InputImage to Image Widget with Image.memory

### ISSUE THREAD

**Issue by danielcmm** [bharat-biradar/Google-Ml-Kit-plugin#135]
Hi!

When i try to create an Image Widget from the InputImage bytes, using Image.memory function:

``
Image.memory(inputImage.bytes,fit: BoxFit.cover),
``

i get the following error: 

```
======== Exception caught by image resource service ================================================
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data

When the exception was thrown, this was the stack: 
#0      _futurize (dart:ui/painting.dart:5326:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:5194:12)
#2      instantiateImageCodec (dart:ui/painting.dart:2048:60)
<asynchronous suspension>
```

I have debugged and there is data on inputImage.bytes.

What can i do to create an image representation/widget from the InputImage class?

Thanks in advance!

**Comment by sina03030** [comment]
I HAVE THE SAME PROBLEM .
