### ISSUE TITLE
Changing some parameter the face is not recognized anymore

### ISSUE THREAD

**Issue by pdivita** [bharat-biradar/Google-Ml-Kit-plugin#138]
On my Xiaomi 10 lite 5g it works with this configuration only:
 * Portrait
 * Resolution.preset low or high (not medium)
 * Using CameraPreview inside a Stack with "StackFit.expand" (but the aspect ratio is not ok), like the example of the package

Here comes the strange things:
 * If I rotate the screen to landscape, it doesn't recognize faces anymore
 * In portait: if I remove the "StackFit.expand" the aspect ratio is ok, the face is recognized (i used debug print) but the painter doesn't paint anything

**Comment by bharat-biradar** [comment]
@pdivitia Thank you for opening the issue. I also found that face was not being detected in landscape mode I'll check what's wrong and get back to you.

**Comment by ducvu212** [comment]
same issue :(

**Comment by Arkania9** [comment]
I had the same issue with the painter not drawing when I removed 'StackFit.expand'. What I did is I sized the camera width and height and move those values directly into custom paint. 
CameraView:
    return Container(
      width: 300,
      height: 400,
      color: Colors.black,
      child: Stack(
        children: <Widget>[
          CameraPreview(_controller!),
          if (widget.customPaint != null) widget.customPaint!,
        ],
      ),
    );

then in face_detector_view inside process image function:
      customPaint = CustomPaint(
        painter: painter,
        size: Size(300, 400),
      );

**Comment by josemave2000** [comment]
I have the same issue face detection not working for the landscape. Pls, any solution? Thanks

**Comment by fbernaly** [comment]
It depends of your rotation and how you create the InputImageData, look at this:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_commons#usage

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_mlkit_commons/lib/src/input_image.dart

Feel free to send a PR if you find a better solution or improvements.
