### ISSUE TITLE
[iOS] - app crashing when trying to change `ResolutionPreset.low`.  

### ISSUE THREAD

**Issue by SebghatYusuf** [bharat-biradar/Google-Ml-Kit-plugin#139]
Hello, 
I'm trying to use the app to do text recognition and reading barcode, when I set the `ResolutionPreset.low` to `ResolutionPreset.veryHigh` / `high` /`medium` the app is crashing. 
It's running fine when I set `ResolutionPreset.low` but the issue is it's not able to detect barcode and text very well. 
here is a little of code snippet: 

```
Future _startLiveFeed() async {
    final camera = cameras[_cameraIndex];
    _controller = CameraController(
      camera,
      ResolutionPreset.low,
      enableAudio: false,
    );
    _controller?.initialize().then((_) {
      if (!mounted) {
        return;
      }
      _controller?.startImageStream(_processCameraImage);
      setState(() {});
    });
  }
```

any recommendations?

**Comment by SebghatYusuf** [comment]
Closing the issue because I haven't received any feedback.

**Comment by AlaaMarawi** [comment]
having the same problem !

**Comment by AlaaMarawi** [comment]
actually it works but very slow with ResolutionPreset.medium and crashes with ResolutionPreset.high and max (android)
