### ISSUE TITLE
Can we use the  on device translator with this plugin?

### ISSUE THREAD

**Issue by itssidhere** [bharat-biradar/Google-Ml-Kit-plugin#14]
Can we use the on-device translator with this plugin? I didn't find anything in the docs.

**Comment by bharat-biradar** [comment]
@itssidhere Thanks for opening an issue. Support for on device translator is not yet implemented. I hope to implement it soon.

**Comment by itssidhere** [comment]
Thanks for the response. Well this question is out of curiosity, is this on device ml-kit like on device translation absolutely free to use ?

**Comment by bharat-biradar** [comment]
@itssidhere Are you asking about the plugin or the original kit. If it is the original kit provided by google as far I know it's free but look at their [terms of service](https://developers.google.com/terms) for better understanding.

**Comment by itssidhere** [comment]
Yes I meant the Google kit. I am thinking if they add the billing as per usage to our firebase account or something. I used cloud translation api and it ended up blowing my billing account , I wonder if that's also the case with this ml kit.

**Comment by bharat-biradar** [comment]
@itssidhere No, I think it's free you just have to download the models here which will be run locally on the device.

**Comment by bharat-biradar** [comment]
@itssidhere On-device translator has been implemented in version 0.3.0 though only for android.

**Comment by itssidhere** [comment]
@itssidhere Great, I will check. Thanks

**Comment by jtkeyva** [comment]
@bharat-biradar any plans to implement translator for ios?
thanks
