### ISSUE TITLE
Barcode class no longer has BarcodeFormat field

### ISSUE THREAD

**Issue by jronceroscb** [bharat-biradar/Google-Ml-Kit-plugin#145]
Not sure if this is intentional, but Barcode class had a BarcodeFormat field in firebase_ml_vision plugin. 

This change means that if you allow "all" barcode formats, and you detect a barcode, you can't identify the format anymore (QR, etc), just the type (email, sms, etc).

**Comment by bharat-biradar** [comment]
@jronceroscb I believe we still provide the barcode format it can be accessed by `barcode.value.format` and there is [enum](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/4c2ca1f42ee4d8287dee8862b6220ec14e331517/lib/src/vision/barcode_scanner.dart#L45) for the all the supported barcode formats.

**Comment by jronceroscb** [comment]
> @jronceroscb I believe we still provide the barcode format it can be accessed by `barcode.value.format` and there is [enum](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/4c2ca1f42ee4d8287dee8862b6220ec14e331517/lib/src/vision/barcode_scanner.dart#L45) for the all the supported barcode formats.

You are right, I was using google_ml_kit 0.6.0, it must have been added on 0.7.x version. Thanks for the reply.
