### ISSUE TITLE
D/TransportRuntime.CctTransportBackend(14172): Making request to: https://firebaselogging.googleapis.com/v0cc/log/batch?format=json_proto3

### ISSUE THREAD

**Issue by COWRCHEN** [bharat-biradar/Google-Ml-Kit-plugin#146]
I could see this kind of logs from the android studio console. Does anyone know what it's for? can I disable the upload?

D/TransportRuntime.SQLiteEventStore( 4152): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler( 4152): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...

.................................
D/TransportRuntime.CctTransportBackend(14172): Making request to: https://firebaselogging.googleapis.com/v0cc/log/batch?format=json_proto3
I/System.out(14172): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(14172): (HTTPLog)-Static: isSBSettingEnabled false
I/TransportRuntime.CctTransportBackend(14172): Status Code: 200
I/TransportRuntime.CctTransportBackend(14172): Content-Type: application/json; charset=UTF-8
I/TransportRuntime.CctTransportBackend(14172): Content-Encoding: gzip

**Comment by aomlovebank1212** [comment]
how to fix

**Comment by fbernaly** [comment]
We released a new version of [google_ml_kit](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit) in which we have split all the plugins in multiple plugins to avoid removing the models for API you are not using, go to our readme and start using the new plugin you need.

More details here:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
