### ISSUE TITLE
Can't Scan inverted Data Matrix codes (light on dark/ white on black)

### ISSUE THREAD

**Issue by mhilalsh** [bharat-biradar/Google-Ml-Kit-plugin#148]
I'm trying to use the api to scan inverted data matrix codes (white on black) but it's not recognizing, I thought about looping on the bytes of the input image and invert the bytes but I can't find out how to do that, is there anything I can do to read inverted data matrix codes?

**Comment by mhilalsh** [comment]
Okay I solved this issue

**Comment by bharat-biradar** [comment]
@mhilalsh Can you please add your solution here, so that it can be helpful to others

**Comment by mhilalsh** [comment]
in the CameraView page, I added a piece of code in the _processCameraImage() function, CameraImage format is usually YUV by default 
YUV images consist of 3 planes Y , U and V each plane has bytes inside of it so what we want to do to the YUV image -before transforming it to an inputImage and send it to be processed- is to invert the bytes of each plane by substracting every byte from 255 (this is the way of inverting YUV images).
so after calling writeBuffer() we have a for loop which puts the bytes of each plane in the allBytes buffer, we will add another for loop before putting each plane and iterate over the bytes of the plane and substract each one from 255 

Edited code :

Future _processCameraImage(CameraImage image) async {

    final WriteBuffer allBytes = WriteBuffer();
    for (Plane plane in image.planes) {
      final p = plane.bytes;
      for (var i = 0, len = p.length; i < len; i ++) {
        p[i] = 255 - p[i];
      }
    allBytes.putUint8List(p);
    }
    final bytes = allBytes.done().buffer.asUint8List();

and the rest of the function is left as it's, of course this code can be optimized and the performance can be enhanced, if anyone can edit the code and optimize the performance that would be great.

**Comment by yuexunshi** [comment]
when i print it，it‘s wrong。
\^]0108809460304701112105121726051110202104280056\^]21121EC3<…>
what is \^] ？

**Comment by mhilalsh** [comment]
> when i print it，it‘s wrong。 ^]0108809460304701112105121726051110202104280056^]21121EC3<…> what is ^] ？

@yuexunshi Idk really, I don't even know anything about bytes or image processing I just kept manipulating the bytes and it worked for me so I thought I might share it maybe it'll work for someone else
