### ISSUE TITLE
App crashes when navigating 

### ISSUE THREAD

**Issue by mhilalsh** [bharat-biradar/Google-Ml-Kit-plugin#151]
so I'm trying to scan some datamatrix code with the scanner, and it's reading and everything is fine, then I want to navigate back (pop) with the data but it crashes and if doesn't crash the behavior is very strange it's not navigating smoothly.
the app crashes without errors or exceptions and sometimes I get a fatal error flutter signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x71b4871f08
and I also don't know what is that.

**Comment by fbernaly** [comment]
Try the latest version.

Also note that `google_ml_kit` has been split in multiples plugins, to avoid adding unnecessary dependencies to your project. You can start using `google_mlkit_barcode_scanning` instead.

More details here:
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin
