### ISSUE TITLE
Scanning with Image Picker is not working

### ISSUE THREAD

**Issue by mhilalsh** [bharat-biradar/Google-Ml-Kit-plugin#154]
I'm trying to scan data matrix codes with the Image picker feature and I tried debugging, I didn't change the code but the invoke method and the api request doesn't return anything and the barcodes list is empty, if someone knows what I might be doing wrong please help me I need to work with this Image Picker.

**Comment by mhilalsh** [comment]
I get this " {"typeNumber": "0", "errorCode": "3", "version": "85"} " when I try to print the string found in the barcodes list and when I try to view it while debugging the application crashes, does anybody know what's that?

**Comment by TrungNguyen153** [comment]
+1 problem

**Comment by bharat-biradar** [comment]
@TrungNguyen153 Sorry for replying late, can you please share the image so I can replicate the error?

**Comment by AlaaMarawi** [comment]
I am having a similar problem with both camera image and file image with barcode reader:
1- camera picture rarely gives 'Found X barcodes' with error :

>    Another exception was thrown: CameraException(Disposed CameraController, buildPreview() was called on a disposed 
>    CameraController.)
>    I/CameraDevice-JV-0( 7308): Camera now idle
>    I/flutter ( 7308): Found 2 barcodes
>    Another exception was thrown: A CameraController was used after being disposed.

other times gives 0 results with no errors

2- gallery image never gives recognized barcodes with no errors

I tried same images in livestream and it works well
exp: https://jad5p481iok18f24519n5ve1-wpengine.netdna-ssl.com/wp-content/uploads/QRtoarticle_1.jpg
exp: https://www.activebarcode.com/images/pictos/barcode2d.png

**Comment by fbernaly** [comment]
Try the latest version.

Also note that `google_ml_kit` has been split in multiples plugins, to avoid adding unnecessary dependencies to your project. You can start using `google_mlkit_barcode_scanning` instead.

More details here:
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin


So far I am able to scan both QR codes with the sample app:

![IMG_0053](https://user-images.githubusercontent.com/7014968/165397886-cafa0dc5-d90e-4caf-aefc-842d57529981.PNG)

![IMG_0054](https://user-images.githubusercontent.com/7014968/165397899-918b69e8-730c-4227-8061-461758a7d563.PNG)
