### ISSUE TITLE
TextDetector not working with InputImage.fromFile();

### ISSUE THREAD

**Issue by Mijawel** [bharat-biradar/Google-Ml-Kit-plugin#155]
When I use the flutter camera plugin and convert the image as explained in the docs, it detects text. However when I use image_picker to get an image from file, it is not detecting any text.

I have no real idea why InputImage.fromFile() isn't working but reading through other issues posted on here, I've tried a couple things as follows: (which haven't helped)

I have noticed that the InputImageData is null, however I can't extract the image PlaneData from the image File to pass that along (and it won't take null for those values). I tried passing PlaneData as null and I copied the image format from what it said for the CameraImage on the same phone (although not sure about that one). But then I get an exception that terminates the app after running textDetector.processImage(image);

Here are things I've tried to get an inputImage that works:
Attempt 1:
final inputImage = InputImage.fromFile(file);

Result: No text detected

Attempt 2: 
Future<InputImage> _processImageFile(XFile image) async {
    final imageInBytes = await image.readAsBytes();
    var decodedImage = decodeImage(imageInBytes.toList());
    var height = decodedImage?.height;
    var width = decodedImage?.width;
    final Size imageSize = Size(width!.toDouble(), height!.toDouble());
    var imageRotation = InputImageRotation.Rotation_0deg;
    if (width > height) imageRotation = InputImageRotation.Rotation_90deg;
    final inputImageData = InputImageData(size: imageSize, imageRotation: imageRotation, inputImageFormat: InputImageFormat.BGRA8888, planeData: null);
return InputImage.fromBytes(bytes: imageInBytes, inputImageData: inputImageData);
  }

Result: 
-[NSNull count]: unrecognized selector sent to instance 0x1ea855c00
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull count]: unrecognized selector sent to instance 0x1ea855c00'
*** First throw call stack:
(0x18710adc0 0x19bc627a8 0x18700e2d0 0x18710d918 0x18710fc10 0x10695de1c 0x10695dad8 0x1069601f8 0x1069600a8 0x10695c9dc 0x10d5b22d4 0x10d0fc4f0 0x10d47defc 0x10d3acf28 0x10d3b0c94 0x1870858c0 0x1870854bc 0x18708490c 0x18707e6c0 0x18707d9f4 0x19e74e734 0x189afb75c 0x189b00fcc 0x1029e9bcc 0x186d39cf8)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001b5460334 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1b5460334 <+8>:  b.lo   0x1b5460354               ; <+40>
    0x1b5460338 <+12>: pacibsp 
    0x1b546033c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1b5460340 <+20>: mov    x29, sp
Target 0: (Runner) stopped.

**Comment by fbernaly** [comment]
Fix is included in this PR: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/236

details: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/236/commits/26b1b6cfbedbf920956c2904139ef87baf298381

will be available in v0.2.0
