### ISSUE TITLE
Can't detect face in IOS

### ISSUE THREAD

**Issue by doanbh** [bharat-biradar/Google-Ml-Kit-plugin#157]
I run example with Android, everything is working properly. I try with Iphone, face detect with camera still working fine. 
But when I try with pick image from gallery then it doesn't work. It always returns like below:

> 2021-10-18 10:15:18.244083+0700 Runner[731:77148] [WARNING]The specified colorspace format is not supported. Falling back on Libyuv.
2021-10-18 10:15:18.436004+0700 Runner[731:77394] [discovery] errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled}
2021-10-18 10:15:18.559948+0700 Runner[731:76740] flutter: Found 0 faces

Please try again from gallery and help me.

**Comment by hardikvij195** [comment]
yea I am also facing the same issue, face is not getting detected on iOS

**Comment by fbernaly** [comment]
Fix is included in this PR: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/236

details: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/commit/26b1b6cfbedbf920956c2904139ef87baf298381

will be available in v0.2.0
