### ISSUE TITLE
ETA on iOS object detection?

### ISSUE THREAD

**Issue by petermoser** [bharat-biradar/Google-Ml-Kit-plugin#161]
We are eagerly awaiting the Object Detection and Tracking feature on iOS for the flutter ml-kit-plugin. Would you have some information if this feature is being worked on and maybe an estimated time when it will be available since we need to make a decision soon if we should use native ML Kit for iOS and Android instead of flutter. Thank you!

**Comment by bharat-biradar** [comment]
@petermoser Thank you for your patience. @fbernaly will let you know if it's possible to be implemented in due time.

**Comment by siddzankat** [comment]
Thanks @bharat-biradar for all the work you have done on this plugin. Is there an update on above request? I am also looking for iOS support for object detection and tracking api. Thanks!

**Comment by fabiosanto** [comment]
Hello @bharat-biradar, thanks again for your work on this plugin. Any update on the above request?
thank you

**Comment by fbernaly** [comment]
Try the latest version.

Also note that `google_ml_kit` has been split in multiples plugins, to avoid adding unnecessary dependencies to your project. You can start using `google_mlkit_object_detection` instead.

More details here:
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin
