### ISSUE TITLE
java.lang.IllegalArgumentException with PendingIntents on Android 12

### ISSUE THREAD

**Issue by MobiliteDev** [bharat-biradar/Google-Ml-Kit-plugin#163]
Google ml kit plugin makes the app crash on Android 12. 

**Step to reproduce :** 
- Create a new sample application 
VSCode : ctrl+shift+p -> Flutter: new project -> Application
- Change _compileSdkVersion_ to 31, _minSdkVersion_ to 23 and _targetSdkVersion_ to 31 in android/app/build.gradle
- Add _android:exported="true"_ on the _activity_ tag in android/app/src/main/AndroidManifest.xml
(this is a change that need to be done in order to be compatible with Android 12 : see [Safer component exporting](https://developer.android.com/about/versions/12/behavior-changes-12#exported) for more details)
- Try to run main.dart : it works as expected.
- Add _google_ml_kit: ^0.7.2_ to pubspec.yaml
- Try to run main.dart : it doesn't work anymore
The error is the following : 

```
E/AndroidRuntime(23081): FATAL EXCEPTION: pool-9-thread-1
E/AndroidRuntime(23081): Process: com.example.flutter_application_1, PID: 23081
E/AndroidRuntime(23081): java.lang.IllegalArgumentException: com.example.flutter_application_1: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime(23081): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/AndroidRuntime(23081): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
E/AndroidRuntime(23081): 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
E/AndroidRuntime(23081): 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
E/AndroidRuntime(23081): 	at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:174)
E/AndroidRuntime(23081): 	at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:108)
E/AndroidRuntime(23081): 	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:86)
E/AndroidRuntime(23081): 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
E/AndroidRuntime(23081): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(23081): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(23081): 	at java.lang.Thread.run(Thread.java:920)

```

In my opinion, it's linked to [this](https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability) change of Android 12 but I'm not sure about it. 

Thanks.

**Comment by bharat-biradar** [comment]
@MobiliteDev I think this error is because the [build.gradle](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/9621775908ab46a9efcb3836e4c9d4765d1921e9/android/build.gradle#L27) compile version is set to 30 in the plugin. Can you please try changing it to 31 and try again?

**Comment by MobiliteDev** [comment]
@bharat-biradar Yeah it's working with this change. It would be nice to have a new version of the plugin with this change to ensure Android 11 compatibility

**Comment by MobiliteDev** [comment]
@bharat-biradar It is working now. Thanks for your help.
