### ISSUE TITLE
IOS How load custom model in image labeler google_ml_kit: 0.7.2

### ISSUE THREAD

**Issue by ashtana** [bharat-biradar/Google-Ml-Kit-plugin#165]

**Comment by ashtana** [comment]
I figured out that, The path to the model that I use there, for example just model.tflite and the model should be placed in /android/app/src/main/assets/model.tflite

But I still do not understand what architecture the model should be and how it should be created for its own classes and dataset in order to successfully load it and not receive errors.

**Comment by ashtana** [comment]
I get when I try to load my model into the console:

I/Manager (25210): DeviceManager::DeviceManager
I/Manager (25210): findAvailableDevices
I/native  (25210): I1104 00:55:29.897558   27682 classifier_client_calculator.cc:139] Loading classifier efficientdet-lite0/v1
I/tflite  (25210): Initialized TensorFlow Lite runtime.
E/native  (25210): E1104 00:55:29.919796   27677 calculator_graph.cc:772] INVALID_ARGUMENT: CalculatorGraph::Run() failed in Run: 
E/native  (25210): Calculator::Open() for node "ClassifierClientCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1). [type.googleapis.com/mediapipe.StatusList='\n\xf8\x01\x08\x03\x12\xc6\x01\x43\x61lculator::Open() for node \"ClassifierClientCalculator\" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).\x1a+\n$tflite::support::TfLiteSupportStatus\x12\x03\x34\x30\x30']
E/native  (25210): E1104 00:55:29.920103   27677 pipeline_jni.cc:95] INVALID_ARGUMENT: CalculatorGraph::Run() failed in Run: 
E/native  (25210): Calculator::Open() for node "ClassifierClientCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1). [type.googleapis.com/mediapipe.StatusList='\n\xf8\x01\x08\x03\x12\xc6\x01\x43\x61lculator::Open() for node \"ClassifierClientCalculator\" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).\x1a+\n$tflite::support::TfLiteSupportStatus\x12\x03\x34\x30\x30']
E/native  (25210): E1104 00:55:29.923687   27677 pipeline_jni.cc:243] INVALID_ARGUMENT: Graph has errors: 
E/native  (25210): Calculator::Open() for node "ClassifierClientCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1). [type.googleapis.com/mediapipe.StatusList='\n\xf8\x01\x08\x03\x12\xc6\x01\x43\x61lculator::Open() for node \"ClassifierClientCalculator\" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).\x1a+\n$tflite::support::TfLiteSupportStatus\x12\x03\x34\x30\x30']
E/native  (25210): E1104 00:55:29.929809   27677 pipeline_jni.cc:243] INVALID_ARGUMENT: Graph has errors: 
E/native  (25210): Calculator::Open() for node "ClassifierClientCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1). [type.googleapis.com/mediapipe.StatusList='\n\xf8\x01\x08\x03\x12\xc6\x01\x43\x61lculator::Open() for node \"ClassifierClientCalculator\" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).\x1a+\n$tflite::support::TfLiteSupportStatus\x12\x03\x34\x30\x30']
E/MobileVisionBase(25210): Error preloading model resource
E/MobileVisionBase(25210): com.google.mlkit.common.MlKitException: Failed to initialize detector. Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).
E/MobileVisionBase(25210): 	at com.google.mlkit.vision.vkp.PipelineManager.start(com.google.mlkit:vision-internal-vkp@@18.1.1:66)
E/MobileVisionBase(25210): 	at com.google.mlkit.vision.label.custom.internal.zzh.zzf(Unknown Source:40)
E/MobileVisionBase(25210): 	at com.google.mlkit.vision.label.custom.internal.zzg.tryLoad(com.google.mlkit:image-labeling-custom@@16.3.1:2)
E/MobileVisionBase(25210): 	at com.google.mlkit.common.sdkinternal.model.CustomModelLoader.load(com.google.mlkit:common@@17.3.0:3)
E/MobileVisionBase(25210): 	at com.google.mlkit.vision.label.custom.internal.zzh.load(com.google.mlkit:image-labeling-custom@@16.3.1:2)
E/MobileVisionBase(25210): 	at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@17.3.0:4)
E/MobileVisionBase(25210): 	at com.google.mlkit.common.sdkinternal.zzm.run(Unknown Source:10)
E/MobileVisionBase(25210): 	at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@17.3.0:2)
E/MobileVisionBase(25210): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@17.3.0:4)
E/MobileVisionBase(25210): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@17.3.0:1)
E/MobileVisionBase(25210): 	at com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2)
E/MobileVisionBase(25210): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/MobileVisionBase(25210): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/MobileVisionBase(25210): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@17.3.0:2)
E/MobileVisionBase(25210): 	at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
E/MobileVisionBase(25210): 	at java.lang.Thread.run(Thread.java:923)
D/TransportRuntime.SQLiteEventStore(25210): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
I/native  (25210): I1104 00:55:29.950099   27684 classifier_client_calculator.cc:139] Loading classifier efficientdet-lite0/v1
D/TransportRuntime.JobInfoScheduler(25210): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
E/native  (25210): E1104 00:55:29.982095   27677 calculator_graph.cc:772] INVALID_ARGUMENT: CalculatorGraph::Run() failed in Run: 
E/native  (25210): Calculator::Open() for node "ClassifierClientCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1). [type.googleapis.com/mediapipe.StatusList='\n\xf8\x01\x08\x03\x12\xc6\x01\x43\x61lculator::Open() for node \"ClassifierClientCalculator\" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).\x1a+\n$tflite::support::TfLiteSupportStatus\x12\x03\x34\x30\x30']
E/native  (25210): E1104 00:55:29.982315   27677 pipeline_jni.cc:95] INVALID_ARGUMENT: CalculatorGraph::Run() failed in Run: 
E/native  (25210): Calculator::Open() for node "ClassifierClientCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1). [type.googleapis.com/mediapipe.StatusList='\n\xf8\x01\x08\x03\x12\xc6\x01\x43\x61lculator::Open() for node \"ClassifierClientCalculator\" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).\x1a+\n$tflite::support::TfLiteSupportStatus\x12\x03\x34\x30\x30']
E/native  (25210): E1104 00:55:29.983665   27677 pipeline_jni.cc:243] INVALID_ARGUMENT: Graph has errors: 
E/native  (25210): Calculator::Open() for node "ClassifierClientCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1). [type.googleapis.com/mediapipe.StatusList='\n\xf8\x01\x08\x03\x12\xc6\x01\x43\x61lculator::Open() for node \"ClassifierClientCalculator\" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).\x1a+\n$tflite::support::TfLiteSupportStatus\x12\x03\x34\x30\x30']
E/native  (25210): E1104 00:55:29.984370   27677 pipeline_jni.cc:243] INVALID_ARGUMENT: Graph has errors: 
E/native  (25210): Calculator::Open() for node "ClassifierClientCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1). [type.googleapis.com/mediapipe.StatusList='\n\xf8\x01\x08\x03\x12\xc6\x01\x43\x61lculator::Open() for node \"ClassifierClientCalculator\" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).\x1a+\n$tflite::support::TfLiteSupportStatus\x12\x03\x34\x30\x30']
D/TransportRuntime.SQLiteEventStore(25210): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(25210): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
E/flutter (25210): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(ImageLabelDetectorError, com.google.mlkit.common.MlKitException: Failed to initialize detector. Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1)., null, null)
E/flutter (25210): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (25210): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (25210): <asynchronous suspension>
E/flutter (25210): #2      ImageLabeler.processImage (package:google_ml_kit/src/vision/label_detector.dart:30:20)
E/flutter (25210): <asynchronous suspension>
E/flutter (25210): #3      _MyHomePageState.doImageLabeling (package:live_feed_demo/main.dart:74:37)
E/flutter (25210): <asynchronous suspension>

**Comment by ashtana** [comment]
I understand to join custom model in image labeler for android, but i don't know how do it for IOS. Please can you help me.

**Comment by fbernaly** [comment]
This issue was resolved in other conversation.

Look at this example: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/179#issuecomment-1077527570
