### ISSUE TITLE
how to use tflite model into model name while performing image labeling ?

### ISSUE THREAD

**Issue by flomingdev** [bharat-biradar/Google-Ml-Kit-plugin#167]
As i can see below example code where we need to put modelName also there is the comment line which indicates where the tflite model stores but there is no brief explanation that how we can use it ?
I kindly request if anyone have some idea then comment down below. 
Thank you.

 // Add the tflite model in android/src/main/assets
  Future<void> processImageWithRemoteModel(InputImage inputImage) async {
    final options = CustomRemoteLabelerOption(
        confidenceThreshold: 0.5, modelName: 'bird-classifier');
    imageLabeler = GoogleMlKit.vision.imageLabeler(options);
    processImage(inputImage);
  }

**Comment by fbernaly** [comment]
This issue duplicates https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/165.

Closing this issue and moving conversation to https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/165.
