### ISSUE TITLE
LiveStream in example app does not stop on app navigation

### ISSUE THREAD

**Issue by AlaaMarawi** [bharat-biradar/Google-Ml-Kit-plugin#170]
I am trying the example app for OCR but when navigation to another app by home or recent button on Android (without using back button ) it resumes  the live streaming
how to stop streaming in this situation ?

**Comment by paj-co** [comment]
When using LiveStream you must be using camera plugin. From their documentation:
~~~
As of version 0.5.0 of the camera plugin, lifecycle changes are no longer handled by the plugin.
...
Handling lifecycle changes can be done by overriding the didChangeAppLifecycleState method ...
~~~

https://pub.dev/packages/camera#handling-lifecycle-states

So, you should stop image stream and dispose camera controller on `AppLifecycleState.inactive` and start again on `AppLifecycleState.resumed`
