### ISSUE TITLE
barcode reader don't work in moto g 30

### ISSUE THREAD

**Issue by ranulfo** [bharat-biradar/Google-Ml-Kit-plugin#176]
Hi guys,

Barcode reader don't work in **motorola moto g 30.**

I alter resolution to "**Medium**", "**High**" and "**veryHigh**" but nothing happens.

Can someone help me ?
Thank's

**Comment by luandnguyen** [comment]
Having this problem as well. Scanning works on all other phones except for Moto G. The camera feed is working, but detecting the QR code inside it doesn't seem to work (no outputs and just stay on the camera feed).

**Comment by ranulfo** [comment]
I still have this problem, does anyone have any idea how to solve this?
thank's

**Comment by msarkrish** [comment]
Barcode not detected in Oneplus Nord N100(Android 11) also, @ranulfo @luandnguyen @bharat-biradar 
Anyone found solution for this problem?

**Comment by GeoGlass** [comment]
Moto G7 not reading barcode ITF type. But I guess it's a problem with Camera plugin. 
this package worked fine.  https://pub.dev/packages/qr_mobile_vision

**Comment by fbernaly** [comment]
Try the latest version.

Also note that `google_ml_kit` has been split in multiples plugins, to avoid adding unnecessary dependencies to your project. You can start using `google_mlkit_barcode_scanning` instead.

More details here:
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/documentation/packages/google_mlkit_barcode_scanning

**Comment by ranulfo** [comment]
> Try the latest version.
> 
> Also note that `google_ml_kit` has been split in multiples plugins, to avoid adding unnecessary dependencies to your project. You can start using `google_mlkit_barcode_scanning` instead.
> 
> More details here:
> 
> * https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
> * https://github.com/bharat-biradar/Google-Ml-Kit-plugin
> * https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/documentation/packages/google_mlkit_barcode_scanning



> Try the latest version.
> 
> Also note that `google_ml_kit` has been split in multiples plugins, to avoid adding unnecessary dependencies to your project. You can start using `google_mlkit_barcode_scanning` instead.
> 
> More details here:
> 
> * https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
> * https://github.com/bharat-biradar/Google-Ml-Kit-plugin
> * https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/documentation/packages/google_mlkit_barcode_scanning

Hi, the latest version didn't solve the problem
