### ISSUE TITLE
Future of google_ml_kit plugin

### ISSUE THREAD

**Issue by paj-co** [bharat-biradar/Google-Ml-Kit-plugin#177]
Firstly, I really appreciate work that you guys put in developing this plugin 👏.

However, it seems, that lately, you have been struggling to find time to reply to some issues and add corresponding solutions.
So, I just want to ask, if this lack of time is something temporary or it can last a little bit longer?

**Comment by paj-co** [comment]
@bharat-biradar Thank you for your reply. Good luck in your search for a new iOS contributor!

**Comment by LZZZZ** [comment]
I am willing to contribute with some money for anyone that can fix the current iOS problem, where it crashes or requires Firebase (issue #172 and others).

Would that be helpful, @bharat-biradar?

**Comment by fbernaly** [comment]
@LZZZZ: I am working on updating the iOS plugin. What is the specific issue you are facing?

I can take Venmo or PayPal.

**Comment by fbernaly** [comment]
Try the latest version.

Also note that `google_ml_kit` has been split in multiples plugins, to avoid adding unnecessary dependencies to your project.

More details here:
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin
