### ISSUE TITLE
İos build error

### ISSUE THREAD

**Issue by cansavrun** [bharat-biradar/Google-Ml-Kit-plugin#178]
I am gettings this error how can i solve it?

" error: could not build Objective-C module 'Firebase'"

**Comment by fbernaly** [comment]
Try the latest version.

Also note that `google_ml_kit` has been split in multiples plugins, to avoid adding unnecessary dependencies to your project.

More details here:
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin

You can find more details on why you those issues here:

- https://github.com/bharat-biradar/Google-Ml-Kit-plugin#ios
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/documentation#firebase-dependency-custom-models
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/documentation/packages/google_ml_kit/example#getting-started
