### ISSUE TITLE
Upgrade to iOS MlKit 2.5.0

### ISSUE THREAD

**Issue by eripe970** [bharat-biradar/Google-Ml-Kit-plugin#181]
Hey, 

If I understand correctly then the IOS part of the library is using GoogleMLKit 2.2.0. 2.5.0 seems to be available now, for example https://developers.google.com/ml-kit/vision/pose-detection/ios 

Would be nice to get the latest version since that seems to be working better for pose detections.

**Comment by bharat-biradar** [comment]
@eripe970 Thanks for opening the issue, after the current PR is merged I will open a PR with the suggested changes.

**Comment by eripe970** [comment]
Awesome! 🙌 I tried just to bump the version numbers but it didn't work so guess something more needs to be changed

**Comment by fbernaly** [comment]
Try the latest version.

Also note that `google_ml_kit` has been split in multiples plugins, to avoid adding unnecessary dependencies to your project.

More details here:
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin
