### ISSUE TITLE
print datamatrix string 

### ISSUE THREAD

**Issue by yuexunshi** [bharat-biradar/Google-Ml-Kit-plugin#182]
``` Expanded(
            child: BarcodeScannerView(
              onResult: (Barcode value) async {
                debugPrint(
                    '=======_ScanViewState.build:${value.value.rawValue}');
                setState(() {
                  text = value.value.rawValue!;
                });
              },
              cameras: CameraService.of.cameras,
            ),
          ),
          Text(
            text,
            style: TextStyle(
              fontSize: 14,
              fontWeight: FontWeight.bold,
              color: Colors.white,
            ),
          ),```


print is wrong :
`flutter: =======_ScanViewState.build:^]0108809460304701112105121726051110202104280056^]21121EC3<…>`

text is right:
010880946030470111210512172605111020210428005621121EC38645

what is "^]" and "<…>"?
how can i get a right string and post to service?

**Comment by yuexunshi** [comment]
[print](https://i.stack.imgur.com/IAZU6.png)
[text](https://i.stack.imgur.com/7PJ1A.jpg)

**Comment by fbernaly** [comment]
Try the latest version.

Also note that `google_ml_kit` has been split in multiples plugins, to avoid adding unnecessary dependencies to your project. You can start using `google_mlkit_barcode_scanning` instead.

More details here:
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/documentation/packages/google_mlkit_barcode_scanning
