### ISSUE TITLE
Why is there no headEulerAngleX available in Face detection?

### ISSUE THREAD

**Issue by MenaRaafat** [bharat-biradar/Google-Ml-Kit-plugin#183]
I implemented face detection using GoogleML-Kit on native android, where a detected face had a headEulerAngleX value.
In flutter, there seems to be no headEulerAngleX parameter available. Why?

**Comment by jdiazgon55** [comment]
It seems that they forgot to add it on the library, but I was able to get it. It's pretty easy, if I have time I will create a Pull Request.

Just find in every file of this package where headEulerAngleY is used, and add headEulerAngleX:

![Captura de pantalla 2022-02-09 a las 10 11 46](https://user-images.githubusercontent.com/28304354/153163572-1e07369f-7d63-4afd-b762-cf7fafe185e9.png)

**Comment by fbernaly** [comment]
Closing as resolved. That is included in the latest version: 

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_mlkit_face_detection/lib/src/face_detector.dart#L131-L159
