### ISSUE TITLE
How to get the text when tapped on text detector view while scanning

### ISSUE THREAD

**Issue by BharanidharanNichiIn** [bharat-biradar/Google-Ml-Kit-plugin#186]
Hi,
I have requirement like whenever the user tap on the ocr text while scanning in text detector view, i need to search that text may i know how to do that  call back method to get the value when tapped.

**Comment by BharanidharanNichiIn** [comment]
This requirement i achieved this with touchable plugin. So i'm closing this.

**Comment by j007ha** [comment]
@BharanidharanNichiIn appreciate if you could share the sample code like how you achieve this using touchable plugin?  I would like to implement the same feature. Thanks a lot in advance.
