### ISSUE TITLE
How to use without firebase service

### ISSUE THREAD

**Issue by girllee** [bharat-biradar/Google-Ml-Kit-plugin#189]
In the China's network environment, there is no firebase and google play, how to use it in this case?

**Comment by msarkrish** [comment]
This plugin support Barcode scanning, Image Labeling and much more, 
If you want to use Barcode scanning then no need to include firebase service. 
You cannot use google play service option while taking build, but you can use bundle option.
Example: you can check for barcode scan bundle option [here](https://developers.google.com/ml-kit/vision/barcode-scanning/android#before-you-begin)

**Comment by fbernaly** [comment]
Try the latest version.

Also note that `google_ml_kit` has been split in multiples plugins, to avoid adding unnecessary dependencies to your project. You can start using `google_mlkit_barcode_scanning` instead.

More details here:
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/documentation/packages/google_mlkit_barcode_scanning
