### ISSUE TITLE
Pass many strokes (List<Offset>) in digitalInkRecogniser

### ISSUE THREAD

**Issue by LeoRpc** [bharat-biradar/Google-Ml-Kit-plugin#190]
Hi,
First of all, thanks a lot to the people who are working to make this wonderful library available on Flutter!

On the android version of the library, the input object taken by the digitalInkRecogniser is an `Ink` element ([see documentation](https://developers.google.com/ml-kit/vision/digital-ink-recognition/android#build_an_ink_object)) which is basically a List of `Stroke`s.
On the flutter version, the digitalInkRecogniser takes a `List<Offset>` which would be the equivalent of a single `Stroke` element ([see documentation #3](https://pub.dev/documentation/google_ml_kit/latest/)).

I workaround this issue by concatenating the List<Offset>, but it leads to recognition issues. For example when the use writes "11", the ML kit recognize "M" because the bottom of the first "1" is likend to the top of the second "1", so indeed it almost draws an "M"...

So I think this issue is very problematic since it directly decrease the recognition capability :/

**Comment by fbernaly** [comment]
Fix is included in this PR: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/236

details: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/236/commits/b4b9fdf2b8feb5081461e60d4750640907ac51eb

will be available in v0.2.0
