### ISSUE TITLE
Not able to run iOS example

### ISSUE THREAD

**Issue by jdiazgon55** [bharat-biradar/Google-Ml-Kit-plugin#194]
### Problem description

Related to #169.

I would like to run the iOS example.

I have freshly cloned this project, and I am not able to execute `flutter run` on folder `examples/ios`. I am getting the following output:

```cmd
Unable to install
/Users/xxx/Documents/proyectos/teoxaneflutter/build/ios/iphonesimulat
or/Runner.app on 2BB49A93-2976-4200-822A-6FAD2DF63EE3. This is sometimes caused
by a malformed plist file:
ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=NSPOSIXErrorDomain,
code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for
CFBundleIdentifier.
  Command: xcrun simctl install 2BB49A93-2976-4200-822A-6FAD2DF63EE3
  /Users/quasardynamics/Documents/proyectos/teoxaneflutter/build/ios/iphonesimul
  ator/Runner.app
Error launching application on iPhone 13.
```
I have checked Info.plist file but the bundle identifier `$(PRODUCT_BUNDLE_IDENTIFIER)` seems correct.

### System configuration

macOS Monterey V. 12.2
XCode V. 13
Flutter 2.10.0
iPhone 13 emulator

**Comment by fbernaly** [comment]
Try the latest version.

Also note that `google_ml_kit` has been split in multiples plugins, to avoid adding unnecessary dependencies to your project.

More details here:
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin

You can find more details on why you those issues here:

- https://github.com/bharat-biradar/Google-Ml-Kit-plugin#ios
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/documentation#firebase-dependency-custom-models
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/documentation/packages/google_ml_kit/example#getting-started
