### ISSUE TITLE
Disable firebase metrics/logging

### ISSUE THREAD

**Issue by M123-dev** [bharat-biradar/Google-Ml-Kit-plugin#198]
When using the scanner we often see:

> D/TransportRuntime.CctTransportBackend(30833): Making request to: https://firebaselogging.googleapis.com/v0cc/log/batch?format=json_proto3
> I/TransportRuntime.CctTransportBackend(30833): Status Code: 200
> I/TransportRuntime.CctTransportBackend(30833): Content-Type: application/json; charset=UTF-8
> I/TransportRuntime.CctTransportBackend(30833): Content-Encoding: gzip
> D/TransportRuntime.JobInfoScheduler(30833): Scheduling upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) with jobId=-2059590218 in 899999ms(Backend next call timestamp 1644664297271). Attempt 1
> I/ViewRootImpl@f844e3e[MainActivity](30833): MSG_WINDOW_FOCUS_CHANGED 0 1
> I/ViewRootImpl@f844e3e[MainActivity](30833): MSG_WINDOW_FOCUS_CHANGED 1 1
> D/InputMethodManager(30833): startInputInner - Id : 0
> I/InputMethodManager(30833): startInputInner - mService.startInputOrWindowGainedFocus

Since privacy is a big point we need some kind of way to disable this logging for the end user, it would be great if there would be a way to do this

**Comment by fbernaly** [comment]
this is coming from the native Firebase library, look at this: https://firebase.google.com/docs/perf-mon/disable-sdk?platform=android

**Comment by rienkkk** [comment]
Is there a way to disable this in this package? Our maybe a direction to how to go about disabling this. I tried to search online, but only where able to find how to disable this on Android, not on IOS.
