### ISSUE TITLE
Example app stuck when opening the camera

### ISSUE THREAD

**Issue by ritox842** [bharat-biradar/Google-Ml-Kit-plugin#199]
Hey.

I'm a new user in Flutter and I'm trying to run the barcode example.
Im running the app in a real ios device (iPhone 12 pro) and as soon as I select the example from the list the application stuck and I see this in xcode:

<img width="829" alt="image" src="https://user-images.githubusercontent.com/7280441/153729384-133aa9c8-981c-45dc-a0ad-1e06212a7cda.png">

Seems like some kind of error with [eventChannel setStreamHandler:_imageStreamHandler]; but I don't see anything informative about it or how to handle it.

I didn't change anything in the code of the example, this is a fresh start.
Anyone have any idea why it's happening ?

**Comment by salmanrajz** [comment]
same here :(

**Comment by salmanrajz** [comment]
same here :(

**Comment by ritox842** [comment]
> same here :(

It's working for me now... I'm not sure what I did to make it work cause I tried many things but please try this and update here if it helps:

```
 flutter channel master
 flutter upgrade
```

**Comment by salmanrajz** [comment]
> > same here :(
> 
> It's working for me now... I'm not sure what I did to make it work cause I tried many things but please try this and update here if it helps:
> 
> ```
>  flutter channel master
>  flutter upgrade
> ```

Sure I'll try but currently, I'm using this package, quite good for now as I need, 

https://pub.dev/packages/camera_process

**Comment by fbernaly** [comment]
Try the latest version.

Also note that `google_ml_kit` has been split in multiples plugins, to avoid adding unnecessary dependencies to your project.

More details here:
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin

You can find more details on why you got those issues here:

- https://github.com/bharat-biradar/Google-Ml-Kit-plugin#ios
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/documentation#firebase-dependency-custom-models
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/documentation/packages/google_ml_kit/example#getting-started
