### ISSUE TITLE
live camera pose estimation

### ISSUE THREAD

**Issue by RCVZ** [bharat-biradar/Google-Ml-Kit-plugin#2]
out of curiosity when can we aspect live camera pose estimation?

**Comment by bharat-biradar** [comment]
Hi @RCVZ.
Thank you for showing interest and opening an issue.

 I am currently in the middle of my semester exams. I will work on it as soon as possible and update you.

**Comment by RCVZ** [comment]
Thank you @bharat-biradar.
Good luck with your exams!

**Comment by bharat-biradar** [comment]
Hi @RCVZ  I have written the code for live pose estimation and commented out the part because for some reason its's not producing any results. Please see the code in the new-apis branch, if I have any development in getting the results I will update you.
