### ISSUE TITLE
Conflicting with new firebase packages  "CocoaPods could not find compatible versions for pod "GoogleDataTransport"

### ISSUE THREAD

**Issue by usestrive** [bharat-biradar/Google-Ml-Kit-plugin#20]

**Comment by bharat-biradar** [comment]
@usestrive Can you please be more specific about the issue. Actually, this plugin doesn't support IOS yet may be the problem is being caused by that.

**Comment by fbernaly** [comment]
@usestrive:  I added iOS support for Face Detection in this PR: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/21. Once it is approved and merged, clone the the repo and give it a try. You only need to set your development team in the Xcode project to run the example app.
