### ISSUE TITLE
Google ML + Image_Picker

### ISSUE THREAD

**Issue by officialFlutterDeveloper** [bharat-biradar/Google-Ml-Kit-plugin#200]
hey there I am using image picker 0.8.4+1

and I am using ML to detect text I have a gallery option and camera option if I use picture from gallery it works I am able to detect but when I use camera option it does not detect anything why is that? camera uses Xfile 

I get this error what does it mean

[Camera] Failed to read exposureBiasesByMode dictionary: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL}
[Runner] findWriterForTypeAndAlternateType:119: unsupported file format 'public.heic'
[Runner] findWriterForTypeAndAlternateType:119: unsupported file format 'public.heic'

**Comment by palvajk** [comment]
I don't get this error, but I also have this issue. If I select a picture from gallery it works fine, detect the text, but if I use the camera and take the exactly same picture which i selected it didn't find anything.

**Comment by fbernaly** [comment]
Try the latest version.

Also note that `google_ml_kit` has been split in multiples plugins, to avoid adding unnecessary dependencies to your project.

More details here:
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin

**Comment by fbernaly** [comment]
Example app uses the camera, give it a try: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/documentation/packages/google_ml_kit/example
