### ISSUE TITLE
face detection not working on android 11+ devices

### ISSUE THREAD

**Issue by Ritsz123** [bharat-biradar/Google-Ml-Kit-plugin#201]
face detection is not working on android 11+ devices,
I test face detection on 4 android devices but it was not working on 2 of them (having android 11+) versions.

Devices used for testing :
Realme 1 : android 9 (working)
Redmi 6A: android 9 (working)
Realme Narzo 20A: android 11 (not working)
Redmi note 7 pro: android 11 (not working)

**Comment by jdiazgon55** [comment]
Is it happening on Android 10 aswell? At least in my phone it does not seem to work

**Comment by Ritsz123** [comment]
> Is it happening on Android 10 aswell? At least in my phone it does not seem to work

@jdiazgon55 not sure about android 10.

**Comment by jdiazgon55** [comment]
Confirmed it is not working on Android 10 and higher. I am going to try to fix this, wish me good luck :D

**Comment by ardiirfanto** [comment]
Hello, i have some trouble with face detection. 
In my case on Android 10+ for several device is work correctly. but on several devices is not working.
I set CameraController to ResolutionPreset.high , Low, Medium, VeryHigh still didnt work.

Please, Do you have a solution?
Thankyou

My Test Device Didnt Work:
Redmi 9T
Poco X3
And more..

**Comment by MlecznyU** [comment]
I face the same problem on one plus 8 pro Android 11

**Comment by Ritsz123** [comment]
> Okay, so finally I found a workaround. It seems that the camera resolution in Android 10 or higher needs to be set to `ResolutionPreset.high` instead of `ResolutionPreset.low`.
> 
> For instance, in the example app on [camera_view](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/example/lib/VisionDetectorViews/camera_view.dart) you should use in method `_startLiveFeed` the following:
> 
> ```dart
> final camera = cameras[_cameraIndex];
>     _controller = CameraController(
>       camera,
>       ResolutionPreset.high,
>       enableAudio: false,
>     );
> ```
> 
> It is detecting faces correctly with this change.

@jdiazgon55 I tried this but still it is not working for me

**Comment by ardiirfanto** [comment]
> Hello, i have some trouble with face detection. In my case on Android 10+ for several device is work correctly. but on several devices is not working. I set CameraController to ResolutionPreset.high , Low, Medium, VeryHigh still didnt work.
> 
> Please, Do you have a solution? Thankyou
> 
> My Test Device Didnt Work: Redmi 9T Poco X3 And more..

Hello, I'll try it and worked.

replace 
`final Size imageSize = Size(image.width.toDouble(), image.height.toDouble());`

with 
```
int width = image.planes[0].bytesPerRow; 
final Size imageSize = Size(width.toDouble(), image.height.toDouble());
```

I found the solution [here](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/94#issuecomment-898934212)

Thanks for attention.

**Comment by Ritsz123** [comment]
@ardiirfanto 
Thank you for the solution it works..

**Comment by Ritsz123** [comment]
Closing this thread as we found the solution https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/201#issuecomment-1077472040
