### ISSUE TITLE
Image capture from Face Detection screen in example

### ISSUE THREAD

**Issue by PandaTobi** [bharat-biradar/Google-Ml-Kit-plugin#202]
Does anyone know how to do this? I'm trying to snap an image as soon as it detects a face, but I'm not sure how to get an image file from an InputImage instance.

**Comment by jdiazgon55** [comment]
Use the example file `camera_view` from [here](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/example/lib/VisionDetectorViews/camera_view.dart) and take the picture using the `CameraController` provided:

```dart
  Future<XFile?> startTakePicture() async {
    final CameraController? cameraController = _controller;
    if (cameraController == null || !cameraController.value.isInitialized) {
      print('Error: select a camera first.');
      return null;
    }

    if (cameraController.value.isTakingPicture) {
      // A capture is already pending, do nothing.
      return null;
    }

    try {
      await cameraController.stopImageStream();
      final XFile file = await cameraController.takePicture();
      return file;
    } on CameraException catch (e) {
      logError(e.code, e.description);
      return null;
    }
  }
```

**Comment by fbernaly** [comment]
follow the suggestion by @jdiazgon55 .

`camera_view.dart` has been move here: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/documentation/packages/google_ml_kit/example/lib/vision_detector_views/camera_view.dart
