### ISSUE TITLE
How can I crop the cameraImage taken by CameraPreview

### ISSUE THREAD

**Issue by mhilalsh** [bharat-biradar/Google-Ml-Kit-plugin#204]
in the scanner and I needed to implement a square overlay to the Camera preview, I take the image stream from the Camera Preview and send it to an API, now after adding the square overlay I need to square crop the cameraImage taken from the Camera preview before sending it to the API.

I only have the cameraImage -which is **YUV** 420 format- taken how can I crop it programmatically?

**Comment by fbernaly** [comment]
Cropping an image is outside of the scope of this plugin.
