### ISSUE TITLE
Increasing apk size.

### ISSUE THREAD

**Issue by MushtaqAlvi** [bharat-biradar/Google-Ml-Kit-plugin#205]
I want to know that this plugin implements which model to use like as [this page](https://developers.google.com/ml-kit/vision/face-detection/android) mention there are two models . If you select the unbundled model your app will be smaller because it will download the trained ml model after installation of apk . otherwise, if you select bundled the model will become inside apk (apk size increased).
Including what would I have to do if I want to use bundled model or unbundled model of Google ML.

Do I have to add dependencies manually in build.gradle ? Then what flutter does ? 
How does flutter add dependencies itself which plugin depends on?

another question is that . I saw this plugin add dependencies all of Google ML
what if I dont code in app to use face detection will it download model for that also ? or will that compiles into app also ?
all dependencies in plugin  are :
dependencies {
    implementation 'com.google.android.gms:play-services-mlkit-barcode-scanning:16.2.1'

    implementation 'com.google.android.gms:play-services-mlkit-image-labeling:16.0.5'
    implementation 'com.google.mlkit:image-labeling-custom:16.3.1'
    implementation 'com.google.mlkit:image-labeling-automl:16.2.1'

    implementation 'com.google.mlkit:barcode-scanning:17.0.0'
    implementation 'com.google.mlkit:language-id:17.0.1'
    implementation 'com.google.mlkit:digital-ink-recognition:17.0.0'

    implementation 'com.google.mlkit:pose-detection:17.0.1-beta6'
    implementation 'com.google.mlkit:pose-detection-accurate:17.0.1-beta6'

    implementation 'com.google.mlkit:translate:16.1.2'
    implementation 'com.google.mlkit:entity-extraction:16.0.0-beta2'
    implementation 'com.google.mlkit:smart-reply:16.2.0'

    implementation 'com.google.mlkit:object-detection:16.2.7'
    implementation 'com.google.mlkit:object-detection-custom:16.3.3'
    implementation 'com.google.mlkit:linkfirebase:16.1.1'

    implementation 'com.google.android.gms:play-services-mlkit-face-detection:16.2.0'

    implementation 'com.google.mlkit:text-recognition:16.0.0-beta1'
    implementation 'com.google.mlkit:text-recognition-chinese:16.0.0-beta1'
    implementation 'com.google.mlkit:text-recognition-devanagari:16.0.0-beta1'
    implementation 'com.google.mlkit:text-recognition-japanese:16.0.0-beta1'
    implementation 'com.google.mlkit:text-recognition-korean:16.0.0-beta1'

}

**Comment by fbernaly** [comment]
Try the latest version.

Also note that `google_ml_kit` has been split in multiples plugins, to avoid adding unnecessary dependencies to your project.

More details here:
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin
