### ISSUE TITLE
Pose Detection does not return correct coordinates in IOS.

### ISSUE THREAD

**Issue by BilalKashif** [bharat-biradar/Google-Ml-Kit-plugin#210]
Pose detection is correctly working on android and when I use it in ios it gives wrong coordinates 

For example: The leftWrist gives the coordinates of rightWrist and rightWrist gives the coordinates of leftWrist

I changed left to right and right to left then it worked.

It seems that in ios it treats your left side as your right side.

Please check it and tell me that is it the fault in this package.

**Comment by fbernaly** [comment]
@BilalKashif : could you send a PR?

**Comment by jtmuller5** [comment]
I noticed that on iOS the landmarks returned by the model are not in any particular order. This made it look like the coordinates were wrong. To fix it, I just sorted the landmarks before handling them:

`landmarks.sort((a,b) => a.type.index.compareTo(b.type.index));`

**Comment by fbernaly** [comment]
That means we can close this issue.
@BilalKashif : Confirm that that works for you.

**Comment by jtmuller5** [comment]
I dug into this a little further and I think this issue should be reopened. In addition to the landmarks being out of order, the left and right landmarks are reversed on iOS (so your left knee is labeled as your right knee, your left ankle is labeled as your right ankle, and so on)

**Comment by fbernaly** [comment]
@jtmuller5 : only reopen if you are going to send a PR to fix the issue.
