### ISSUE TITLE
Are custom models supported for Pose Estimation ?

### ISSUE THREAD

**Issue by mhidalgo** [bharat-biradar/Google-Ml-Kit-plugin#212]
I don't see how to integrate custom models in the documentation.  I am trying to implement the model as seen here:

https://developers.google.com/ml-kit/vision/pose-detection/classifying-poses.

**Comment by baseplate77** [comment]
check this [tflite_flutter](https://pub.dev/packages/tflite_flutter_helper)  package

**Comment by fbernaly** [comment]
@mhidalgo: Google's ML Kit Pose Detection only offers an API to detect poses and return landmarks, with the landmarks returned by the API you can use that data as an input for another step using another package like the one @baseplate77  suggested, but that is outside the scope of this plugin.
