### ISSUE TITLE
Android- App auto close on imageStream

### ISSUE THREAD

**Issue by X-SLAYER** [bharat-biradar/Google-Ml-Kit-plugin#213]
whenever I use the app with  faceDetector in debug, profile, or release mode it works fine but when i build the app and start it the app automatically close after the camera stream starts

**Comment by X-SLAYER** [comment]
another note this crash happens only when I build the apk with `flutter build apk --split-per-abi` and install the **app-armeabi-v7a-release.apk** but with `flutter build apk --release` the app works fine is it normal?

**Comment by fbernaly** [comment]
@X-SLAYER: any update on this? did `flutter build apk --release` solve your issue?

**Comment by X-SLAYER** [comment]
yes `flutter build apk --release` solved the issue
