### ISSUE TITLE
does't open app on Android

### ISSUE THREAD

**Issue by naoaki-kaito** [bharat-biradar/Google-Ml-Kit-plugin#217]
## problem
App is crashed immediately after app opened.
iOS works fine.

## How to reproduce
 - create new project `$ flutter new xxxx`
 - add "import dependencies" in pubspec.yaml `google_ml_kit: ^0.7.3`
 - setting viewing [Usage](https://pub.dev/packages/google_ml_kit#usage)
 - `$ flutter build apk`
 - `$ flutter run` and crashed.

## Versions
 - google_ml_kit: 0.7.3
 - Flutter: 2.10.4
 - dart: 2.16.2
 - openjdk: 11.0.10
 - kotlin: 1.6.20

## Log
```
e: /Users/xxxx/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.20/f8629f336bad4001c89e9cffa5ef3d4b5d0f5e22/kotlin-stdlib-jdk7-1.6.20.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

e: /Users/xxxx/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.20/6cedc143badbb4f1c6b7f5a340b04edff1743208/kotlin-stdlib-1.6.20.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

e: /Users/xxxx/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.20/27b4562b6713d70f458c6d7ea39aadacb8e6a92b/kotlin-stdlib-common-1.6.20.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
```
It looks like I should downgrade kotlin version to 1.4.x. But crashed again leaving following message.

```
* What went wrong:
Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > java.lang.OutOfMemoryError (no error message)
```
I'm using pixel6 and emulator(pixel4) has 20GB memories, so I should have plenty of memory.

## Temporally solution
adding WorkManager in `android/app/build.gradle`
```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.work:work-runtime-ktx:2.7.1' <-- add this line
}
```

Do you have any idea I should do?

Thank you

**Comment by fbernaly** [comment]
Could you try the latest version: `0.8.0`.

Also be aware that in our latest release we split the plugin in multiples plugins, and now `google_ml_kit` is an umbrella plugin. More details in our readme: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit

**Comment by naoaki-kaito** [comment]
@fbernaly it works thank you.
