### ISSUE TITLE
Can I use image labeling instead of object detection and tracking to view similar products as the capture one ?

### ISSUE THREAD

**Issue by hassanyassiin** [bharat-biradar/Google-Ml-Kit-plugin#218]
Hello, I'm building a flutter app that the user can capture a product (clothes, shoes, watches, etc...) and my app should view the similar products, I see that the object detection is still not yet implemented for iOS, so can I use image labeling for that issue, and if yes can anyone give me a hint what should I do, I'm learning now TensorFlow in Order to make my own custom model...

This is example for what I need : https://developers.google.com/ml-kit/case-studies/adidas

Hope can anyone help me with that,

**Comment by fbernaly** [comment]
@hassanyassiin : we released `0.8.0` yesterday and all the APIs are supported for both iOS and Android, except for selfie segmentation.

Also, be aware that `google_ml_kit` is an umbrella plugin that will include all the functionality for all the ML Kit APIs, and therefore will include more functionality that you intend to use. If your intentions is to only use object detection try `google_mlkit_object_detection`. Go to our readme for more details: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
