### ISSUE TITLE
Realme 7i, Android 11 face detector not working even  sample app

### ISSUE THREAD

**Issue by ChanakaWeerasinghe** [bharat-biradar/Google-Ml-Kit-plugin#222]
Realme 7i, Android 11 Face detection is not working could you please help to resolve the issue.

**Comment by fbernaly** [comment]
@ChanakaWeerasinghe: we do not have all the devices to test using all the available Android OS variants and manufacturer, and we cannot use the emulator in all the cases. Please provide more detail of your issue so maybe another developer with the same hardware can step in and help. Also, we released `0.8.0` yesterday, please give it a try.
