### ISSUE TITLE
The method 'getLandmark' isn't defined for the type 'Face'

### ISSUE THREAD

**Issue by X-SLAYER** [bharat-biradar/Google-Ml-Kit-plugin#225]
after upgrading the `google_ml_kit` to the newest version `0.8.0` when I wanted to use the getLandmark like it mentionned here [google_mlkit_face_detection](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_face_detection) it didn't work
```dart
final FaceLandmark leftEar = face.getLandmark(FaceLandmarkType.leftEar);
```
but I handle it like that.
So i don't know if it should be updated in the code or the document should mention it like the way i did

```dart
    final FaceLandmark leftEar = face.landmarks[FaceLandmarkType.leftEar]!;
```

**Comment by fbernaly** [comment]
Thanks @X-SLAYER that is the correct way to access the landmarks. We will update the readme, I forgot to update that. Also, you are welcome to send a PR and update the readme.
