### ISSUE TITLE
TextDetectorV2  Not Working on ios

### ISSUE THREAD

**Issue by mahmoud-atef-eden** [bharat-biradar/Google-Ml-Kit-plugin#226]
TextDetectorV2  Not Working on ios
Unhandled Exception: MissingPluginException(No implementation found for method vision#startTextDetectorV2 on channel google_ml_kit)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)

When I change TextDetectorV2  with TextDetector camera opened and start to detect but stopped after a while you can see the attached image.
Using the latest version .
![photo5981314745564772980](https://user-images.githubusercontent.com/94847589/164454449-d812d26d-b418-4439-a35f-30aa7b91e116.jpg)

**Comment by fbernaly** [comment]
@mahmoud-atef-eden: what plugin version are you using? we released `0.8.0` yesterday and we do not have such method `vision#startTextDetectorV2` in the latest one. Also, make sure you are passing the correct recognition script when creating the an instance of `TextRecognizer`: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_mlkit_text_recognition/lib/src/text_recognizer.dart#L33-L39
