### ISSUE TITLE
PlatformException : com.google.mlkit.common.MlKitException: This detector is already closed!

### ISSUE THREAD

**Issue by arazinger** [bharat-biradar/Google-Ml-Kit-plugin#230]
Hi,
I'm using *google_mlkit_text_recognition* plugin in the following way, but there seems to be an issue after TextRecognizer is closed:

```
// Create first TextRecognizer and process image
final textRecognizer = TextRecognizer();
textRecognizer.processImage(...);
textRecognizer.close();

...

// Create another TextRecognizer and process image
final textRecognizer = TextRecognizer();
textRecognizer.processImage(...);

--> PlatformException exception is thrown here:
PlatformException(TextRecognizerError, com.google.mlkit.common.MlKitException: This detector is already closed!, null, null)
```

I would expect that new TextRecognizer instances could still be created and used?

**Comment by fbernaly** [comment]
@arazinger : thanks for finding that bug, we will fix it in the next release.

**Comment by fbernaly** [comment]
This is fixed in this PR:  https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/229

And released in version [0.2.0](https://pub.dev/packages/google_mlkit_text_recognition/versions/0.0.2)

Details:
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/229/commits/cf28dd5233eeb35219f92fdd7b611f6b2d85951e#diff-5d7206290bb61a20123c996baf3eaf530bca7435976397cca10399adbd39c998
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/229/commits/e52ffc165d907dada083a309e154eb99666fd2a3

**Comment by Holofox** [comment]
@fbernaly,

see also:

```
PlatformException(ObjectDetectionError, com.google.mlkit.common.MlKitException: This detector is already closed!, null, null)]
```

```
PlatformException(ImageLabelDetectorError, com.google.mlkit.common.MlKitException: This detector is already closed!, null, null)]
```

**Comment by fbernaly** [comment]
Thanks @Holofox: I noticed that as well, and it will be included in PR: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/229 as well

**Comment by fbernaly** [comment]
[google_mlkit_image_labeling](https://pub.dev/packages/google_mlkit_image_labeling) was update in https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/229/commits/3085835e210e677460176e764ad162edccb416cf as part of https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/229

**Comment by fbernaly** [comment]
[google_mlkit_object_detection](https://pub.dev/packages/google_mlkit_object_detection) was update in https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/229/commits/aaf8130e5b3b14f310f1cd40cf3672a00e6f792b as part of https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/229
