### ISSUE TITLE
Hey first of all i want to say thanks to you for making such cool plugins . but i have issue in digital ink recongnition i give the error the firebase not configure please solve this issue if any one find the solution

### ISSUE THREAD

**Issue by Ashfaque-231219** [bharat-biradar/Google-Ml-Kit-plugin#232]

**Comment by fbernaly** [comment]
@Ashfaque-231219 : update title and description of this issue and provide more details.

**Comment by fbernaly** [comment]
if you are using `google_ml_kit` then you need to read our readme:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit

and start using: `google_mlkit_digital_ink_recognition`

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_digital_ink_recognition



Confirm if that solves your issue
