### ISSUE TITLE
google_mlkit_translation missed two languages download.

### ISSUE THREAD

**Issue by hsangtini** [bharat-biradar/Google-Ml-Kit-plugin#238]
https://developers.google.com/ml-kit/language/translation/android#java

Please check document.

Create a [Translator](https://developers.google.com/android/reference/com/google/mlkit/nl/translate/Translator) object, configuring it with the source and target languages:
```
// Create an English-German translator:
TranslatorOptions options =
    new TranslatorOptions.Builder()
        .setSourceLanguage(TranslateLanguage.ENGLISH)
        .setTargetLanguage(TranslateLanguage.GERMAN)
        .build();
final Translator englishGermanTranslator =
    Translation.getClient(options);
```

Make sure the required translation model has been downloaded to the device. Don't call translate() until you know the model is available.
```
DownloadConditions conditions = new DownloadConditions.Builder()
    .requireWifi()
    .build();
englishGermanTranslator.downloadModelIfNeeded(conditions)
    .addOnSuccessListener(
        new OnSuccessListener() {
          @Override
          public void onSuccess(Void v) {
            // Model downloaded successfully. Okay to start translating.
            // (Set a flag, unhide the translation UI, etc.)
          }
        })
    .addOnFailureListener(
        new OnFailureListener() {
          @Override
          public void onFailure(@NonNull Exception e) {
            // Model couldn’t be downloaded or other internal error.
            // ...
          }
        });
```

Single model download always fail.

**Comment by fbernaly** [comment]
@hsangtini: thanks for pointing out to the java documentation. Our plugin uses both the java and the obj-c APIs depending on the platform you are running in Flutter.

did you look at our documentation? 

In our documentation we added a class to make sure you download the model before you call `translateText()`, look at this: 

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_translation#managing-remote-models

in our example app you will find how to use both `OnDeviceTranslatorModelManager` and `OnDeviceTranslator`:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_ml_kit/example/lib/nlp_detector_views/language_translator_view.dart#L97-L135

I hope that resolves your issue.

**Comment by fbernaly** [comment]
BTW: I just check in our java code and we are downloading the model if needed:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_mlkit_translation/android/src/main/java/com/google_mlkit_translation/TextTranslator.java#L55

same for ios:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_mlkit_translation/ios/Classes/GoogleMlKitTranslationPlugin.m#L48

**Comment by hsangtini** [comment]
@fbernaly Thank you for quick reply. I just want to talking about pre-download a combo, like englishGermanTranslator. 
BTW i can solved pre-download by send first translate and catch the result success or fail.

Regards,

**Comment by fbernaly** [comment]
I noticed the current readme in master has some errors, I updated the readme with more details here: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/239/commits/8933c591eea49678c31a39e99bae5ecfc0763608

You can used `OnDeviceTranslatorModelManager` to pre-download the languages you need before translating.

Look at the updated read how you can use `OnDeviceTranslatorModelManager` and look at the example as well.
