### ISSUE TITLE
minSdkVersion & typo

### ISSUE THREAD

**Issue by lks-nbg** [bharat-biradar/Google-Ml-Kit-plugin#24]
Since firebase_ml_vision is discontinued, I am migrating to your plugin. Thereby I realized that google_ml_kit currently requires minSdkVersion >= 26, while firebase_ml_vision supported Version 16 onwards. Therefore I am wondering, if minSdkVersion 26 is really necessary or if it can be lowered, to increase compatibility. If this is not possible, I suggest adding a hint in the readme file.

Furthermore during testing I found a typo in the Language Detection Code: identifyLangua**n**ge

**Comment by fbernaly** [comment]
what minSdkVersion do you recommend?

**Comment by bharat-biradar** [comment]
I think 21 is possible.

**Comment by fbernaly** [comment]
Ok, will send a PR

**Comment by lks-nbg** [comment]
Thanks for your quick response! I tested the example app with minSdkVersion 21 and it seems to work as expected. A lower version was not possible, since the example app depends on the camera plugin, which requires minSdkVersion >= 21. But at least for my purposes supporting Android 5.0 and higher is more than enough.

**Comment by fbernaly** [comment]
Let's close this issue after this PR is merged: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/25
