### ISSUE TITLE
Question about Digital Ink Recognition

### ISSUE THREAD

**Issue by Knaackee** [bharat-biradar/Google-Ml-Kit-plugin#244]
I tried the Digital Ink Recognition Plugin and have a question. I am uncertain if this is the right place to ask.

Drawing a word or sentence works great, but what if I want to insert a word before.
e.g., I draw “World” and then I draw “Hello” before. 
I expected the result would be “Hello World” but instead it is “World Hello”.

Does anybody know how to achieve the behavior I expected?

Thanks a lot for this repo!

**Comment by fbernaly** [comment]
I thought it was because the stroke takes a timestamp:

https://developers.google.com/ml-kit/vision/digital-ink-recognition/ios#build_an_ink_object

But I also hardcoded the example app and removed the timestamp, and it is still returning World Hello. I think the native API is taking the ink sequentially for processing: it process stroke 1, and then 2... and so on. Maybe you need to have some logic in your app to sort the strokes from the top left corner to the bottom right corner... but honestly that sounds complex.

What I would do is to run the google native sample app and make sure if their same app can do what you expect, if you get the same world hello, then most likely it will be their API not supporting what you want.

Here you have the links to their sample apps:
-[iOS](https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/digitalinkrecognition)
- [Android](https://github.com/googlesamples/mlkit/tree/master/android/digitalink)


If you are able to get Hello World, then come back and we will take a look at the plugin or how the `Ink` object is saved.

**Comment by Knaackee** [comment]
Thanks for your quick reply!

I tested the sample on my android tablet. 

The sample recognizes the text and does an overlay (see images).
So, the recognizer returns not only the text, but also the boundaries of the strokes.

This is precisely what I want. Can we make this happen?

Thanks again!

## Drawing 
![Screenshot_20220503-234146_ML Kit Digital Ink Recognition Demo](https://user-images.githubusercontent.com/880759/166571447-ad8624d2-4e3e-4b33-a495-bcb537ff5407.jpg)
## Recognize
![Screenshot_20220503-234203_ML Kit Digital Ink Recognition Demo](https://user-images.githubusercontent.com/880759/166571439-dae24793-9cd8-4537-8315-a9d68cae74a0.jpg)
## Drawing 
![Screenshot_20220503-234215_ML Kit Digital Ink Recognition Demo](https://user-images.githubusercontent.com/880759/166571442-8876a879-32fe-4971-ac58-2ed4e0ce4d84.jpg)
## Recognize
![Screenshot_20220503-234225_ML Kit Digital Ink Recognition Demo](https://user-images.githubusercontent.com/880759/166571445-7613a73b-a87d-4da6-9906-4692ec59c966.jpg)

**Comment by fbernaly** [comment]
@Knaackee : I played with the native app, and the app is processing the `Ink` the same way this plugin is doing.

To be more specific this plugin is just grabbing the `Ink` you are passing in the method, wrapping in a json, passing using FlutterMethodChannel to the native later and in the native layer we decode that json back to an `Ink` object and pass it to the MLKit API. When the response is received, it is encoded in a json, passed back to Flutter using the calling FlutterMethodChannel and decoding that json back to a `RecognitionCandidate` with the same properties as their native counterpart.
- android: https://developers.google.com/android/reference/com/google/mlkit/vision/digitalink/RecognitionCandidate
- ios: https://developers.google.com/ml-kit/reference/swift/mlkitdigitalinkrecognition/api/reference/Classes/DigitalInkRecognitionCandidate

This plugin does not provide a widget for you you handle and manage how to capture the `Ink`. We have a simple demo in our sample app that you can use to expand and fit it to your needs. And that is what their sample app is doing: they are handling the `Ink` in a different way that our sample app. Not that our sample app is wrong, but different. Let me explain you how.

I tried their sample app and follow the same steps you shared: 
> draw 'world'
> draw 'hello' before
> tap 'recognize`
And the result is the same we get in our: world hello

I have attached this screenshoot:
![Screen Shot 2022-05-03 at 4 17 37 PM](https://user-images.githubusercontent.com/7014968/166588193-c176b20f-da50-4943-8b0c-7c6e934c8144.png)


However, here is where it is different:
1. draw 'world'
2. tap 'recognize`
 result: the word world is recognized and draw on top
3. draw 'hello'
4. tap 'recognize`
 result: the word hello is recognized and draw on top

between step 2 and 3, they clear the ink they are passing, I meant they are passing two different Inks, or processing the strokes separately. I stroke for the world and one stroke for hello.

You can achieve the same in with our plugin, but you need to handle when to create a new instance of `Ink`. Maybe when the touches ends.

Also, drawing the recognized world on top is extra processing that they are doing in their example, and it can be done by you using our plugin as well. This is how I think they are doing it: `RecognitionCandidate` does not return a bounding rect, but you already have it with the points coordinates: you can get max x, min x, max y, min y and you will have it, with that you can draw the text on top of it.

I hope this helps.

**Comment by Knaackee** [comment]
Thank you very much!

This was very helpful.

**Comment by fbernaly** [comment]
Ok, closing issue.

**Comment by fbernaly** [comment]
@Knaackee: if our plugin is helpful do not forget to thumbs up our plugin in pub.dev or give it a star here.

**Comment by fbernaly** [comment]
@Knaackee: Their documentation also supports the output you are getting when writing world and then hello. 

>  The recognizers expect strokes to occur in the order people would naturally write; for example left-to-right for English. Any case that departs from this pattern, such as writing an English sentence starting with the last word, gives less accurate results.
> 
> Another example is when a word in the middle of an Ink is removed and replaced with another word. The revision is probably in the middle of a sentence, but the strokes for the revision are at the end of the stroke sequence. In this case we recommend sending the newly written word separately to the API and merging the result with the prior recognitions using your own logic.


https://developers.google.cn/ml-kit/vision/digital-ink-recognition/ios#stroke-ordering.

**Comment by Knaackee** [comment]
Yes i already read and tried ist (Stroke ordering) .

Works good.
