### ISSUE TITLE
Setting writingArea for Digital Ink Recognition

### ISSUE THREAD

**Issue by Knaackee** [bharat-biradar/Google-Ml-Kit-plugin#246]
Is it possible to set the `writingArea `for the recognizer like described [here](https://developers.google.cn/ml-kit/vision/digital-ink-recognition/ios) ?

I didn't find anything. 

Thanks!

**Comment by fbernaly** [comment]
We have not included that yet, we can include it in our next release or feel free to send a PR with your contribution.

**Comment by Knaackee** [comment]
I could do it for android, but not for iOS. (at least not using objective-c)

**Comment by fbernaly** [comment]
PR should contain both for us to release it

**Comment by Knaackee** [comment]
Of course. 

Since It's only about adding one argument, I hope that I will find someone to help.

If someone with decent objective-c experience reads this and would like to help. 
Please comment here.

I would even pay for that feature.

**Comment by fbernaly** [comment]
ok, you can pay me!!!

this is the PR: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/247 it includes both iOS and Android and updated the README with new details.

**Comment by Knaackee** [comment]
Oh wow. This is nice. 

Bit you started before we talked about the price 😉

What, you think, ist a fair price?

**Comment by Knaackee** [comment]
Thanks a lot! What about a compensation?

**Comment by fbernaly** [comment]
What is you email ?and we can discuss details

**Comment by Knaackee** [comment]
dknaack@gmail.com
