### ISSUE TITLE
How can I add gestures to recognized text?

### ISSUE THREAD

**Issue by iremiko** [bharat-biradar/Google-Ml-Kit-plugin#252]
Hi,
I want to select text from recognized texts, how can I do that?

**Comment by fbernaly** [comment]
@iremiko : could you provide more details? I dont get what you want to do

**Comment by iremiko** [comment]
When I click on one of the articles read, how can I add a gesture to close the page and return the article I clicked to the previous page?
![img1](https://user-images.githubusercontent.com/47665203/167881890-4e45696c-bf17-4ec0-a3f0-83ec548341de.png)
![img2](https://user-images.githubusercontent.com/47665203/167881915-e8704952-76b4-457e-bfa4-b243029c59d5.png)
![img3](https://user-images.githubusercontent.com/47665203/167881931-7ee1d1a5-5c7b-489e-9445-77fb0f408e86.jpg)

For example I have two sentences, "HI" and "HELLO WORLD", the tool recognize these. I want to click "HELLO WORLD" and close page, return "HELLO WORLD".

**Comment by fbernaly** [comment]
@iremiko: that is outside the scope of this plugin, that is more like a general Flutter question. So far this plugin is working for you and returning the recognized text. That is all this plugin will do. This plugin does not provide any widget for you to handle the response, that is up to the consumer/developer.

To learn more about Taps, drags, and other gestures: https://docs.flutter.dev/development/ui/advanced/gestures
