### ISSUE TITLE
Pose Detection on Images

### ISSUE THREAD

**Issue by Ellymayr** [bharat-biradar/Google-Ml-Kit-plugin#254]
Hi there I have the issue that the pose detection do not draw the lines and points of an image from the gallery. would be awesome if somebody can help me out.

**Comment by fbernaly** [comment]
@Ellymayr: do you mean in the example app? 

This plugin only returns the detected landmarks. This plugin does not provide a widget for you to draw the landmarks on top of you image. That is outside the scope of this plugin.

You can look at our example app for some guidance, however we know that the example app is not complete, it is not production code and it is intended to demonstrate some of the functionality. That being said you can look at our example app: in the case of using the camera feed we are drawing the lines on top of the images using our [PosePainter](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_ml_kit/example/lib/vision_detector_views/painters/pose_painter.dart):

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_ml_kit/example/lib/vision_detector_views/pose_detector_view.dart#L50-L52

In the case of image gallery we are just printing in the console:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_ml_kit/example/lib/vision_detector_views/pose_detector_view.dart#L54-L56

In both cases the pose detection is working, but you will need to create your own `CustomPainter` to satisfy your use case. Maybe all you need to do is tweak our `PosePainter` to scale properly. Feel free to tweak our painters in the example app and send back your PR with your contribution.

**Comment by fbernaly** [comment]
No, that wont work, actually force unwrapping `inputImage.inputImageData!` will crash your app because you  are reading the image from a file, when you read the image from a file `inputImageData` is null. Unless you find a way to pass the inputImageData then it will work.

**Comment by Ellymayr** [comment]
alright thank you! sadly i can not find a solution to draw the landmarks over my image. Maybe somebody solved that already or have an input for me for creating the _customPaint

**Comment by Ellymayr** [comment]
is there a guidance page where I can read how to solve my problem? or an example with an similar task? 
many thanks in advance!!

**Comment by fbernaly** [comment]
@Ellymayr : we have plenty of documentation in our readmes on how to use our API to get the landmarks or our detection particular to the API you are using. We also have plenty of links in our readmes that point to more documentation by Google on specifics of their APIs.

However what you want to do is outside the scope of this plugin. This plugin will only help you you detect the landmark on a given InputImage. It will NOT draw the landmark on top of the image. That is up to the developer to process the response (landmarks) properly and according to your app needs. 

I am sorry that we can not help you any more. I have shared with you in previous comments how we are doing that for the camera feed. You can use that as a reference to build what you need on top. You can google how to use CustomPainter. I am sure you will find plenty of tutorials, that is how we learn.

I hope this helps, and good luck.

**Comment by fbernaly** [comment]
Here you have some tutorials: 
- https://api.flutter.dev/flutter/widgets/CustomPaint-class.html
- https://api.flutter.dev/flutter/rendering/CustomPainter-class.html
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_ml_kit/example/lib/vision_detector_views/painters/pose_painter.dart
- https://medium.com/flutter-community/a-deep-dive-into-custompaint-in-flutter-47ab44e3f216
- https://petercoding.com/flutter/2022/02/09/using-custom-paint-in-flutter/
- https://pub.dev/packages/image_painter
- https://www.youtube.com/watch?v=jaoJz3q9PmE
- https://localcoder.org/flutter-how-to-draw-an-image-on-canvas-using-drawimage-method

Good luck
