### ISSUE TITLE
Entity extraction crashing/not working

### ISSUE THREAD

**Issue by dimitchik** [bharat-biradar/Google-Ml-Kit-plugin#258]
Calling `annotateText()` throws the following exception: 
`NoSuchMethodError (NoSuchMethodError: The method 'toInt' was called on null.
Receiver: null
Tried calling: toInt())`
Tried following inputs:
- `google.com`
- `www.google.com`
- `https://google.com`

Judging by the call stack, the exception occurs because the string is mistakingly recognised as `EntityType.trackingNumber` instead of `EntityType.url`

If I try calling `annotateText()` with `entityTypesFilter: [EntityType.url]`, no entities are detected at all (with the same inputs)

**Comment by dimitchik** [comment]
> @dimitchik: could you send a PR with the fix? And steps to reproduce, please 

I don't have a fix, only discovered this a couple hours ago

You can reproduce this by running the example app, choosing entity extraction, and typing in any string that contains a url

**Comment by fbernaly** [comment]
@dimitchik : fix is included in this PR: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/259, and released in [v0.4.0](https://pub.dev/packages/google_mlkit_entity_extraction)
