### ISSUE TITLE
Increased App Size

### ISSUE THREAD

**Issue by lks-nbg** [bharat-biradar/Google-Ml-Kit-plugin#26]
After implementing google_ml_kit, the app size is increased by ~85 MB in debug mode and ~44 MB in release mode. I investigated this with the app size tool and found that all models/resources are always included, even if they are not used. So it would be great to be able to configure which resources are used and and which can be excluded.

The firebase_ml_vision plugin had the same issue (https://github.com/FirebaseExtended/flutterfire/issues/4767) and I was able to adapt the workaround of excluding unused resources to google_ml_kit and wanted to share it. In my case I am currently only using the language detection feature therefore I don't need pose detection, etc. 

The workaround for Android looks like that and increases the app size by less than 3 MB:

```
android {

    // some other code 

    buildTypes {
        release {
            // some other code 

            aaptOptions {
                ignoreAssetsPattern '!mlkit_pose:!mlkit_label_default_model:'
            }
        }
        debug {
            // some other code 

            aaptOptions {
                ignoreAssetsPattern '!mlkit_pose:!mlkit_label_default_model:'
            }
        }
    }

    packagingOptions {
        exclude 'lib/**/libtranslate_jni.so'
        exclude 'lib/**/libdigitalink.so'
        exclude 'lib/**/libxeno_native.so'
        exclude 'lib/**/libmlkitcommonpipeline.so'
        exclude 'lib/**/libbarhopper_v2.so'
        exclude 'lib/**/libclassifier_jni.so'
        exclude 'lib/**/libface_detector_v2_jni.so'
        exclude 'lib/**/libtensorflowlite_jni.so'
        // exclude 'lib/**/liblanguage_id_jni.so' → required for language detection
    }
```
Since a workaround does exist, this is not a pressing issue, but I think many developers would appreciate some sort of configuration option :)

**Comment by bharat-biradar** [comment]
@lks-nbg Thanks for pointing it out. I'll this in the docs.

**Comment by adriancsbna** [comment]
Hi @lks-nbg 
Which one should I comment to use image label?

**Comment by bharat-biradar** [comment]
@adriancsbna libclassifier_jni

**Comment by adriancsbna** [comment]
Hello @bharat-biradar.

I have applied it but the size of the App has not decreased.
What should I add in ignoreAssetsPattern?

**Comment by MalayAgrawal** [comment]
> After implementing google_ml_kit, the app size is increased by ~85 MB in debug mode and ~44 MB in release mode. I investigated this with the app size tool and found that all models/resources are always included, even if they are not used. So it would be great to be able to configure which resources are used and which can be excluded.
> 
> The firebase_ml_vision plugin had the same issue ([FirebaseExtended/flutterfire#4767](https://github.com/FirebaseExtended/flutterfire/issues/4767)) and I was able to adapt the workaround of excluding unused resources to google_ml_kit and wanted to share it. In my case I am currently only using the language detection feature therefore I don't need pose detection, etc.
> 
> The workaround for Android looks like that and increases the app size by less than 3 MB:
> 
> ```
> android {
> 
>     // some other code 
> 
>     buildTypes {
>         release {
>             // some other code 
> 
>             aaptOptions {
>                 ignoreAssetsPattern '!mlkit_pose:!mlkit_label_default_model:'
>             }
>         }
>         debug {
>             // some other code 
> 
>             aaptOptions {
>                 ignoreAssetsPattern '!mlkit_pose:!mlkit_label_default_model:'
>             }
>         }
>     }
> 
>     packagingOptions {
>         exclude 'lib/**/libtranslate_jni.so'
>         exclude 'lib/**/libdigitalink.so'
>         exclude 'lib/**/libxeno_native.so'
>         exclude 'lib/**/libmlkitcommonpipeline.so'
>         exclude 'lib/**/libbarhopper_v2.so'
>         exclude 'lib/**/libclassifier_jni.so'
>         exclude 'lib/**/libface_detector_v2_jni.so'
>         exclude 'lib/**/libtensorflowlite_jni.so'
>         // exclude 'lib/**/liblanguage_id_jni.so' → required for language detection
>     }
> ```
> 
> Since a workaround does exist, this is not a pressing issue, but I think many developers would appreciate some sort of configuration option :)

Yep, this did work it reduced my app-release.apk size from 323MB to 86MB but can I reduce it even more? because I only want to use OCR (image text reader).

**Comment by bharat-biradar** [comment]
@adriancsbna Could give me the android part of `build.gradle` that you used in your app. The same section mentioned by iks-ngb

**Comment by bharat-biradar** [comment]
@MalayAgrawal Maybe it can be reduced. I looked at the size of our example app using devtools and I found this.
![image](https://user-images.githubusercontent.com/62872048/119612029-0870c480-be19-11eb-958f-994687149fa2.png)
You can exclude models by mentioning it in `ignoreAssetsPattern` but I'm not sure which among these models are used for OCR.
![image](https://user-images.githubusercontent.com/62872048/119612279-52f24100-be19-11eb-87de-74ae7fc312e5.png)
First try by excluding whole model folder and then individually for each older. Let me know if it works.

**Comment by adriancsbna** [comment]
Hi @bharat-biradar here you have it

I managed to reduce the size by adding ignoreAssetsPattern '!mlkit_pose:' but I'm sure I can add more to lower the size further. Do you know what options there are to add there?

   buildTypes {
        release {
            signingConfig signingConfigs.debug
            aaptOptions {
                ignoreAssetsPattern '!mlkit_pose:'
            }
        }
        debug {
            signingConfig signingConfigs.debug
            aaptOptions {
                ignoreAssetsPattern '!mlkit_pose:'
            }
        }
    }

    packagingOptions {
        exclude 'lib/**/libtranslate_jni.so'
        exclude 'lib/**/libdigitalink.so'
        exclude 'lib/**/libxeno_native.so'
        //exclude 'lib/**/libmlkitcommonpipeline.so'
        exclude 'lib/**/libbarhopper_v2.so'
        //exclude 'lib/**/libclassifier_jni.so'
        exclude 'lib/**/libface_detector_v2_jni.so'
        exclude 'lib/**/libtensorflowlite_jni.so'
        exclude 'lib/**/liblanguage_id_jni.so'
    }

**Comment by MalayAgrawal** [comment]
```
buildTypes {
       release {
           signingConfig signingConfigs.release
            aaptOptions {
                ignoreAssetsPattern "mlkit_pose"
            }
       }
   }
   packagingOptions {
        exclude 'lib/**/libtranslate_jni.so'
        exclude 'lib/**/libdigitalink.so'
        exclude 'lib/**/libxeno_native.so'
        exclude 'lib/**/libmlkitcommonpipeline.so'
        exclude 'lib/**/libbarhopper_v2.so'
        exclude 'lib/**/libclassifier_jni.so'
        exclude 'lib/**/libface_detector_v2_jni.so'
        exclude 'lib/**/libtensorflowlite_jni.so'
        exclude 'lib/**/liblanguage_id_jni.so'
    }
```
![Screenshot_2021-05-27 DevTools for Flutter Dart](https://user-images.githubusercontent.com/55668156/119720947-350ff500-be88-11eb-979d-66d63e136c13.png)

OCR is working great and app size reduced to 30MB approx

**Comment by bharat-biradar** [comment]
@adriancsbna Try adding models along with mlkit_pose

**Comment by TusharPatel18** [comment]
since I'm using this package for scanning barcode to get results which unnecessary lib i need to excluded?
Thank you in advance : )

**Comment by bharat-biradar** [comment]
@TusharPatel18 I think you should comment out common pipeline and libbarh... I'm not sure I'm guessing as it looks similar to barcode, in in ignore assets add mlkit_pse and image label. Scroll up to see this implementation

**Comment by AlexHartford** [comment]
> since I'm using this package for scanning barcode to get results which unnecessary lib and models i need to excluded?
> Thank you in advance : )

One of my apps only uses it for barcode scanning, the following is how I have it configured:
<details>
<summary>Click to expand</summary>

```gradle
packagingOptions {
    exclude 'lib/**/libtranslate_jni.so'
    exclude 'lib/**/libdigitalink.so'
    exclude 'lib/**/libxeno_native.so'
    exclude 'lib/**/libmlkitcommonpipeline.so'
    // exclude 'lib/**/libbarhopper_v2.so' → required for barcode detection
    exclude 'lib/**/libclassifier_jni.so'
    exclude 'lib/**/libface_detector_v2_jni.so'
    exclude 'lib/**/libtensorflowlite_jni.so'
    exclude 'lib/**/liblanguage_id_jni.so'
}
```

</details>

**Comment by AlexHartford** [comment]
I'm not super familiar with the iOS side of things, is there an equivalent solution for iOS? Or is it necessary at all?

**Comment by fbernaly** [comment]
not for now, 3rd party dependencies are managed in Xcode using Cocoapods or Swift Package Manager, ours uses Cocoapods. Eventually I will work on a way to only add the scanners you need, but for now in iOS the bundle comes with all.

**Comment by ashwinkey04** [comment]
I am working on an app to use face detection alone. Is there any more stuff I can add to the `ignoreAssetsPattern` under `aaptOptions` to use only the face recognition stuff?

---
This is my current `aaptOptions` 
```
aaptOptions {
                ignoreAssetsPattern '!mlkit_pose:!mlkit_label_default_model:'
            }
```

**Comment by bharat-biradar** [comment]
@ashwinkey04 Analyze the app size through dev tools and look at the instances under `assets` section. Try removing those which seem unnecessary. An example screenshot can be obtained above.

**Comment by ashwinkey04** [comment]
Thanks a lot @bharat-biradar. I removed a few models without breaking the app and managed to bring the size down to 35 MB for the bulk release apk and 23 MB for v8a. Yet to try and remove more assets as I am expected to make something less than 10 MB. Thanks for the time :)

**Comment by bhanuka96** [comment]
@adriancsbna how about IOS?

**Comment by tokyokamera** [comment]
I want to use Japanese Text recognition only. What should I do?

**Comment by wazini-john** [comment]
@ashwinkey04 What did you exclude for only facedetection ?

**Comment by wazini-john** [comment]
I'm only  using `facedetector`
 My gradle file looks like this
```
buildTypes {
		release {
			// TODO: Add your own signing config for the release build.
			// Signing with the debug keys for now, so `flutter run --release` works.
			signingConfig signingConfigs.debug
			aaptOptions {
				ignoreAssetsPattern 'mlkit_pose'
				ignoreAssetsPattern '!mlkit_pose:!mlkit_label_default_model:'
				ignoreAssetsPattern '!mlkit_pose:'
			}
		}
		debug {
			aaptOptions {
				ignoreAssetsPattern 'mlkit_pose'
				ignoreAssetsPattern '!mlkit_pose:!mlkit_label_default_model:'
				ignoreAssetsPattern '!mlkit_pose:'
			}
		}
	}
	packagingOptions {
		exclude 'lib/**/libtranslate_jni.so'
		exclude 'lib/**/libdigitalink.so'
		exclude 'lib/**/libxeno_native.so'
		exclude 'lib/**/libmlkitcommonpipeline.so'
		exclude 'lib/**/libbarhopper_v2.so'
		exclude 'lib/**/libclassifier_jni.so'
		exclude 'lib/**/libpredictor_jni.so'
		exclude 'lib/**/libtextclassifier3_jni_tclib.so'
		// exclude 'lib/**/libface_detector_v2_jni.so'
		exclude 'lib/**/libtensorflowlite_jni.so'
		exclude 'lib/**/liblanguage_id_jni.so'
	}
```

But the size is still huge.. especially the `hobbes.tflite`,

<img width="1440" alt="Screenshot 2021-07-01 at 11 57 16" src="https://user-images.githubusercontent.com/78900743/124097350-2b1f7a00-da64-11eb-9199-7ef51f39d058.png">
<img width="1440" alt="Screenshot 2021-07-01 at 11 58 19" src="https://user-images.githubusercontent.com/78900743/124097388-34104b80-da64-11eb-87fb-867d4fac05ba.png">

What else do I exclude ?

**Comment by bharat-biradar** [comment]
@wazini-john Try excluding `hobbes.tflite` it should not be related to face detection IG.

**Comment by deepaklohmod6789** [comment]
How can i remove hobbes.tflite, I also need only for face detection

**Comment by bharat-biradar** [comment]
@deepaklohmod6789 Mention `hobbes.tflite` in `ignoreAssetsPattern` along with any other assets you want to ignore. Refer to the example above.

**Comment by deepaklohmod6789** [comment]
```
aaptOptions {
                ignoreAssetsPattern 'mlkit_pose'
                ignoreAssetsPattern 'hobbes.tflite'
                ignoreAssetsPattern '!mlkit_pose:!mlkit_label_default_model:'
                ignoreAssetsPattern '!mlkit_pose:'
            }
```
I did this but still the size is 86.6 mb

**Comment by cngeru** [comment]
@deepaklohmod6789 run `flutter clean` then `flutter pub get`...
combine all options to one string `ignoreAssetsPattern '!mlkit_pose:!mlkit_label_default_model:!hobbes.tflite:'`

**Comment by deepaklohmod6789** [comment]
@cngeru thanks a lot, it worked : )

**Comment by swissonid** [comment]
Is there any technical reason that is holding us back from splitting this plugin into multiple packages? I don't see one use case where I need all the ml-models at once. Or do I oversee something?

**Comment by SatishKumarRaizada** [comment]
@swissonid i completely agree. I think would add more value if we can split the models into different module like - TextRecognise, BarCode Reader etc...

**Comment by cngeru** [comment]
@SatishKumarRaizada  and @swissonid  Someone opened an issue  regarding this issue [here](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/76)

**Comment by fbernaly** [comment]
@swissonid, @SatishKumarRaizada: collaboration is always welcome, feel free to send a PR with what you are proposing

**Comment by bharat-biradar** [comment]
@swissonid I am checking if we can work with unbundled models instead of model bundels. If it works I think size won't be an issue then.

**Comment by swissonid** [comment]
@fbernaly I spend yesterday on smaller lib ([google_ml_vision](https://github.com/brianmtully/flutter_google_ml_vision) )because that the one we use right now. Anyway, the problem is the same. And with a "simple" PR it isn't done. If the vision of this Plugin / Lib is to split it into smaller pieces, that will a fundamental change in the architecture. And gonna take its time. 
[This is a sketched possible solution. Not Yet finished](https://github.com/swissonid/flutter_google_ml_vision/tree/bugfix/%239-ML-Vision-dependencies).

**Comment by fbernaly** [comment]
Thanks @swissonid : I will look at it. Splitting this plugin into multiple packages will take some time.

**Comment by NighttCoder** [comment]
Any ideas to reduce AppSize in iOS. I am only using OCR and app size after including this plugin increases by ~50MB.

**Comment by Surajsahani28** [comment]
How we reduce app size in IOS ?

**Comment by NighttCoder** [comment]
@Surajsahani28 I couldn’t find a way to reduce the app size with this plugin..I ended using the cloud ocr ..

**Comment by hesmnyn** [comment]
> not for now, 3rd party dependencies are managed in Xcode using Cocoapods or Swift Package Manager, ours uses Cocoapods. Eventually I will work on a way to only add the scanners you need, but for now in iOS the bundle comes with all.

any update?
@fbernaly

**Comment by PabloLavin** [comment]
If it's not too much to ask for, I would love if anybody can list what 
ignoreAssetsPattern 
and 
packagingoptions 

refer to each of the ML Kit assets, or share a link of any docs that talk about that.

**Comment by itssidhere** [comment]
Does anyone have any idea about parameters for translation kit only? @bharat-biradar

**Comment by itssidhere** [comment]
For anybody looking to seriously reduce the size, I would suggest going to the plugin implementation.
Comment unnecessary files in the build.grade. Then comment all the files src>nlp / src>vision based on what you need. This is a hit and trial method and you will get few errors just keep commenting down things whose implementation you have commented and in the end, it will compile. In my case, I only needed the translator plugin. It is easier than going through apk size tool again and again.
```
dependencies {
    // implementation 'com.google.android.gms:play-services-mlkit-barcode-scanning:16.2.1'

    // implementation 'com.google.android.gms:play-services-mlkit-image-labeling:16.0.5'
    // implementation 'com.google.mlkit:image-labeling-custom:16.3.1'
    // implementation 'com.google.mlkit:image-labeling-automl:16.2.1'

    // implementation 'com.google.android.gms:play-services-mlkit-text-recognition:17.0.0'
    // implementation 'com.google.mlkit:language-id:17.0.0'
    // implementation 'com.google.mlkit:digital-ink-recognition:17.0.0'

    // implementation 'com.google.mlkit:pose-detection:17.0.1-beta5'
    // implementation 'com.google.mlkit:pose-detection-accurate:17.0.1-beta5'

     implementation 'com.google.mlkit:translate:16.1.2'
    // implementation 'com.google.mlkit:entity-extraction:16.0.0-beta2'
    // implementation 'com.google.mlkit:smart-reply:16.2.0'

    // implementation 'com.google.mlkit:object-detection:16.2.6'
    // implementation 'com.google.mlkit:object-detection-custom:16.3.3'
    // implementation 'com.google.mlkit:linkfirebase:16.1.1'

    // implementation 'com.google.android.gms:play-services-mlkit-face-detection:16.2.0'
}
```

**Comment by bharat-biradar** [comment]
@nachtmaar Sorry but I don't know about Ios side of things but please try and if it works, please mention it here.

**Comment by svprdga** [comment]
Thanks @nachtmaar for the effort  of creating the fork, that was exactly what I was looking for.

**Comment by anounboy** [comment]
i only use pose detection and my  aaptOptions is 

`aaptOptions {
                ignoreAssetsPattern '!mlkit_ocr:!mlkit_label_default_model:'
                ignoreAssetsPattern 'hobbes.tflite'

            }`

`packagingOptions {
        exclude 'lib/**/libtranslate_jni.so'
        exclude 'lib/**/libdigitalink.so'
        exclude 'lib/**/libxeno_native.so'
        exclude 'lib/**/libmlkitcommonpipeline.so'
        exclude 'lib/**/libbarhopper_v2.so'
        exclude 'lib/**/libclassifier_jni.so'
        exclude 'lib/**/libface_detector_v2_jni.so'
        exclude 'lib/**/libtensorflowlite_jni.so'
        // exclude 'lib/**/liblanguage_id_jni.so' → required for language detection
    }`

but it's size still 129 mb please help me to reduce the size.

**Comment by fbernaly** [comment]
We released a new version of [google_ml_kit](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit) in which we have split all the plugins in multiple plugins to avoid removing the models for API you are not using, go to our readme and start using the new plugin you need.

More details here:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit

**Comment by Visio-Biswaroop** [comment]
> 

Hi, I am using:
dependencies {
...
... 
implementation 'com.google.mlkit:translate:17.0.1'
...
}
I want to just use Language X (any one language)  to English translation. Is there a way I can optimise MLKit further to reduce my apk size?

**Comment by KartavyaBagga** [comment]
> ```
> buildTypes {
>        release {
>            signingConfig signingConfigs.release
>             aaptOptions {
>                 ignoreAssetsPattern "mlkit_pose"
>             }
>        }
>    }
>    packagingOptions {
>         exclude 'lib/**/libtranslate_jni.so'
>         exclude 'lib/**/libdigitalink.so'
>         exclude 'lib/**/libxeno_native.so'
>         exclude 'lib/**/libmlkitcommonpipeline.so'
>         exclude 'lib/**/libbarhopper_v2.so'
>         exclude 'lib/**/libclassifier_jni.so'
>         exclude 'lib/**/libface_detector_v2_jni.so'
>         exclude 'lib/**/libtensorflowlite_jni.so'
>         exclude 'lib/**/liblanguage_id_jni.so'
>     }
> ```
> 
> ![Screenshot_2021-05-27 DevTools for Flutter Dart](https://user-images.githubusercontent.com/55668156/119720947-350ff500-be88-11eb-979d-66d63e136c13.png)
> 
> OCR is working great and app size reduced to 30MB approx

How to reduce app size further below 30MB
