### ISSUE TITLE
use disaggregated model mlkit face detection

### ISSUE THREAD

**Issue by edwinmacalopu** [bharat-biradar/Google-Ml-Kit-plugin#263]
Why not use the disaggregated model to reduce the weight of the app?

instead of using

```
dependencies {
     implementation 'com.google.mlkit:face-detection:16.1.5'
}
```

Should use

```
  dependencies {
       // Use this dependency to use dynamically downloaded model in Google Play Service
       implementation 'com.google.android.gms:play-services-mlkit-face-detection:17.0.1'
     }
```

**Comment by fbernaly** [comment]
@edwinmacalopu: using the dependency from Google Play Service  would require your app to have an internet connection to  download the model. But at the same time, if they are downloading your app from the AppStore we could assume they have internet. But nothing guarantee that they will open the app immediately to download the model... that is why we went with the dependency that already includes the model... but we are open to changes and we could explore that option more.
