### ISSUE TITLE
ObjectDetector does not work for InputImage.fromFilePath() or InputImage.fromFile()

### ISSUE THREAD

**Issue by pbrejdak** [bharat-biradar/Google-Ml-Kit-plugin#264]
Currently `ObjectDetector` works only for `InputImage.fromBytes` which is working only when operating `Camera` plugin since there is no other way to encode `planeBytes` for `InputImageData`. I'm attaching photos below from example app provided in this repository

<details>
<summary>When I'm trying to process via camera image it's working properly. Photo below</summary>

![Screenshot_2022-05-23-20-21-07-943_com google_mlkit_example](https://user-images.githubusercontent.com/10552567/169883277-2f47e052-1d85-4bca-8e7c-b2b20cd7aeea.jpg)
</details>

<details>
<summary>But when I'm trying to use photo from gallery it founds nothing. Photo below</summary>

![Screenshot_2022-05-23-20-21-59-156_com google_mlkit_example](https://user-images.githubusercontent.com/10552567/169883415-5b4f51ec-944d-4b52-afae-460939eb6138.jpg)
</details>

<details>
<summary>Here's source photo if needed. Photo below</summary>

![IMG_20220523_202124](https://user-images.githubusercontent.com/10552567/169883805-785a7f42-4777-4c49-91d8-60ee8b1d9fa2.jpg)

</details>

Is this a bug or just `ObjectDetector` is not supporting files loaded from FS?

**Comment by fbernaly** [comment]
@pbrejdak: are you changing the mode from `stream` to `single` for `ObjectDetectorOptions`? https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_mlkit_object_detection/lib/src/object_detector.dart#L74

The example app is hardcoded to use always stream, but feel free to send a PR fixing that.

**Comment by fbernaly** [comment]
When I tweaked the example app to use single instead of stream:

![Screen Shot 2022-05-23 at 12 08 09 PM](https://user-images.githubusercontent.com/7014968/169889373-787c404f-d104-40da-96b5-9e5a8b5e7679.png)


It is working, do the same in your code:

![Screenshot_20220523-120435](https://user-images.githubusercontent.com/7014968/169889182-0b16ad21-9c92-4de8-8b1c-e215170f0ddf.png)

**Comment by fbernaly** [comment]
BTW, our plugin does not provide a widget to draw the bounding rect or id on top of your image, that is something extra that the example app is doing, but we are only doing it for the camera feed, for gallery we are just printing the text and tracking id as you can see in my screenshoot.
You can handle the drawing on top of your image if needed.

**Comment by pbrejdak** [comment]
Thank you very much for such a detailed answer to my question, it helped. If I will have a spare hours I will gladly do a PR to fix adding images from gallery to the processor.
