### ISSUE TITLE
InputImageRotationMethods Not Found

### ISSUE THREAD

**Issue by nwjun** [bharat-biradar/Google-Ml-Kit-plugin#268]
When creating Input Image from CameraImage, the documentation stated the rotation method as:

```python
final InputImageRotation imageRotation =
    InputImageRotationMethods.fromRawValue(camera.sensorOrientation) ??
        InputImageRotation.rotation0deg;
```

However, the method is not found in the plugin.

**Comment by fbernaly** [comment]
Thanks for finding this bug in the documentation.
