### ISSUE TITLE
Once I added this package to the project the image_picker package stopped working !!

### ISSUE THREAD

**Issue by hassanyassiin** [bharat-biradar/Google-Ml-Kit-plugin#270]
once I added this package, I wasn't able to select images anymore by image_picker I tried with several projects. the gallery will open but the image will return nul, I don't know why but that what happening

**Comment by fbernaly** [comment]
Look at your dependencies. Fixing `image_picker` is outside the scope of this plugin. Check our example app, it is using `image_picker` and it is working with no issues in both iOS and Android, so I am afraid this more an issue is your dependencies and how you are configuring your project.  

Check our example app, clone our repo: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit/example

Also, a couple of days ago I created this sample that uses one of our plugins and `image_picker`, and it is running with no issues: https://github.com/fbernaly/web_text_recognition_poc

**Comment by hassanyassiin** [comment]
Hello, thanks for your response, i have two question, first when i added armv7 to the excluded architecture, the arm64 qdded by default when i try to remove it it shows me error, second when configuring firebase to the ios app i only added the bundle id and the GoogleService-info.plist to the project without any extra code, is it right like that ?

TEST
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by fbernaly** [comment]
yes, unfortunately  in case of object detection you need Firebase, and that is because for this API there is this one feature that allows you to download your model from Firebase. And since the plugin bundles everything together we have not found a way to get rid of that. Other than adding the GoogleService-info.plist to the project you need to initialize [Initialize Firebase in your app](https://firebase.google.com/docs/ios/setup#initialize-firebase).

**Comment by fbernaly** [comment]
What do you mean with added automatically? never seen that?

**Comment by hassanyassiin** [comment]
ok then i added the GoogleService-info.plist to my project and i initialized firebase in my app but i didn't add the firebase sdk into my app as step 3 said is it necessary ? 

Once i added the amrv7 there ....
<img width="1512" alt="Screen Shot 2022-06-01 at 9 26 13 AM" src="https://user-images.githubusercontent.com/94860683/171341233-b182f637-d5b1-4e62-b1c7-2ae7bb77ff2b.png">


Then arm64 added here automatically, when i tried to remove it an error accur "Target Integrity (Xcode): The linked framework 'Pods_Runner.framework' is missing one or more architectures required by this target: arm64."

**Comment by hassanyassiin** [comment]
@fbernaly Please can you help to fix this issue about adding the amr64 automatically ? because I'm not able to run my app on the iOS simulators but on any iOS real device it works great and also on the android devices/emulators

**Comment by hassanyassiin** [comment]
Hello, no I’m excluding the armv7 in the project level but once i added there, it automatically added to the target level then if i remove it in the target level the simulator will throw an error

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fbernaly** [comment]
Compare side by side with our example app. Ours can be ran in the simulator

**Comment by hassanyassiin** [comment]
Thanks for your response, kindly can you send me the buildsettings in the target runner please ? I want to see the excluded architecture in you target level

TEST
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by fbernaly** [comment]
it is in the repo: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit/example/ios

clone our repo and run the app

**Comment by hassanyassiin** [comment]
@fbernaly Thanks for your help! i clone the app and it is working great in all devices but except on the IOS simulators, the app run in the IOS simulator  without errors but what happen is that the image picker will return null when select an image, and even the object detector package didn't work in the IOS simulator and what i noticed that once i run the app the arm64 added automatically into the target-> Exculed Architectures -> Any IOS Simulator !!.

<img width="707" alt="Screen Shot 2022-06-05 at 8 49 02 PM" src="https://user-images.githubusercontent.com/94860683/172063596-f0fce94a-fdee-4d37-a662-df5701b83960.png">

Kindly can you check on your IOS Simulator if the image picker return an image ? and if yess can you help me to solve this issue it take me too long and didn't find any solution and the deadline for me is Tuesday to submit my task!!!.
Note: I'm using Macbook pro m1

**Comment by fbernaly** [comment]
Sorry, I cannot do anymore, I also running on a M1 processor and for me it is perfectly running on the iOS simulator. I cannot reproduce the same issue you are facing. I mage picker is working as well.
