### ISSUE TITLE
Target Integrity (Xcode): The linked framework 'Pods_Runner.framework' is missing one or more architectures required by this target: arm64.

### ISSUE THREAD

**Issue by hassanyassiin** [bharat-biradar/Google-Ml-Kit-plugin#272]
As mentioned in the documentation that we should add armv7 in the Excluded Architecture but when added this arm64 added automatically beside amv7 and i386. is it ok for that ? and I also when configuring iOS to firebase I only added the json file that downloaded to the runner without adding step 3 and 4 (adding code to the appDelegate)  as I suggested by someone, so is it right ?

**Comment by fbernaly** [comment]
I case of iOS you also need to call

```
@import Firebase;

[FIRApp configure];
```

in the `AppDelegate`

**Comment by fbernaly** [comment]
Other than adding the GoogleService-info.plist to the project you need to initialize [Initialize Firebase in your app](https://firebase.google.com/docs/ios/setup#initialize-firebase).
