### ISSUE TITLE
How to convert the detected object to a XFile or File .... !

### ISSUE THREAD

**Issue by hassanyassiin** [bharat-biradar/Google-Ml-Kit-plugin#276]
How to convert the detected objects to a File like the image below ?

![WhatsApp Image 2022-06-03 at 3 20 50 PM](https://user-images.githubusercontent.com/94860683/171853058-a11190f1-1eaf-4eff-b3f3-fd71c8a0482e.jpeg)

**Comment by fbernaly** [comment]
You need to crop the image, using the boundingReact returned by the detector. But that is outside the scope of this plugin. This plugin will only detect the object and return an instance of [DetectedObject](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_mlkit_object_detection/lib/src/object_detector.dart#L180-L210). How you process that response it up to the developer. For a list of all the capabilities of this plugin look at our [readme for this plugin](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_object_detection). If what you want to do is not there, then it is oiutside the scope of this plugin.
