### ISSUE TITLE
face detect attributes returns null

### ISSUE THREAD

**Issue by wmla419** [bharat-biradar/Google-Ml-Kit-plugin#28]
```
              faces[0].leftEyeOpenProbability
              faces[0].headEulerAngleY,
              faces[0].headEulerAngleZ,
              faces[0].rightEyeOpenProbability,
              faces[0].smilingProbability,
              faces[0].trackingID);
```
Why is it returns null from all these attributes after it detected a face from live camera?

**Comment by fbernaly** [comment]
is this for iOS or Android?

**Comment by wmla419** [comment]
> is this for iOS or Android?
Android

**Comment by wmla419** [comment]
I just tried to clone the example project and run it on simulator, but it still return null.

**Comment by fbernaly** [comment]
try running on an actual device

**Comment by wmla419** [comment]
> try running on an actual device

sorry for typo, i tried to run on physica device.

**Comment by fbernaly** [comment]
ok, I will take a look at it

**Comment by fbernaly** [comment]
@wmla419: after reviewing, the example app is working as expected look at the configuration for the Detector options, only the contour is enabled:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/example/lib/VisionDetectorViews/face_detector_view.dart#L12-L15

if you are interested in classification you can enable that as well, but be cautions, there are some constraint outlines in the real time Face detection API.

https://developers.google.com/ml-kit/vision/face-detection/android#real-time_face_detection

According to that you cannot have Contour detection and classification enabled at the same time, but I changed it in my example app and it is working. Give it a try.

```
FaceDetector faceDetector =
      GoogleMlKit.vision.faceDetector(FaceDetectorOptions(
    enableContours: true,
    enableClassification: true,
  ));
```
