### ISSUE TITLE
Smallest Text Detection elements for Chinese are lines, not characters

### ISSUE THREAD

**Issue by craigomac** [bharat-biradar/Google-Ml-Kit-plugin#283]
According to the documentation at https://developers.google.com/ml-kit/vision/text-recognition:

> an Element is a contiguous set of alphanumeric characters ("word") on the same axis in most Latin languages, or **a character in others**

I'm initialising a text recogniser like so:

```dart
    final RecognizedText recognizedText = await textRecognizer.processImage(inputImage);
    textRecognizer.close();

    final blocks = <OcrResultBlock>[];
    for (final block in recognizedText.blocks) {
      for (final line in block.lines) {
        if (!line.recognizedLanguages.contains('zh')) {
          continue;
        }

        for (final element in line.elements) {
        ...
```

What I'm seeing is that at the `element` level, text is still grouped into contiguous lines—not individual characters, and not even compound words and phrases.

**Comment by fbernaly** [comment]
@craigomac: could you compare running the native example, use the same image and let us know if for the native the API is also returning the same for elements.

https://github.com/googlesamples/mlkit

**Comment by craigomac** [comment]
Thanks @fbernaly. I verified that the native frameworks have the same behaviour and have raised this as a bug with MLKit here: https://github.com/googlesamples/mlkit/issues/535.
