### ISSUE TITLE
Dependency problem between firebase_core and google_ml_kit.

### ISSUE THREAD

**Issue by std-s** [bharat-biradar/Google-Ml-Kit-plugin#292]
hi, 
  I have this problem, how to solve it?

```
Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm (Rosetta),
    locale en-CN)
```
```
  google_ml_kit: 0.11.0
  firebase_core: 1.19.0
```
![image](https://user-images.githubusercontent.com/99468005/177722225-9ec8eeb0-9c41-493a-b515-eec6984ed45c.png)

**Comment by MichiruNakam** [comment]
I was having the same problem since Friday 01/07. The problem seems that this package is outdated and does not work with FirebaseCore 9.2.0. My workaround was to downgrade some packages in the pubspec.yaml, and adding the package `firebase_core_platform_interface` with a fixed version:
```
firebase_messaging: 11.4.2 # For push notifications
firebase_core: 1.18.0 # Bundle for firebase
firebase_core_platform_interface: 4.4.1
```
Don't forget to run `flutter clean`

**Comment by nirbar89** [comment]
Same here any update?

**Comment by 04pd** [comment]
facing same issue any update?

**Comment by SebghatYusuf** [comment]
same issue

**Comment by fbernaly** [comment]
Hi guys, sorry for the delay. Thanks for using our plugin. @bharat-biradar and I have been maintaining this plugin, but sometimes we cannot provide all the support you need. Both of us are busy with school, work and family. We created this plugin as an open source project. We do not have an ETA for this fix, too busy with so many things, but you are welcome to fork our repo, fix whatever is broken and sent the PR. We will review PRs as soon as possible and release a new version.

If the plugin is not compatible with those version try to update the versions our plugin is using and send a PR.
