### ISSUE TITLE
Simulator app crashed after using google_mlkit_language_id function

### ISSUE THREAD

**Issue by floheitzmann** [bharat-biradar/Google-Ml-Kit-plugin#294]
Hi 👋
I've tried the `google_mlkit_language_id 0.3.0` plugin to detect the language from user comments but when I use the `await languageIdentifier.identifyLanguage(text);` function my app crashes.

I don't know what to do next, I have complied with the requirements and added everything.

My crash report because it's too long for GitHub. https://pastebin.com/jAJ9gFmD

**Comment by fbernaly** [comment]
ML Kit only supports 64-bit architectures (x86_64 and arm64). ML Kit does not support 32-bit architectures (i386 and armv7). Make sure the device or simulator you run conforms with that.

source: https://developers.google.com/ml-kit/migration/ios

**Comment by khjde1207** [comment]
I found a solution.
[      'id': id,](https://github.com/khjde1207/Google-Ml-Kit-plugin/blob/e2f5f813ec586ce8bf8fd25e15e6dd415d17d1ae/packages/google_mlkit_language_id/lib/src/language_identifier.dart#L44)
