### ISSUE TITLE
Adjust face tracking

### ISSUE THREAD

**Issue by Ahmad-Jarrar** [bharat-biradar/Google-Ml-Kit-plugin#296]
I am using the face detection module with tracking on. I don't find the tracking to be very accurate, and the ids change too often and essentially the bounding boxes drawn are jittery.

I want to know is there a way to adjust the tracker (i.e change the number of missed frames to drop track). Or to incorporate a different tracker.

**Comment by fbernaly** [comment]
All the documentation is in our repo or in Google's ML Kit official documentation:

- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_face_detection#googles-ml-kit-face-detection-for-flutter
- https://developers.google.com/ml-kit/vision/face-detection
- https://developers.google.com/ml-kit/vision/face-detection/face-detection-concepts
- https://developers.google.com/ml-kit/vision/face-detection/ios
- https://developers.google.com/ml-kit/vision/face-detection/android

Our API maches the APIs explained in Google's ML Kit official documentation.

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_mlkit_face_detection/lib/src/face_detector.dart
