### ISSUE TITLE
Anyway to recognize the text in complex scenarios ?

### ISSUE THREAD

**Issue by cimplesid** [bharat-biradar/Google-Ml-Kit-plugin#308]
<img width="457" alt="Screen Shot 2022-08-02 at 5 01 37 PM" src="https://user-images.githubusercontent.com/29953052/182362025-638ac177-60bb-40b8-b7db-a97dde643851.png">

**Comment by cimplesid** [comment]
<img width="454" alt="Screen Shot 2022-08-02 at 5 02 29 PM" src="https://user-images.githubusercontent.com/29953052/182362187-b7f70a72-5061-4a33-aa49-538b4583efdf.png">

**Comment by fbernaly** [comment]
????
@cimplesid: Add detail description please? Otherwise we will close issue.

**Comment by cimplesid** [comment]
How can we extract Text from above image ? Can we modify given model to do. so ?

**Comment by fbernaly** [comment]
This is the guidelines for text detection: https://developers.google.com/ml-kit/vision/text-recognition

What you are asking it is not supported the Google's API.
