### ISSUE TITLE
draw boundingRect on top of still image not showing

### ISSUE THREAD

**Issue by vidalbenjoe** [bharat-biradar/Google-Ml-Kit-plugin#311]
boundingRect is not showing on a captured image or from the gallery for the object detection.
Please see the code below for your reference.

` String text = 'Objects found: ${objects.length}\n\n';
      for (final object in objects) {
        text +=
            'Object:  trackingId: ${object.trackingId} - ${object.labels.map((e) => e.text)}\n\n';
      }
      _text = text;
      // TODO: set _customPaint to draw boundingRect on top of image
      Size originalSize = MediaQuery.of(_mContext).size;
       Size imageSize = Size(360.0 * originalSize.aspectRatio, 360.0);
      // // if image source from gallery
      // // image display size is scaled to 360x360 with retaining aspect ratio
      if (originalSize.aspectRatio > 1) {
        imageSize = Size(360.0, 360.0 / originalSize.aspectRatio);
      } else {
        imageSize = Size(360.0 * originalSize.aspectRatio, 360.0);
      }

      final painter = ObjectDetectorPainter(
          objects,
          InputImageRotation.rotation0deg,
          imageSize);
      _customPaint = CustomPaint(painter: painter);`

**Comment by fbernaly** [comment]
Drawing the boundingRect on top of your input image is outside the scope of these plugin. Refer to README for the features of this plugin: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_object_detection.
