### ISSUE TITLE
Example Project errors

### ISSUE THREAD

**Issue by RealWorldApplications** [bharat-biradar/Google-Ml-Kit-plugin#32]
In the file **barcode_detector_painter.dart** whenever barcode.info! is referenced it needs to be replaced with barcode.barcodeUnknown!

In the file **barcode_scanner_view.dart**  the following needs to be replaced
 BarcodeFormat.Default,
    BarcodeFormat.Code_128,
    BarcodeFormat.Code_39,
    BarcodeFormat.Code_93,
    BarcodeFormat.Codebar,
    BarcodeFormat.EAN_13,
    BarcodeFormat.EAN_8,
    BarcodeFormat.ITF,
    BarcodeFormat.UPC_A,
    BarcodeFormat.UPC_E,
    BarcodeFormat.QR_Code,
    BarcodeFormat.PDF417,
    BarcodeFormat.Aztec,
    BarcodeFormat.Data_Matrix

with this

 Barcode.FORMAT_Default,
    Barcode.FORMAT_Code_128,
    Barcode.FORMAT_Code_39,
    Barcode.FORMAT_Code_93,
    Barcode.FORMAT_Codabar,
    Barcode.FORMAT_EAN_13,
    Barcode.FORMAT_EAN_8,
    Barcode.FORMAT_ITF,
    Barcode.FORMAT_UPC_A,
    Barcode.FORMAT_UPC_E,
    Barcode.FORMAT_QR_Code,
    Barcode.FORMAT_PDF417,
    Barcode.FORMAT_Aztec,
    Barcode.FORMAT_Data_Matrix

In the file **text_detector_painter.dart** 
textBlock.text replace with textBlock.blockText
and where textBlock.rect is referenced replace with textBlock.blockRect

**Comment by fbernaly** [comment]
@RealWorldApplications : I dont get the issue. We renamed some of that in this PR https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/30 and the new options should be `BarcodeFormat.*`, pull the latest code from master.
