### ISSUE TITLE
Why does this plugin generate libmlkit_google_ocr_pipeline.so for x86 architecture?

### ISSUE THREAD

**Issue by HarsHvA** [bharat-biradar/Google-Ml-Kit-plugin#323]
Flutter dosen't support x86 architecture. But this plugin still generates libmlkit_google_ocr_pipeline.so for x86. Due to which we get libflutter.so missing error and the app crashes. Is there anyway we can stop creating libmlkit_google_ocr_pipeline.so for x86 architecture?

**Comment by fbernaly** [comment]
is that for Android or iOS?

**Comment by HarsHvA** [comment]
@fbernaly for android
