### ISSUE TITLE
CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core"

### ISSUE THREAD

**Issue by JoergPf** [bharat-biradar/Google-Ml-Kit-plugin#333]
Hi, I just installed google_ml_kit: ^0.12.0 and when I want to run on iOS I get the error:

```
[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
      In snapshot (Podfile.lock):
        GTMSessionFetcher/Core (< 2.1, < 3.0, = 2.0.0, >= 1.7)
      In Podfile:
        google_mlkit_barcode_scanning (from `.symlinks/plugins/google_mlkit_barcode_scanning/ios`) was resolved to 0.4.0, which depends on
          GoogleMLKit/BarcodeScanning (~> 3.1.0) was resolved to 3.1.0, which depends on
            MLKitBarcodeScanning (~> 2.1.0) was resolved to 2.1.0, which depends on
              MLKitVision (~> 4.1) was resolved to 4.1.0, which depends on
                GTMSessionFetcher/Core (~> 1.1)
```
Do I have to downgrade GTMSessionFetcher/Core? Or is there a better way to handle this?

Thx!

**Comment by sikandernoori** [comment]
Same issue.

```
[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In Podfile:
    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 4.0.2, which depends on
      Firebase/Auth (= 10.0.0) was resolved to 10.0.0, which depends on
        FirebaseAuth (~> 10.0.0) was resolved to 10.0.0, which depends on
          GTMSessionFetcher/Core (~> 2.1)
          ```

**Comment by antoniopetricc** [comment]
Same issue 

[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In Podfile:
    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 4.0.2, which depends on
      Firebase/Auth (= 10.0.0) was resolved to 10.0.0, which depends on
        FirebaseAuth (~> 10.0.0) was resolved to 10.0.0, which depends on
          GTMSessionFetcher/Core (~> 2.1)

**Comment by sikandernoori** [comment]
The problem is with GTMSessionFetcher/Core.

Firebase Auth uses version 2.1 [link](https://github.com/CocoaPods/Specs/blob/68ec86b7926781457a465b3ef2b026f831b8b8ed/Specs/6/3/6/FirebaseAuth/10.0.0/FirebaseAuth.podspec.json#L54)

While MLKIT uses version 1.1 [link](https://github.com/CocoaPods/Specs/blob/68ec86b7926781457a465b3ef2b026f831b8b8ed/Specs/c/c/6/MLKitCommon/8.0.0/MLKitCommon.podspec.json#L4)

Someone from Google team has to update this in PODS.

PODS source is not available else I would have created a temporary pod.

**Comment by antoniopetricc** [comment]
> The problem is with GTMSessionFetcher/Core.
> 
> Firebase Auth uses version 2.1 [link](https://github.com/CocoaPods/Specs/blob/68ec86b7926781457a465b3ef2b026f831b8b8ed/Specs/6/3/6/FirebaseAuth/10.0.0/FirebaseAuth.podspec.json#L54)
> 
> While MLKIT uses version 1.1 [link](https://github.com/CocoaPods/Specs/blob/68ec86b7926781457a465b3ef2b026f831b8b8ed/Specs/c/c/6/MLKitCommon/8.0.0/MLKitCommon.podspec.json#L4)
> 
> Someone from Google team has to update this in PODS.
> 
> PODS source is not available else I would have created a temporary pod.

How long will we have to wait for a fix?
