### ISSUE TITLE
Google_mlkit_face_detection    java.lang.OutOfMemory Error

### ISSUE THREAD

**Issue by GorIvanov** [bharat-biradar/Google-Ml-Kit-plugin#339]
Performance question/issue.

It can't process a stream from the camera in real time. I got only 10 fps on Samsung s21 ultra ( Exynos 2100 ).
If I try to process more frames per second, then after 3-5 minutes there is a sharp overflow of memory and an error  java.lang.OutOfMemory Error.

Regarding the load on the processor, regardless of whether I process 10 frames or 30, the load is at 45%, that is, the problem is with garbage collection and overflow.

Please give me some comments about this.

////
java.lang.OutOfMemoryError: Failed to allocate a 3686736 byte allocation with 1829888 free bytes and 1787KB until OOM, target footprint 268435456, growth limit 268435456
E/AndroidRuntime( 8348): 	at java.util.Arrays.copyOf(Arrays.java:3670)
E/AndroidRuntime( 8348): 	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:120)
E/AndroidRuntime( 8348): 	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:95)
E/AndroidRuntime( 8348): 	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:156)
E/AndroidRuntime( 8348): 	at io.flutter.plugin.common.StandardMessageCodec.writeBytes(StandardMessageCodec.java:196)
E/AndroidRuntime( 8348): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:247)
E/AndroidRuntime( 8348): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
E/AndroidRuntime( 8348): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:277)
E/AndroidRuntime( 8348): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
E/AndroidRuntime( 8348): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:63)
E/AndroidRuntime( 8348): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:251)
E/AndroidRuntime( 8348): 	at io.flutter.plugins.camera.Camera.lambda$setImageStreamImageAvailableListener$16(Camera.java:1166)
E/AndroidRuntime( 8348): 	at io.flutter.plugins.camera.Camera$$ExternalSyntheticLambda1.run(Unknown Source:4)
E/AndroidRuntime( 8348): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 8348): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 8348): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime( 8348): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime( 8348): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
E/AndroidRuntime( 8348): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8348): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime( 8348): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
I/example.cantes( 8348): Starting a blocking GC Alloc
I/example.cantes( 8348): Starting a blocking GC Alloc
V/FaceDetectorV2Jni( 8348): detectFacesImageByteArray.end()
V/FaceDetectorV2Jni( 8348): detectFacesImageByteArray.start()
I/example.cantes( 8348): Alloc young concurrent copying GC freed 853(157KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 255MB/256MB, paused 83us,67us total 10.707ms
I/example.cantes( 8348): Forcing collection of SoftReferences for 450KB allocation
I/example.cantes( 8348): Starting a blocking GC Alloc
I/Process ( 8348): Sending signal. PID: 8348 SIG: 9
Lost connection to device.

**Comment by maciejbrzezinski** [comment]
Hey @GorIvanov, have you solved it?

**Comment by Nashev** [comment]
I have same situation. Very sad here no solution described....
