### ISSUE TITLE
Integrating in projects with Firebase causes iOS app to have errors while 'pod install'

### ISSUE THREAD

**Issue by Nickkorol** [bharat-biradar/Google-Ml-Kit-plugin#34]
I have a project, where I am using firebase pubs:
  firebase_core: ^1.2.0
  firebase_crashlytics: ^2.0.3
  firebase_analytics: ^8.0.0

When I am trying to build my app for iOS device, 'pod install' command fails with description:
```CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In Podfile:
    firebase_crashlytics (from `.symlinks/plugins/firebase_crashlytics/ios`) was resolved to 2.0.4, which depends on
      Firebase/Crashlytics (= 8.0.0) was resolved to 8.0.0, which depends on
        FirebaseCrashlytics (~> 8.0.0) was resolved to 8.0.0, which depends on
          GoogleDataTransport (~> 9.0)

    google_ml_vision (from `.symlinks/plugins/google_ml_vision/ios`) was resolved to 0.0.4-2, which depends on
      GoogleMLKit/BarcodeScanning (~> 2.1.0) was resolved to 2.1.0, which depends on
        GoogleMLKit/MLKitCore (= 2.1.0) was resolved to 2.1.0, which depends on
          MLKitCommon (~> 2.1.0) was resolved to 2.1.0, which depends on
            GoogleDataTransport (~> 8.0)`

Could you help me with some information about workarounds or fix this issue?

**Comment by bharat-biradar** [comment]
@Nickkorol Refer to this issue #27 they also had the same problem.

**Comment by Nickkorol** [comment]
BTW, even if I remove all Firebase dependencies, `pod install` finishes with error `The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (GoogleUtilitiesComponents)`

**Comment by fbernaly** [comment]
Closing this issue, it is a known issue, and lets move the conversation to issue https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/27
