### ISSUE TITLE
Sign is canceled when Pod update is performed.

### ISSUE THREAD

**Issue by ttb-inc** [bharat-biradar/Google-Ml-Kit-plugin#341]
After updating Xcode to the latest,
Sign is canceled when Pod update is performed.

Xcode Version 14.0 (14A309)

```
Could not build the precompiled application for the device.
Error (Xcode): Signing for "MLKitTextRecognitionDevanagari-DevanagariOCRResources" requires a development team. Select a development team in the Signing & Capabilities editor.

Error (Xcode): Signing for "MLKitTextRecognition-LatinOCRResources" requires a development team. Select a development team in the Signing & Capabilities editor.

Error (Xcode): Signing for "MLKitTextRecognitionKorean-KoreanOCRResources" requires a development team. Select a development team in the Signing & Capabilities editor.

Error (Xcode): Signing for "MLKitTextRecognitionJapanese-JapaneseOCRResources" requires a development team. Select a development team in the Signing & Capabilities editor.

Error (Xcode): Signing for "Mute-Mute" requires a development team. Select a development team in the Signing & Capabilities editor.

Error (Xcode): Signing for "MLKitTextRecognitionChinese-ChineseOCRResources" requires a development team. Select a development team in the Signing & Capabilities editor.
```

Thank you.

**Comment by florianhenonin** [comment]
Use this in Podfile :
`post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings["DEVELOPMENT_TEAM"] = "FNB26M6BKR"
    end
  end
end
`

**Comment by ttb-inc** [comment]
> 

It's resolved.
Thank you

**Comment by ttb-inc** [comment]
> Use this in Podfile :
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>     target.build_configurations.each do |config|
>       config.build_settings["DEVELOPMENT_TEAM"] = "TEAM ID"
>     end
>   end
> end
> ```

It's resolved.
Thank you

**Comment by yankai3306** [comment]
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
    flutter_additional_ios_build_settings(target)
  end
end

**Comment by yankai3306** [comment]
**Use this in Podfile :**

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
```
