### ISSUE TITLE
There seems to be a problem with the library uploaded to pub.get. Related with #32 Issues

### ISSUE THREAD

**Issue by Sunggu** [bharat-biradar/Google-Ml-Kit-plugin#35]
Hello! 
First of all, I used a translator because I wasn't familiar with English.

This problem seems to be related to number 32.
The version is the same as 0.4.0, but the source received after pub get and the source in the github repository are different.

**Comment by bharat-biradar** [comment]
@Sunggu It is because the latest changes made have not yet been published pub.dev.

**Comment by Sunggu** [comment]
I understand. Thank you! 
When will update that changes?

**Comment by fbernaly** [comment]
@Sunggu : we published 0.5.0 today, you are good to go.
