### ISSUE TITLE
Cannot run on iOS

### ISSUE THREAD

**Issue by nashirdrabi** [bharat-biradar/Google-Ml-Kit-plugin#355]
I cannot do pod install as I am receiving this error 

[!] CocoaPods could not find compatible versions for pod "GoogleMLKit/MLKitCore":
  In Podfile:
    google_mlkit_face_detection (from `.symlinks/plugins/google_mlkit_face_detection/ios`) was resolved to 0.4.0, which depends on
      GoogleMLKit/FaceDetection (~> 3.1.0) was resolved to 3.1.0, which depends on
        GoogleMLKit/MLKitCore (= 3.1.0)
    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 0.0.1, which depends on
      GoogleMLKit/BarcodeScanning (~> 2.6.0) was resolved to 2.6.0, which depends on
        GoogleMLKit/MLKitCore (= 2.6.0)
CocoaPods could not find compatible versions for pod "MLKitVision":
  In Podfile:
    google_mlkit_commons (from `.symlinks/plugins/google_mlkit_commons/ios`) was resolved to 0.2.0, which depends on
      MLKitVision
    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 0.0.1, which depends on
      GoogleMLKit/BarcodeScanning (~> 2.6.0) was resolved to 2.6.0, which depends on
        MLKitBarcodeScanning (~> 1.7.0) was resolved to 1.7.0, which depends on
          MLKitVision (~> 3.0)

**Comment by antoniopetricc** [comment]
same problem

**Comment by fbernaly** [comment]
It seems this is not related to #357 . 

@nashirdrabi : From what you shared you are using 2 packages that in iOS they use different pod versions.
**mobile_scanner**  and our plugin  both use **GoogleMLKit/BarcodeScanning** but in a previous version they were using different versions.

You need to run `flutter pub upgrade` and resolve the specific dependencies of your project.

If you are able to use the latest version from mobile_scanner and ours, both are now using the same GoogleMLKit/BarcodeScanning:

theirs: https://github.com/juliansteenbakker/mobile_scanner/blob/master/ios/mobile_scanner.podspec

ours: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_mlkit_barcode_scanning/ios/google_mlkit_barcode_scanning.podspec


Also consider this: why are you using both? mobile_scanner and ours do the same, pick one of them and that will also resolve your dependencies issue.

Good luck.

**Comment by fbernaly** [comment]
Also look at: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/364
