### ISSUE TITLE
Error: 'Rect' isn't a type - google_mlkit_face_detection

### ISSUE THREAD

**Issue by Imesh7** [bharat-biradar/Google-Ml-Kit-plugin#363]
when switch into google_mlkit_face_detection version 0.4.0 to 0.5.0.
I got a error.

```
Error: 'Rect' isn't a type.
../…/src/face_detector.dart:103
  final Rect boundingBox;
        ^^^^
```

`flutter doctor -v`
```
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.19043.2130], locale en-US)
    • Flutter version 3.0.4 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (4 months ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2
```

I found a solution, upgrade **flutter verion to 3.3.7** now it works for this version.

**Comment by mustafiz012** [comment]
I'm facing the same issue.

**Comment by Furqan978** [comment]
just add the below line in **google_mlkit_text_recognition-0.5.0/lib/src/text_recognizer.dart**
`import 'dart:ui';`

**Comment by alberto-cappellina** [comment]
same here! it's not possible  to  add the text_reconizer.dart 'import dart:ui' because it's a library and even tho i can edit on my machine, on my CI system it's not possible

**Comment by fbernaly** [comment]
Send a PR with those changes and I will review and approve

**Comment by Rahul-K-Jha** [comment]
i got the same issue as above in the google_mlkit_object_detection package

**Comment by fbernaly** [comment]
@Rahul-K-Jha : send a PR with a similar fix as in https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/401.
