### ISSUE TITLE
Unable to compile for iOS due to MLKit lib conflict

### ISSUE THREAD

**Issue by psatler** [bharat-biradar/Google-Ml-Kit-plugin#364]
Hi, thanks for the efforts on providing such packages for the community. It helps a lot!

Below is the issue I'm facing currently with some of your plugins and another one that I'm using.

I'm using the [mobile scanner](https://pub.dev/packages/mobile_scanner) package, and both [TextRecognition](https://pub.dev/packages/google_mlkit_text_recognition) and [translation](https://pub.dev/packages/google_mlkit_translation) packages.

When trying to compile the project for iOS, I'm facing the following problem:

```
[!] CocoaPods could not find compatible versions for pod "GoogleMLKit/MLKitCore":
  In Podfile:
    google_mlkit_text_recognition (from `.symlinks/plugins/google_mlkit_text_recognition/ios`) was resolved to 0.5.0, which depends on
      GoogleMLKit/TextRecognition (~> 3.2.0) was resolved to 3.2.0, which depends on
        GoogleMLKit/MLKitCore (= 3.2.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 0.0.1, which depends on
      GoogleMLKit/BarcodeScanning (~> 2.6.0) was resolved to 2.6.0, which depends on
        GoogleMLKit/MLKitCore (= 2.6.0)
  ```
  
 The Mobile Scanner package also uses MLKit and its dependencies are getting conflicts with the ones of the MLKit plugin. I also noticed this issue when using version of `0.4.0` of these plugins. 
  
For now, I downgraded the dependencies to version `0.3.0` and I was able to compile successfully. Though, that is not the optimal solution for this.

```
google_mlkit_translation: ^0.3.0
google_mlkit_text_recognition: ^0.3.0
```

PS: One thing I noticed as well when looking at this [commit](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/commit/f28b63bd61b2c6592f5dabea9eb0ecc184e03545#diff-b39001a1a572ab1a4055cdd941ed0d3b034e3d998c098148c4fc8b5319c96102R13) is that you added an optional way to add new language packages. Though, by looking at the commit, it seems that the pod `GoogleMLKit/TextRecognitionChinese` was left there uncommented so maybe that is the reason of the pod versions conflict? I haven't had time to fork and check this myself yet, but I decided to open this issue already in case you can spot that easier than me.

**Comment by Kevinpahlevi** [comment]
im facing this issue too, any update for this problem ?

**Comment by psatler** [comment]
Hi,
I noticed that [mobile_scanner](https://pub.dev/packages/mobile_scanner) got updated recently and because of that, I gave another go of using the latest dependencies of both mobile_scanner and the ML Kits ones I mentioned above ([TextRecognition](https://pub.dev/packages/google_mlkit_text_recognition) and [translation](https://pub.dev/packages/google_mlkit_translation)). Just by upgrading those I got my conflict issue solved. 

So, for me, the dependencies used and their versions, were: 

```
mobile_scanner: ^2.1.0
...
google_mlkit_translation: ^0.5.0
google_mlkit_text_recognition: ^0.5.0
```

So, I will close this issue for now.
