### ISSUE TITLE
Unable to Build due to compatibility relating to Firebase Auth

### ISSUE THREAD

**Issue by LarryAlexander** [bharat-biradar/Google-Ml-Kit-plugin#368]
I'm using flutter to create an application.
I'm unable to build or perform a pod install whenever I try to use the Google Ml Kit dependencies. 
Dependency : google_mlkit_barcode_scanning: ^0.5.0

Notes: This error only appears when using the Firebase Auth dependency. I want to utilize the Qr code scanning feature!

Error:    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 4.1.3, which depends on
      Firebase/Auth (= 10.2.0) was resolved to 10.2.0, which depends on
        FirebaseAuth (~> 10.2.0) was resolved to 10.2.0, which depends on
          GTMSessionFetcher/Core (< 4.0, >= 2.1)

    google_mlkit_barcode_scanning (from `.symlinks/plugins/google_mlkit_barcode_scanning/ios`) was resolved to 0.5.0, which depends on
      GoogleMLKit/BarcodeScanning (~> 3.2.0) was resolved to 3.2.0, which depends on
        GoogleMLKit/MLKitCore (= 3.2.0) was resolved to 3.2.0, which depends on
          MLKitCommon (~> 8.0.0) was resolved to 8.0.0, which depends on
            GTMSessionFetcher/Core (~> 1.1)

**Comment by emileswain** [comment]
looks like its mentioned here too https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/357
