### ISSUE TITLE
TextDetector doesn't work with hindi language "hi-IN" 

### ISSUE THREAD

**Issue by uttamgupta** [bharat-biradar/Google-Ml-Kit-plugin#38]
It works for image with english text. it says language is undefined.

**Comment by fbernaly** [comment]
Are you talking about the example app or the plugin? The example app only recognizes English, if you need another language you need to:
1. Download the model
2. pass that in the method

**Comment by uttamgupta** [comment]
Thanks for response. I am using  https://pub.dev/packages/google_ml_kit . I am very new in this area, so It would be great if you could tell me where I can find model and which method you are talking about.

**Comment by bharat-biradar** [comment]
@uttamgupta Currently the original google API supports only Latin - based character set, hence it is not being recognized. Look here for more details [link](https://developers.google.com/ml-kit/vision/text-recognition).

**Comment by uttamgupta** [comment]
Looks like google cloud vision api is only option for other than latin based char set.  I hope this standalone google ml kit would support other language too in near future. So I am closing this issue.
