### ISSUE TITLE
Output headEulerAngles (X, Y, Z) are false for FaceDetection 0.5.0

### ISSUE THREAD

**Issue by sohsaid** [bharat-biradar/Google-Ml-Kit-plugin#382]
I've been using GoogleMLKit facedetection 0.3.0 to detect, rotate and crop faces.

Since my recent update to 0.5.0, output headEulerAngles (X, Y, Z) doesn't match with reality so my outputs rotated images are not well inclined.

Please can someone Help me solve this issue ?

**Comment by sohsaid** [comment]
I found that it was not well configure as explained in the docs [here](https://github.com/bharat-biradar/Google-Ml-Kit-plugin), That is where the error was coming from.

I fix it anyway by following carefully instructions related to the plugin

**Comment by rabieHs** [comment]
can you please share your repo I work in a project that needs to crop faces before predicting them I don't have any idea how do that
