### ISSUE TITLE
Why app size increase after add this plugin?

### ISSUE THREAD

**Issue by bhanuka96** [bharat-biradar/Google-Ml-Kit-plugin#39]
Previously we used [firebase_ml_vision](https://pub.dev/packages/firebase_ml_vision) plugin. Now, we remove firebase plugin and use [google_ml_kit](https://pub.dev/packages/google_ml_kit) plugin.

Previously, the app size is 23MB with the firebase_ml_vision plugin.(release mode)

Now, the app size is 75MB with google_ml_kit plugin. (release mode)

**Comment by bharat-biradar** [comment]
@bhanuka96 This is similar issue to #26, please look there for details. I'll be closing this issue now.
