### ISSUE TITLE
No support for lower versions of the iOS, at least iOS version 10

### ISSUE THREAD

**Issue by SebghatYusuf** [bharat-biradar/Google-Ml-Kit-plugin#40]
I'm opening this issue because the [`firebase_ml_vision`](https://pub.dev/packages/firebase_ml_vision) is discontinued and they did provide support for iOS version 10. 
now I need to provide support for iOS 10 as well to be able to run my app on the older iOS phones as well, is it possible to have support for iOS version 10?

**Comment by bharat-biradar** [comment]
@SebghatYusuf The ios version will be decreased to 10 and published in the version 0.5.1, wait for a day at most.

**Comment by fbernaly** [comment]
Fix will be included in 0.5.1 after merging this PR: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/42

**Comment by bharat-biradar** [comment]
@SebghatYusuf `v0.5.1` was published just now.

**Comment by SebghatYusuf** [comment]
@bharat-biradar Thank you
