### ISSUE TITLE
Can ML KIT recognize text in other languages?

### ISSUE THREAD

**Issue by Soliardi-Chyngyz** [bharat-biradar/Google-Ml-Kit-plugin#405]
I need not to identify, but to scan and process information

<img width="473" alt="Снимок экрана 2023-02-06 в 12 54 17" src="https://user-images.githubusercontent.com/66687051/216903233-aa573ca3-094e-4fa2-bf78-4c613d242472.png">
Will Cyrillic, Arabic be added and when? Thanks.

**Comment by fbernaly** [comment]
Hi, thanks for using our plugin. This plugin is a wrapper on top of Google’s official API. We only support what they have in their page: https://developers.google.com/ml-kit/vision/text-recognition/v2/languages

If the language you are looking for is not there, then it is a question for them.
