### ISSUE TITLE
GTMSessionFetcher/Core conflict with firebase for ios

### ISSUE THREAD

**Issue by IMWaqasFarooq** [bharat-biradar/Google-Ml-Kit-plugin#408]
we  not able to use this library with firebase auth in ios flutter , because google ml kit GTMSessionFetcher/Core is not updated .
following issue we are facing on ios while installing pods

[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In snapshot (Podfile.lock):
    GTMSessionFetcher/Core (< 4.0, = 1.7.2, ~> 1.1)

    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 4.2.6, which depends on
      Firebase/Auth (= 10.3.0) was resolved to 10.3.0, which depends on
        FirebaseAuth (~> 10.3.0) was resolved to 10.3.0, which depends on
          GTMSessionFetcher/Core (< 4.0, >= 2.1)

    google_mlkit_commons (from `.symlinks/plugins/google_mlkit_commons/ios`) was resolved to 0.2.0, which depends on
      MLKitVision was resolved to 4.2.0, which depends on
        GTMSessionFetcher/Core (~> 1.1)

**Comment by LakshayDCoder** [comment]
Are there any alternatives we can use for detecting faces in images for the time being?

**Comment by baraghiffari** [comment]
I face this similiar issue when i want to use Ink Recognizer, there's a temporary solution that I found yesterday : https://issuetracker.google.com/issues/254418199#comment48

**Comment by LakshayDCoder** [comment]
> I face this similiar issue when i want to use Ink Recognizer, there's a temporary solution that I found yesterday : https://issuetracker.google.com/issues/254418199#comment48

This is working as of now for the time being. Thanks

**Comment by saih3** [comment]
is there a permanent solution?

**Comment by LakshayDCoder** [comment]
> 

I hope it's not. I implemented it in our application yesterday and it is working completely fine. Can't say if it will break in the future, maybe.

**Comment by baraghiffari** [comment]
This issue comes from Google itself, we'll have to wait for permanent fix. They said that it's scheduled at mid of March (https://issuetracker.google.com/issues/254418199#comment156), and i think it shouldn't break stuff we already build after they fix it, hopefully.

**Comment by fbernaly** [comment]
thanks @baraghiffari

**Comment by babang1da** [comment]
Have same

**Comment by mminhlequang** [comment]
.
