### ISSUE TITLE
Error on pod install after add google ml kit plugin on project.

### ISSUE THREAD

**Issue by AlexOliveira123** [bharat-biradar/Google-Ml-Kit-plugin#41]
Anyone else with this error when adding the google_ml_kit to the project?

[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (GoogleUtilitiesComponents)

**Comment by Tomas-TravelUnion** [comment]
i have the same error here...
the "solution" that works for some is to comment use_frameworks! in Podfile
but this does not work for me, i cannot statically link my project, way too big and complicated... any way to solve it?

**Comment by bharat-biradar** [comment]
@AlexOliveira123 @Tomas-TravelUnion this might be issue similar to #27. Take a look.

**Comment by Tomas-TravelUnion** [comment]
> @AlexOliveira123 @Tomas-TravelUnion this might be issue similar to #27. Take a look.

Unfortunately no, that one is in dependency hell category and i solved it like everyone one, by selecting proper lower versions of involved packages. This one prevents pod install with use_frameworks! in Podfile. The key words in error are **statically linked binaries: (GoogleUtilitiesComponents)**

**Comment by Tomas-TravelUnion** [comment]
so... i found the solution for this problem you can easily do it, just one line of code to add to google_ml_kit.podspec file:
  s.static_framework = true

**Comment by fbernaly** [comment]
Thanks @Tomas-TravelUnion , we will include that in the next version

**Comment by fbernaly** [comment]
Fix will be included in 0.5.1 after merging this PR: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/42

**Comment by bharat-biradar** [comment]
@Tomas-TravelUnion @AlexOliveira123 v0.5.1 was just published, I think the issue must be solved now.

**Comment by AlexOliveira123** [comment]
The problem was solved, thank you!!!! @bharat-biradar
