### ISSUE TITLE
Build new Pub.Dev Packages 

### ISSUE THREAD

**Issue by FantaMagier** [bharat-biradar/Google-Ml-Kit-plugin#431]
It is possible to get the new commit https://github.com/bharat-biradar/Google-Ml-Kit-plugin/commit/da9be5182fba024c181665930900071bf7f40b3b to Pub.Dev because I need the new ML Kit Version.

Thanks and Cheers

**Comment by fbernaly** [comment]
on it

**Comment by fbernaly** [comment]
Done: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/432
