### ISSUE TITLE
Draw rectangle around detected text from image

### ISSUE THREAD

**Issue by SebghatYusuf** [bharat-biradar/Google-Ml-Kit-plugin#46]
I've been using [`firebase_ml_vision`](https://pub.dev/packages/firebase_ml_vision) to do OCR, I used a custom painter to draw a rectangle around the detected text using [TextContainer](https://pub.dev/documentation/firebase_ml_vision/latest/firebase_ml_vision/TextContainer-class.html) class which represents dimensions of recognized text in an image. Unfortunately, I can't find any class to be able to get the bounding boxes of detected text.
any feedback would be appreciated.

**Comment by fbernaly** [comment]
@SebghatYusuf : Did you look at the example app? The [example app](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/example) is using the `camera` plugin to process the image like this: 

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/example/lib/VisionDetectorViews/text_detector_view.dart#L35-L53

The `RecognisedText` is passed to `TextDetectorPainter` and then to a `CustomPaint` to draw the rectangles. Look at the details of that implementation here: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/example/lib/VisionDetectorViews/painters/text_detector_painter.dart

I have tested this in multiple devices, both in Android and iOS and so far so good.

**Comment by SebghatYusuf** [comment]
@fbernaly 
Thanks for clearifying that, I haven't looked to the example app. 
I will look forward with the example app.
