### ISSUE TITLE
Unbale to found any helping material Live Camera with Pose Detection API using flutter dart.

### ISSUE THREAD

**Issue by marslannasr7koncepts** [bharat-biradar/Google-Ml-Kit-plugin#5]
I am facing an issue not found any example where Live Camera implemented with Pose Detection API using flutter dart.

Please let me know anyone using it or found any helping material related this i am just found Pose Detection using static image but not using Live Camera..

Thanks

**Comment by bharat-biradar** [comment]
Hi @marslannasr7koncepts thanks for opening an issue.

I had written the example for live detection on new-apis branch but I'm not getting proper results while using the camera stream. So for time being I have commmented out that part. If I have any further developments I will update you. For time being you may refer to this [example](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/6247fd6c7a49efb08d6dcb6b0d2f51bbc11ea5ad/example/lib/DetectorViews/camera_pose_detector.dart#L122) which covers live pose detection.   

Thanks.

**Comment by marslannasr7koncepts** [comment]
Thanks @bharat-biradar for response I have a Question did it work when Camera is streaming no need to click on button just show Pose Detection using Live Camera not depend on any Button Click etc.

And what type of issue your facing and how much time it take to fix?

Thanks

**Comment by bharat-biradar** [comment]
@marslannasr7koncepts the problem is occurring with live stream. I have tried all the methods possible but still when it comes to live stream detection no poses are being detected from the camera stream. It has been nearly a week still I haven't found a solution, so I cant say for sure for now when issue will be resolved.

Sorry for the inconvenience caused.

**Comment by malithkuruppu** [comment]
@bharat-biradar do you have the same issue when you are trying to perform live text recognition using the phone camera?

**Comment by bharat-biradar** [comment]
@malithkuruppu I haven't tried live text detection yet, I will get back to you once I have tried it.

**Comment by malithkuruppu** [comment]
@bharat-biradar is there any solution to the above problem?

**Comment by bharat-biradar** [comment]
@malithkuruppu Sorry but I have not found any solution, I was thinking of filing an issue on the official google ml kit api. Maybe there I can find why this problem is happening.

**Comment by malithkuruppu** [comment]
@bharat-biradar appreciate if you can open an issue! Please leave the link to the issue in this thread.

**Comment by bharat-biradar** [comment]
@malithkuruppu  [link](https://issuetracker.google.com/issues/183328530) for the issue opened in Issue Tracker.
Also I asked a question on [stackoverflow](https://stackoverflow.com/questions/66517551/send-image-stream-byte-data-flutter-to-native-android) if this helps

**Comment by malithkuruppu** [comment]
@bharat-biradar will you be updating the code in this repo for live camera text and barcode recognition?

**Comment by malithkuruppu** [comment]
@bharat-biradar also what is the issue that needs to be addressed at this moment for the live camera text and barcode recognition to work?

**Comment by bharat-biradar** [comment]
@malithkuruppu The issue is related to rotation degree that we have to pass as a parameter while creating the input image. May be due to wrong calculation of rotation degree neither text nor poses are being detected.

**Comment by malithkuruppu** [comment]
@bharat-biradar  the issue I am having is that I am unable to use live camera preview for text and barcode detection using ML kit in a Flutter app. Do you have a solution for this problem?

**Comment by bharat-biradar** [comment]
@malithkuruppu Yes I have solution to display live preview but don't you want to use the camera stream data to be processed.

**Comment by malithkuruppu** [comment]
@bharat-biradar I am not quite sure how about to use live camera preview. As you said, will need camera stream data for processing with ML kit. 

So the current issue in the solution you have is that when the device is tilted, the app stops working?

Does it work if the rotation of the screen is locked?

**Comment by bharat-biradar** [comment]
@malithkuruppu I'll share you a gist for using live camera preview. But it's not a problem with the plugin itself.

**Comment by malithkuruppu** [comment]
@bharat-biradar Please correct me if I am wrong:
1. The ML Kit is working with Kotlin implementation with live camera
2.  The ML kit is working with Flutter implementation with static images
3. You are getting camera stream data for processing with ML kit.
4. The issue is ML kit is not working with Flutter implementation with live camera, because the rotation degree of the camera is not properly calculated. Therefore, the text detection is not working.

**Comment by bharat-biradar** [comment]
@malithkuruppu Yes that's exactly the problem

**Comment by bharat-biradar** [comment]
I have updated regarding the same in readme

**Comment by bharat-biradar** [comment]
@malithkuruppu  Currently yes, this plugin is not officially from google and they mentioned in this [issue](https://issuetracker.google.com/issues/171338906) that they are not thinking of creating a flutter plugin currently.

**Comment by malithkuruppu** [comment]
@bharat-biradar do you have a branch that you are working on specifically for this issue?

**Comment by bharat-biradar** [comment]
@malithkuruppu Except for master on both the branches I'm trying trial and error. You can see them for reference. Currently, I'm adding support for a new API and not focussing on this problem as I am not having any developments.

**Comment by fbernaly** [comment]
@malithkuruppu , @marslannasr7koncepts : pull the latest code from master and run the example app, we added support for the camera plugin
