### ISSUE TITLE
InputImageData is null

### ISSUE THREAD

**Issue by spedalilama** [bharat-biradar/Google-Ml-Kit-plugin#53]
When running the example on a iOS device and choosing an image from the gallery the InputImageData.size and InputImageData.imageRotation is always null.

**Comment by bharat-biradar** [comment]
@spedalilama `InputImageData` is null because it is not necessary to provide the image data when creating an `InputImage` from a file (Note `InputImageData` is nullable) as in the native part everything is handled by the original `google ml kit` API itself.
Hope this answers your query.

**Comment by spedalilama** [comment]
Yes, but if these values are null then the painter to highlight the found text doesn't get used:

if (inputImage.inputImageData?.size != null &&
        inputImage.inputImageData?.imageRotation != null) {
      final painter = TextDetectorPainter(
          recognisedText,
          inputImage.inputImageData!.size,
          inputImage.inputImageData!.imageRotation);
      customPaint = CustomPaint(painter: painter);
    } else {
      customPaint = null;
    }

**Comment by fbernaly** [comment]
@spedalilama: you are right, in the example app, the painter is not working for images from the gallery  because both rotation and size are null. 
However the ML kit API is working for production. Example app is not production code.
Feel free to propose a fix and send a PR. Contributions are always welcome.

**Comment by realArafatBen** [comment]
Currently, I am stuck here... how can I get the inputImageData from a file. 
All that is been returned is null
