### ISSUE TITLE
CocoaPods could not find compatible versions for pod "GoogleDataTransport":

### ISSUE THREAD

**Issue by slaniado** [bharat-biradar/Google-Ml-Kit-plugin#59]
This is my flutter doctor output

[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale es-419)
    • Flutter version 2.2.1 at /Users/slaniado/desarrollo/flutter
    • Framework revision 02c026b03c (13 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/slaniado/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • iPhone SE (2nd generation) (mobile) • F25E6952-6730-4C74-8AB8-713F1F4F5759 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 91.0.4472.77

• No issues found!

` flutter run `

return this Error: 
CocoaPods's specs repository is too out-of-date to satisfy dependencies.

`pod install`

[!] CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In snapshot (Podfile.lock):
    GoogleDataTransport (= 9.0.1, ~> 9.0)

  In Podfile:
    firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 1.2.1, which depends on
      Firebase/CoreOnly (= 8.0.0) was resolved to 8.0.0, which depends on
        FirebaseCore (= 8.0.0) was resolved to 8.0.0, which depends on
          FirebaseCoreDiagnostics (~> 8.0) was resolved to 8.1.0, which depends on
            GoogleDataTransport (~> 9.0)

    google_ml_kit (from `.symlinks/plugins/google_ml_kit/ios`) was resolved to 0.6.0, which depends on
      GoogleMLKit/PoseDetectionAccurate was resolved to 0.64.0, which depends on
        GoogleMLKit/MLKitCore (= 0.64.0) was resolved to 0.64.0, which depends on
          MLKitCommon (~> 0.64.0) was resolved to 0.64.0, which depends on
            GoogleDataTransport (~> 7.0)

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `GoogleDataTransport` inside your development pod `google_ml_kit`.
   You should run `pod update GoogleDataTransport` to apply changes you've made.

I tried every single post to try to clean and reinstall the pods and the same outcome.

**Comment by fbernaly** [comment]
Thanks for reporting, this is a know issue mentioned in the README. Refer to this issue https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/27.
