### ISSUE TITLE
How To Exclude Asset for App Size?

### ISSUE THREAD

**Issue by yusriltakeuchi** [bharat-biradar/Google-Ml-Kit-plugin#65]
When i use this library, the application size is too big, i want to ask how to exclude an assets when building release mode?
For example i just want to use Text Recognition only.

Thank you if you want to help my work easy.

**Comment by bharat-biradar** [comment]
@yusriltakeuchi Sorry for the late reply. Refer to #26 for this issue. You can find a work around there.

**Comment by yusriltakeuchi** [comment]
> @yusriltakeuchi Sorry for the late reply. Refer to #26 for this issue. You can find a work around there.

That's just example to reduce in android, how if we want to reduce in iOS?

**Comment by yasht01** [comment]
Is there a way to do this on iOS?
