### ISSUE TITLE
No way to pass image orientation

### ISSUE THREAD

**Issue by pashtetbezd** [bharat-biradar/Google-Ml-Kit-plugin#67]
Im trying to detect faces on image created by Camera plugin in frontal camera
scanner return empty faces list for portrait orientation images, but it works correctly when i turn device in landscape

i have tried to use InputImage.fromBytes with inputImageData but there are required fileds 
required this.size,
required this.imageRotation,
required this.inputImageFormat,
required this.planeData

how can i say faceDetector.processImage to use actual orientation?

**Comment by pashtetbezd** [comment]
The problem was that in some devices the exif data shows picture in landscape mode when they're actually in portrait.
I solve it by flutter_exif_rotation plugin

**Comment by pdivita** [comment]
> 
> 
> The problem was that in some devices the exif data shows picture in landscape mode when they're actually in portrait.
> I solve it by flutter_exif_rotation plugin

do you have an example on how to fix?
