### ISSUE TITLE
QR code scanning errors

### ISSUE THREAD

**Issue by paj-co** [bharat-biradar/Google-Ml-Kit-plugin#71]
Hello,

I have a problem with two kinds of QR codes:
1. QR code with a company address info
![qr-address-info](https://user-images.githubusercontent.com/44299686/123260525-f3f61980-d4f5-11eb-9efe-7ec45d183155.png)
2. QR code with contact info (ex. made up contact info: John Smith +48 788 233 144 - generated by contacts app on my Samsung phone)
![qr-john-smith](https://user-images.githubusercontent.com/44299686/123261101-a1692d00-d4f6-11eb-9b8f-1d11aee6e4de.jpg)

---

You can reproduce both errors using example app which comes with google_ml_kit 0.6.0.

When I scan QR code with company address info my app shuts down with console message:
```
D/AndroidRuntime(22673): Shutting down VM
E/AndroidRuntime(22673): FATAL EXCEPTION: main
E/AndroidRuntime(22673): Process: com.b.biradar.google_ml_kit_example, PID: 22673
E/AndroidRuntime(22673): java.lang.IllegalArgumentException: Unsupported value: [Ljava.lang.String;@14d337e
E/AndroidRuntime(22673): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:276)
E/AndroidRuntime(22673): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:273)
E/AndroidRuntime(22673): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:265)
E/AndroidRuntime(22673): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:273)
E/AndroidRuntime(22673): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:265)
E/AndroidRuntime(22673): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:59)
E/AndroidRuntime(22673): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime(22673): 	at com.b.biradar.google_ml_kit.vision.BarcodeDetector$2.onSuccess(BarcodeDetector.java:207)
E/AndroidRuntime(22673): 	at com.b.biradar.google_ml_kit.vision.BarcodeDetector$2.onSuccess(BarcodeDetector.java:85)
E/AndroidRuntime(22673): 	at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@17.2.1:1)
E/AndroidRuntime(22673): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(22673): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(22673): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(22673): 	at android.app.ActivityThread.main(ActivityThread.java:8512)
E/AndroidRuntime(22673): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22673): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(22673): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
```
When I scan QR code with contact info I get this message in console:
```
E/flutter (18475): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'MappedListIterable<dynamic, BarcodeAddress>' is not a subtype of type 'List<BarcodeAddress>?'
E/flutter (18475): #0      new BarcodeContactInfo._ (package:google_ml_kit/src/vision/barcode_scanner.dart:425:26)
E/flutter (18475): #1      new Barcode._fromMap (package:google_ml_kit/src/vision/barcode_scanner.dart:169:52)
E/flutter (18475): #2      BarcodeScanner.processImage (package:google_ml_kit/src/vision/barcode_scanner.dart:28:32)
E/flutter (18475): <asynchronous suspension>
E/flutter (18475): #3      _BarcodeScannerViewState.processImage (package:google_ml_kit_example/VisionDetectorViews/barcode_scanner_view.dart:37:22)
E/flutter (18475): <asynchronous suspension>
```
I would appreciate fixing these errors.

**Comment by bharat-biradar** [comment]
@paj-co Did you try this with the latest code from the master branch. I think the issue was fixed for `Android` but may take some time for the IOS part.

**Comment by paj-co** [comment]
@bharat-biradar thanks for replay. I'm currently on Flutter 2.0.4. I will switch to newest Flutter version and run app again.

**Comment by bharat-biradar** [comment]
@paj-co Sorry for the confusion but from latest code I meant code from master branch of the plugin repository. We have updated the plugin but still not published it on pub.dev.

**Comment by paj-co** [comment]
@bharat-biradar my bad ;) Thanks, for quick replay 😄

**Comment by paj-co** [comment]
@bharat-biradar I checked master branch with my app by linking google_ml_kit dependency directly to github:
```
  google_ml_kit:
    git:
      url: https://github.com/bharat-biradar/Google-Ml-Kit-plugin
```
and everything works fine, thank you :) 

However, when I have downloaded zip file from master branch to check example app, apk would not compile due to `File google-services.json is missing. The Google Services Plugin cannot function without it. ` error.

**Comment by bharat-biradar** [comment]
@paj-co Yes, I had excluded the `google-services.json` file as it belonged to a different personal project. Replace it with your json file and it should work.

**Comment by fbernaly** [comment]
@paj-co: this PR fixes the issues for iOS: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/pull/79

**Comment by paj-co** [comment]
@fbernaly it works, thank you! :)
