### ISSUE TITLE
crop InputImage

### ISSUE THREAD

**Issue by hesmnyn** [bharat-biradar/Google-Ml-Kit-plugin#74]
could you please help me to crop object of InputImage when it has imageType of bytes
i want textDetector.processImage(inputImage) function to only recognize a part of my camera input that user see

**Comment by fbernaly** [comment]
I do know how to crop the image, just make sure that your image follows the Input Image guidelines:
* https://developers.google.com/ml-kit/vision/text-recognition/android#input-image-guidelines
* https://developers.google.com/ml-kit/vision/text-recognition/ios#input-image-guidelines
