### ISSUE TITLE
Thermal problem on iPhone

### ISSUE THREAD

**Issue by paj-co** [bharat-biradar/Google-Ml-Kit-plugin#75]
Hi,

Recently I've got iPhone 6 (2014 model) with iOS 12.5.4 for app testing. So, it's quite dated.

I have a thermal issue when scanning QR codes for a minute or longer. iPhone 6 is getting quite warm. However my Samsung A21s (2020 model) is getting just a little warm.

I used both latest (0.6.0) version from pub.dev and latest master branch from GitHub.

When using only camera preview, without image stream and barcode detection, iPhone 6 gets a little bit warm, but with barcode detection it's quite warm.

I wander, is there any thing that could be done with this.  Have you tested this package on newer iPhone device? Do you know what is the reason?
Could it be the outdated iPhone processor and constantly processing image stream is just to heavy a task?
Or the way in which Flutter talks with native code?

Thanks in advance :)

**Comment by fbernaly** [comment]
Hi @paj-co : I have been testing barcode scanning with iPhone11, iOS 14 and iPhone ^s Plus, iOS14 no issues at all, phones not getting warm.

**Comment by paj-co** [comment]
@fbernaly thank you for clarifying :)
