### ISSUE TITLE
Reduce app size by using unbundled models

### ISSUE THREAD

**Issue by wazini-john** [bharat-biradar/Google-Ml-Kit-plugin#76]
Can one use unbundled models as explained [`here`](https://developers.google.com/ml-kit/vision/face-detection/android) ?

**Comment by wazini-john** [comment]
@bharat-biradar ... Can it be done ?

**Comment by bharat-biradar** [comment]
@wazini-john Sorry I had not noticed. I don't think ut is possible, we would need an actual application I suppose. But I'll check once and let you know. Thank you.

**Comment by wazini-john** [comment]
I think loading the model from Google Play Services would lead to smaller bundles

**Comment by wazini-john** [comment]
Was Running the build without specifying the project folder ie `flutter build apk --obfuscate --split-debug-info=./PROJECTNAME/build/symbols`

**Comment by bharat-biradar** [comment]
@wazini-john The plugin works with unbundled models but not all API's support unbundled models we have only 3 API's working with unbundled models. But there was a decrease in the size of apk. @fbernaly Should we change the available models to unbundled ones?

**Comment by wazini-john** [comment]
What API's ? 
And how do we remove the overhead files while getting the same functionalities?

**Comment by bharat-biradar** [comment]
@wazini-john The details have been updated in the `readme`. Can I close this issue or do you have any other queries?

**Comment by wazini-john** [comment]
sure.. thanks

**Comment by wazini-john** [comment]
How to clean up any bundles built up in the app ? Or what lines do we add to prevent any kind of bundling?

**Comment by wazini-john** [comment]
@bharat-biradar

**Comment by bharat-biradar** [comment]
@wazini-john You can't prevent bundling but you can exclude other assets such pose detection model whose size nearly 24 mb. For information regarding this refer #26 .

**Comment by wazini-john** [comment]
What assets do we exclude all together ? @bharat-biradar

**Comment by bharat-biradar** [comment]
@wazini-john Assets that you do not need. For example, if you are working on `face detection`, you won't be needing model for `pose detection` or `hobbes.tflite` etc... Exclude them as shown [here](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/26#issuecomment-872267543). At the end analyze your `apk`, if there assets that are not being used, ignore those assets.

**Comment by wazini-john** [comment]
I'm using face detection in my app and since we'll be using Google Play face API. 
1. Can we exclude all assets generated ?
2.  Does using Google Play APIs affect iOS?

**Comment by bharat-biradar** [comment]
>2. Does using Google Play APIs affect iOS?
No, it does not.
>1. Can we exclude all assets generated ?
You cannot exclude all the generated assets, because some of the assets are may be generated by other plugins or flutter itself. Exclude assets that are used by `google_ml_kit` plugin only.
![image](https://user-images.githubusercontent.com/62872048/125408583-b1c74600-e3d8-11eb-9799-530c9a314881.png)

If you see in this image `mlkit_pose`, `hobbes.tflite`, `object_labeler` etc... are used by ml kit whereas `flutter_assets` are used for different purpose so do not, exclude them.

**Comment by wazini-john** [comment]
Sorry to disturb but do you have a list of `all assets` generated by the package ?

**Comment by bharat-biradar** [comment]
The above screenshot contains the list of assets for the latest version of `example app`. Out of these `mlkit_pose`, `hobbes.tflite`, `object_labeler.tflite`, `mlkit_oft_default_classifier`, `mlkit_odt_lacalizer` are generated by plugin.

**Comment by wazini-john** [comment]
Final question ... Can I exclude `models` in `assets` ?

**Comment by bharat-biradar** [comment]
What models?

**Comment by wazini-john** [comment]
The one below `hobbes` [here](https://user-images.githubusercontent.com/78900743/124097350-2b1f7a00-da64-11eb-9199-7ef51f39d058.png)

**Comment by bharat-biradar** [comment]
Yes you can. Try excluding them, if they interfere with working you can always revert back 😀.

**Comment by wazini-john** [comment]
Removing them breaks the app.
Thanks
