### ISSUE TITLE
MissingPluginException No implementation found for method listen on channel

### ISSUE THREAD

**Issue by roticagas** [bharat-biradar/Google-Ml-Kit-plugin#8]
google_ml_kit: ^0.1.0
  
`      barcodeScanner = GoogleMlKit.instance.barcodeScanner();
      final result = await barcodeScanner.processImage(inputImageOf(image));`

on android everything work fine. but iOS not working. with error 

MissingPluginException No implementation found for method listen on channel google_ml_kit

**Comment by bharat-biradar** [comment]
@roticagas thanks for opening the issue. This error occurred because the plugin doesn't support IOS implementation yet. It is only for Android as of now. Sorry for the inconvenience caused.

**Comment by florisdipt** [comment]
This is unacceptable on Google's part because https://pub.dev/packages/firebase_ml_vision did have compatibility with iOS
and they suggest migrating to this package.
Thank you for clarifying, please also put it in the docs.

**Comment by bharat-biradar** [comment]
@florisdipt I know this is a problem but I am not enough experienced with IOS development yet but people are showing more interest in the project so I think support for IOS will be added with time.
It is already mentioned in the first line of docs that this plugin is for android and also the pub.dev page indicates supported platforms. If you still think it is not explicit enough please let me know and I will update it.

**Comment by florisdipt** [comment]
> @florisdipt I know this is a problem but I am not enough experienced with IOS development yet but people are showing more interest in the project so I think support for IOS will be added with time.
> It is already mentioned in the first line of docs that this plugin is for android and also the pub.dev page indicates supported platforms. If you still think it is not explicit enough please let me know and I will update it.

Okay, I understand. 
I just pressed command+f search ios and did not find any results. So thats my bad. Have a good day!
For now I'll probably will be reimplementing with Tesseract

**Comment by fbernaly** [comment]
@florisdipt : we added support for iOS for some features, check the README, we will release more features eventually.
