### ISSUE TITLE
When are object detection changes planned to be released to dart pub.

### ISSUE THREAD

**Issue by Kypsis** [bharat-biradar/Google-Ml-Kit-plugin#80]
Apologies in advance for creating an issue for what is basically a question. But still, when are you guys planning on releasing the object detection changes to dart pub (even if rough guestimate)?

**Comment by bharat-biradar** [comment]
@Kypsis Once the `IOS` part id done it will be released.

**Comment by fbernaly** [comment]
@Kypsis : I have been busy with work. I am planning to work on that new feature for iOS next week. But collaborations are always welcome.
