### ISSUE TITLE
Text recognision for non english language

### ISSUE THREAD

**Issue by tokyokamera** [bharat-biradar/Google-Ml-Kit-plugin#81]
Hi,
I am trying to build a Japanese ocr using this plugin.
It is working for english but for Japanese I don't have the luck.
Can you please provide an example to do the same?

Thank you!

**Comment by bharat-biradar** [comment]
@tokyokamera The original API supports recognition only for Latin based scripts, hence I doubt it will work in Japanese. Look [here](https://developers.google.com/ml-kit/vision/text-recognition) for more details.

**Comment by fbernaly** [comment]
Since ML Kit only can recognize text in any Latin-based character set. We are closing this issue.

**Comment by fbernaly** [comment]
We released a new version of [google_ml_kit](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit) in which we have split all the plugins in multiple plugins to avoid removing the models for API you are not using, go to our readme and start using the new plugin you need.

Start using:
https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_text_recognition

More details here:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
