### ISSUE TITLE
Error building to  iOS symbol(s) not found for architecture armv7

### ISSUE THREAD

**Issue by slaniado** [bharat-biradar/Google-Ml-Kit-plugin#82]
Hello
I am getting this error when building to iOS, I am targeting version 10.
I am able to run in the simulator, the issue comes when I run `flutter build ios --release`
I tried all the possible solutions cleaning pods also I deleted the iOS folder and build again.

`flutter doctor -v`
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale es-419)
    • Flutter version 2.2.3 at /Users/desarrollo/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users//Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • iPhone 12 mini (mobile) • 4EE48E4F-99F2-43C1-8FC3-33C64178C442 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

This is the error

Undefined symbols for architecture armv7:
      "_OBJC_CLASS_$_MLKTextRecognizer", referenced from:
          objc-class-ref in google_ml_kit(TextRecognizer.o)
      "_OBJC_CLASS_$_MLKCustomImageLabelerOptions", referenced from:
          objc-class-ref in google_ml_kit(ImageLabeler.o)
      "_OBJC_CLASS_$_MLKImageLabeler", referenced from:
          objc-class-ref in google_ml_kit(ImageLabeler.o)
      "_MLKModelDownloadDidSucceedNotification", referenced from:
          -[DigitalInkRecogniser manageInkModel:result:] in google_ml_kit(DigitalInkRecogniser.o)
          -[DigitalInkRecogniser receiveTestNotification:] in google_ml_kit(DigitalInkRecogniser.o)
      "_OBJC_CLASS_$_MLKModelDownloadConditions", referenced from:
          objc-class-ref in google_ml_kit(DigitalInkRecogniser.o)
      "_OBJC_CLASS_$_MLKInk", referenced from:
          objc-class-ref in google_ml_kit(DigitalInkRecogniser.o)
      "_OBJC_CLASS_$_MLKStrokePoint", referenced from:
          objc-class-ref in google_ml_kit(DigitalInkRecogniser.o)
      "_OBJC_CLASS_$_MLKDigitalInkRecognizer", referenced from:
          objc-class-ref in google_ml_kit(DigitalInkRecogniser.o)
      "_OBJC_CLASS_$_MLKModelManager", referenced from:
          objc-class-ref in google_ml_kit(DigitalInkRecogniser.o)
      "_OBJC_CLASS_$_MLKDigitalInkRecognitionModel", referenced from:
          objc-class-ref in google_ml_kit(DigitalInkRecogniser.o)
      "_OBJC_CLASS_$_MLKDigitalInkRecognitionModelIdentifier", referenced from:
          objc-class-ref in google_ml_kit(DigitalInkRecogniser.o)
      "_MLKFaceLandmarkTypeNoseBase", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_OBJC_CLASS_$_MLKStroke", referenced from:
          objc-class-ref in google_ml_kit(DigitalInkRecogniser.o)
      "_MLKFaceLandmarkTypeMouthLeft", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_MLKFaceLandmarkTypeLeftEar", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_MLKFaceLandmarkTypeRightEar", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_MLKFaceLandmarkTypeMouthBottom", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_MLKFaceLandmarkTypeLeftEye", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_MLKFaceContourTypeUpperLipBottom", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_MLKFaceLandmarkTypeLeftCheek", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_MLKFaceContourTypeNoseBottom", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_MLKFaceContourTypeLowerLipBottom", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_MLKModelDownloadDidFailNotification", referenced from:
          -[DigitalInkRecogniser manageInkModel:result:] in google_ml_kit(DigitalInkRecogniser.o)
          -[DigitalInkRecogniser receiveTestNotification:] in google_ml_kit(DigitalInkRecogniser.o)
      "_MLKFaceContourTypeLeftEyebrowTop", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_MLKFaceContourTypeLowerLipTop", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_MLKFaceContourTypeLeftEyebrowBottom", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_MLKPoseLandmarkTypeLeftThumb", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeRightEar", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeRightIndexFinger", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKFaceContourTypeLeftEye", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_MLKFaceContourTypeFace", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_MLKPoseLandmarkTypeRightWrist", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeMouthRight", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeRightAnkle", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeRightShoulder", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKFaceContourTypeUpperLipTop", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_MLKPoseLandmarkTypeRightToe", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeRightPinkyFinger", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKFaceLandmarkTypeMouthRight", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_OBJC_CLASS_$_MLKFaceDetectorOptions", referenced from:
          objc-class-ref in google_ml_kit(FaceDetector.o)
      "_MLKPoseLandmarkTypeRightKnee", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeRightHip", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKFaceContourTypeRightEye", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_MLKPoseLandmarkTypeLeftKnee", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeRightEye", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeNose", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeRightThumb", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeLeftWrist", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_OBJC_CLASS_$_MLKBarcodeScanner", referenced from:
          objc-class-ref in google_ml_kit(BarcodeScanner.o)
      "_MLKPoseLandmarkTypeLeftToe", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_OBJC_CLASS_$_MLKDigitalInkRecognizerOptions", referenced from:
          objc-class-ref in google_ml_kit(DigitalInkRecogniser.o)
      "_MLKFaceContourTypeRightCheek", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_OBJC_CLASS_$_MLKVisionImage", referenced from:
          objc-class-ref in google_ml_kit(BarcodeScanner.o)
          objc-class-ref in google_ml_kit(PoseDetector.o)
          objc-class-ref in google_ml_kit(FaceDetector.o)
          objc-class-ref in google_ml_kit(ImageLabeler.o)
          objc-class-ref in google_ml_kit(TextRecognizer.o)
          objc-class-ref in google_ml_kit(MLKVisionImage+FlutterPlugin.o)
          __OBJC_$_CATEGORY_MLKVisionImage_$_FlutterPlugin in google_ml_kit(MLKVisionImage+FlutterPlugin.o)
          ...
      "_MLKPoseLandmarkTypeLeftShoulder", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeLeftPinkyFinger", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKFaceContourTypeLeftCheek", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_OBJC_CLASS_$_MLKFaceDetector", referenced from:
          objc-class-ref in google_ml_kit(FaceDetector.o)
      "_MLKPoseLandmarkTypeMouthLeft", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeRightEyeInner", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeLeftIndexFinger", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeLeftEar", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeRightEyeOuter", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_OBJC_CLASS_$_MLKBarcodeScannerOptions", referenced from:
          objc-class-ref in google_ml_kit(BarcodeScanner.o)
      "_MLKPoseLandmarkTypeLeftHip", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeLeftHeel", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeRightElbow", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseDetectorModeSingleImage", referenced from:
          -[PoseDetector handleDetection:result:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeLeftElbow", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_OBJC_CLASS_$_MLKImageLabelerOptions", referenced from:
          objc-class-ref in google_ml_kit(ImageLabeler.o)
      "_MLKFaceContourTypeRightEyebrowTop", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_MLKPoseLandmarkTypeLeftEyeOuter", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_OBJC_CLASS_$_MLKPoseDetectorOptions", referenced from:
          objc-class-ref in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeLeftAnkle", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKFaceContourTypeNoseBridge", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_MLKPoseDetectorModeStream", referenced from:
          -[PoseDetector handleDetection:result:] in google_ml_kit(PoseDetector.o)
      "_MLKFaceLandmarkTypeRightCheek", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_OBJC_CLASS_$_MLKAccuratePoseDetectorOptions", referenced from:
          objc-class-ref in google_ml_kit(PoseDetector.o)
      "_MLKFaceContourTypeRightEyebrowBottom", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_MLKPoseLandmarkTypeRightHeel", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKFaceLandmarkTypeRightEye", referenced from:
          ___39-[FaceDetector handleDetection:result:]_block_invoke in google_ml_kit(FaceDetector.o)
      "_OBJC_CLASS_$_MLKPoseDetector", referenced from:
          objc-class-ref in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeLeftEyeInner", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
      "_MLKPoseLandmarkTypeLeftEye", referenced from:
          -[PoseDetector poseLandmarkTypeToNumber:] in google_ml_kit(PoseDetector.o)
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

....
Showing All Messages
Could not find or use auto-linked library 'stdc++'

Thanks

**Comment by fbernaly** [comment]
@slaniado : the fix is in our [README](https://github.com/bharat-biradar/Google-Ml-Kit-plugin#requirements) and in issue https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/44
In your ymal file pull the code from our master to get the latest code.
