### ISSUE TITLE
Crash on iOS by memory limit

### ISSUE THREAD

**Issue by unger1984** [bharat-biradar/Google-Ml-Kit-plugin#83]
Simple example with only barcode scanner. Crashing on start with error:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=1450 MB, unused=0x0)
```

May be, i can exclude other ml pods, that do not need me?

**Comment by fbernaly** [comment]
are you using the code from master? Could you share more logs? I have been testing the barcode scanner and so far no issues.

**Comment by unger1984** [comment]
Im try use 0.6.0 and master from this repo. Im write small plugin for barcode scanner https://github.com/unger1984/barcode_ml_scanner in android its work fine, but in iOS on IPhone 7 crash. In example folder located code that i cannot run (

**Comment by fbernaly** [comment]
@unger1984 : have you tried our example app? try our example app and let me know if you can reproduce the crash.

**Comment by fbernaly** [comment]
@unger1984 : any update? did you try our example app? can we close it?
