### ISSUE TITLE
Example doesn't work with normal camera view

### ISSUE THREAD

**Issue by thanhbinh84** [bharat-biradar/Google-Ml-Kit-plugin#84]
Steps to reproduce: 
1. Run app on Xiaomi Mi Max, android 7.0 
2. Select Vision/Face detector 
3. The app can detect eye, nose... but the camera screen shrinks
4. Remove row 117 in the camera_view.dart `fit: StackFit.expand,` 
5. Rerun the app 

Actual result: 
- The camera screen ratio is normal but cannot detect and draw detection for eye, nose... 

Expected result: 
- Custom paint should work with any camera view 

![Screenshot_2021-07-08-17](https://user-images.githubusercontent.com/366768/124907297-2c2b4b00-e012-11eb-8758-c8ff82031765.png)

**Comment by fbernaly** [comment]
@thanhbinh84: example app is not production code, it is work in progress, feel free to send a PR with your contribution to fix this issue.
