### ISSUE TITLE
Barcode detection not working offline

### ISSUE THREAD

**Issue by gibahjoe** [bharat-biradar/Google-Ml-Kit-plugin#85]
Hi, It seems I have to be online for bacorde reading to work. It works great when online but if I go in airplane mode and turn off wifi, it does not detect anymore. Please advice

**Comment by bharat-biradar** [comment]
@gibahjoe Are facing the same issue even with the example app?

**Comment by gibahjoe** [comment]
Hi, My bad. I was resolving a dynamic link which apparently needed internet. False alarm.
