### ISSUE TITLE
How to get format barcode

### ISSUE THREAD

**Issue by ngant97** [bharat-biradar/Google-Ml-Kit-plugin#88]
I want to get format barcode. 
example: upca, qrCode, pdf417, aztec, etc...
Please help me solution.

**Comment by bharat-biradar** [comment]
@ngant97 Call `barcode.value.format`. Refer [here](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/ab354b8c597afe6188e3033f249f5ccba508afe7/lib/src/vision/barcode_scanner.dart#L263) for details
