### ISSUE TITLE
[Pose Detection] Z Coordinate Support

### ISSUE THREAD

**Issue by vladkharitonov** [bharat-biradar/Google-Ml-Kit-plugin#90]
As stated in the original MLKit documentation for Pose Detection, the model supports Z coordinate for keypoints. It also supports accuracy values which are not available in PoseLandmarkType class. I wonder if you plan to implement them in the near future. Thanks.

**Comment by fbernaly** [comment]
@vladkharitonov: yes, we are going to add those pretty soon

**Comment by fbernaly** [comment]
We added this feature in 0.7.0.
