### ISSUE TITLE
[Pose Detection] Confidence for pose detection and an option for smoother landmarks? 

### ISSUE THREAD

**Issue by jerlyjelly** [bharat-biradar/Google-Ml-Kit-plugin#92]
Is there support to filter based on confidence level? 

Want to do something like this: [https://codepen.io/mediapipe/pen/jOMbvxw](url)

**Comment by bharat-biradar** [comment]
@jerlyjelly Sorry but the original API does not provide any such options to filter based on confidence, we can't implement something not provided by the original API.

But if you want to classify poses refer [here](https://developers.google.com/ml-kit/vision/pose-detection/classifying-poses) for some help.
