### ISSUE TITLE
[Pose Detection] Updating pose detection model dependency to 17.0.1-beta4

### ISSUE THREAD

**Issue by jerlyjelly** [bharat-biradar/Google-Ml-Kit-plugin#93]
There seems to be a lot of performance upgrades on the ML Kit model. 

Any plans on upgrading to the latest 17.0.1 beta 4 model as specified on the Google ML Kit website? [https://developers.google.com/ml-kit/vision/pose-detection/android](url)

Thanks for the great plugin!

**Comment by bharat-biradar** [comment]
@jerlyjelly We plan to update it shortly. We'll let you know when the changes are pushed to the master branch.

**Comment by fbernaly** [comment]
We added this in 0.7.0.
