### ISSUE TITLE
Only works on ResolutionPreset.high CameraController 

### ISSUE THREAD

**Issue by arthas1888** [bharat-biradar/Google-Ml-Kit-plugin#94]
Describe the bug
I'm building an android app using flutter that has a QR code scanning feature. I've broken out the QR code logic into a minimum reproduction case here.

Oddly enough, the QR scanning only works on my Samsung devices  (I have a Samsung S20 FE). 
It's so strange when I test in my Pixel 3a and it doesn't work, only works with ResolutionPreset.high

I know the solutions is just to change the ResolutionPreset on the CameraController to high:

final newCameraController = CameraController(
    cameras.first,
    ResolutionPreset.high,
    enableAudio: false,
);
However,  On lower-end devices it causes dropped frames to set the camera controller to high. I am only using the camera preview for scanning a QR code, so high resolution is overkill for my use case.. Would love to be able to use this plugin on lower resolution presets.

**Comment by JrmyDev** [comment]
Exactly the same problem reported by my customer.
Too laggy with camera resolution high on Samsung SM-G950F
and not working with camera resolution medium on Xiaomi Mi Note 7 and 10 for example
How we do ?

**Comment by pvkhaijvb** [comment]
this is my solution
instead 
   ` final Size imageSize = Size(image.width.toDouble(), image.height.toDouble());`
by
```
    int width = image.planes[0].bytesPerRow;
    final Size imageSize = Size(width.toDouble(), image.height.toDouble());
```

in function  _processCameraImage
this is my code: 

` Future _processCameraImage(CameraImage image) async {
    final WriteBuffer allBytes = WriteBuffer();
    for (Plane plane in image.planes) {
      allBytes.putUint8List(plane.bytes);
    }
    final bytes = allBytes.done().buffer.asUint8List();
    int width = image.planes[0].bytesPerRow;
    final Size imageSize = Size(width.toDouble(), image.height.toDouble());

    final camera = cameras![0];
    final imageRotation =
        InputImageRotationMethods.fromRawValue(camera.sensorOrientation) ??
            InputImageRotation.Rotation_0deg;

    final inputImageFormat =
        InputImageFormatMethods.fromRawValue(image.format.raw) ??
            InputImageFormat.NV21;

    final planeData = image.planes.map(
      (Plane plane) {
        return InputImagePlaneMetadata(
          bytesPerRow: plane.bytesPerRow,
          height: plane.height,
          width: plane.width,
        );
      },
    ).toList();

    final inputImageData = InputImageData(
      size: imageSize,
      imageRotation: imageRotation,
      inputImageFormat: inputImageFormat,
      planeData: planeData,
    );

    final inputImage =
        InputImage.fromBytes(bytes: bytes, inputImageData: inputImageData);
    processImage(inputImage);
  }`

**Comment by arthas1888** [comment]
> this is my solution
> instead
> ` final Size imageSize = Size(image.width.toDouble(), image.height.toDouble());`
> by
> 
> ```
>     int width = image.planes[0].bytesPerRow;
>     final Size imageSize = Size(width.toDouble(), image.height.toDouble());
> ```
> 
> in function _processCameraImage
> this is my code:
> 
> ` Future _processCameraImage(CameraImage image) async {
> final WriteBuffer allBytes = WriteBuffer();
> for (Plane plane in image.planes) {
> allBytes.putUint8List(plane.bytes);
> }
> final bytes = allBytes.done().buffer.asUint8List();
> int width = image.planes[0].bytesPerRow;
> final Size imageSize = Size(width.toDouble(), image.height.toDouble());
> 
> ```
> final camera = cameras![0];
> final imageRotation =
>     InputImageRotationMethods.fromRawValue(camera.sensorOrientation) ??
>         InputImageRotation.Rotation_0deg;
> 
> final inputImageFormat =
>     InputImageFormatMethods.fromRawValue(image.format.raw) ??
>         InputImageFormat.NV21;
> 
> final planeData = image.planes.map(
>   (Plane plane) {
>     return InputImagePlaneMetadata(
>       bytesPerRow: plane.bytesPerRow,
>       height: plane.height,
>       width: plane.width,
>     );
>   },
> ).toList();
> 
> final inputImageData = InputImageData(
>   size: imageSize,
>   imageRotation: imageRotation,
>   inputImageFormat: inputImageFormat,
>   planeData: planeData,
> );
> 
> final inputImage =
>     InputImage.fromBytes(bytes: bytes, inputImageData: inputImageData);
> processImage(inputImage);
> ```
> 
> }`

Thanks!!, really works!, I appreciate your answer, this is my code 

`static Future<dynamic> detect({
    required CameraImage image,
    required Future<dynamic> Function(GoogleVisionImage image) detectInImage,
    required int imageRotation,
  }) async {
    return detectInImage(
      GoogleVisionImage.fromBytes(
        _concatenatePlanes(image.planes),
        _buildMetaData(image, _rotationIntToImageRotation(imageRotation)),
      ),
    );
  }

  static Uint8List _concatenatePlanes(List<Plane> planes) {
    final WriteBuffer allBytes = WriteBuffer();
    planes.forEach((Plane plane) => allBytes.putUint8List(plane.bytes));
    return allBytes.done().buffer.asUint8List();
  }

  static GoogleVisionImageMetadata _buildMetaData(
    CameraImage image,
    ImageRotation rotation,
  ) {
    int width = image.planes[0].bytesPerRow;
    return GoogleVisionImageMetadata(
      rawFormat: image.format.raw,
      size: Size(width.toDouble(), image.height.toDouble()),
      rotation: rotation,
      planeData: image.planes.map(
        (Plane plane) {
          return GoogleVisionImagePlaneMetadata(
            bytesPerRow: plane.bytesPerRow,
            height: plane.height,
            width: plane.width,
          );
        },
      ).toList(),
    );
  }

  static ImageRotation _rotationIntToImageRotation(int rotation) {
    switch (rotation) {
      case 0:
        return ImageRotation.rotation0;
      case 90:
        return ImageRotation.rotation90;
      case 180:
        return ImageRotation.rotation180;
      default:
        assert(rotation == 270);
        return ImageRotation.rotation270;
    }
  }`

**Comment by arthas1888** [comment]
@pvkhaijvb I wonder, do you change the image.width by image.planes[0].bytesPerRow and how do you find out it?

**Comment by arthas1888** [comment]
@pvkhaijvb I wonder, Why do you change the image.width by image.planes[0].bytesPerRow and how do you find out it?

**Comment by pvkhaijvb** [comment]
> @pvkhaijvb I wonder, Why do you change the image.width by image.planes[0].bytesPerRow and how do you find out it?

I dont know. I just debug in my code, i shaw image.planes[0].bytesPerRow different from  plane.width in my Phone. Just replace it.

Some Android phone have image.planes[0].bytesPerRow same  plane.width.

**Comment by sonsosad** [comment]
@pvkhaijvb I also had the same problem. Using this code solved the problem. Thanks

**Comment by pvkhaijvb** [comment]
Wá đjnk c4p <3

**Comment by pvkhaijvb** [comment]
> @pvkhaijvb I also had the same problem. Using this code solved the problem. Thanks

Wá đjnk c4p <3

**Comment by sonsosad** [comment]
@pvkhaijvb omg
Are you from Vietnam?
