### ISSUE TITLE
How soon will pose inference be on part with the native android version?

### ISSUE THREAD

**Issue by danj96dev** [bharat-biradar/Google-Ml-Kit-plugin#96]
I tried out mlkit 0.6.0 on with flutter but human poses aren't detected as often and when they are the points are less accurate. There's especially difficulty with tracking the hands and legs.

Will this happen in the next few weeks, I'd like to know before deciding on flutter or 2 native apps thanks!

**Comment by bharat-biradar** [comment]
@danj96dev We already have a PR #95 , to update it, until PR is merged pull the code directly from this [branch](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/update_poseDetection). Though it is still implemented for android only, you can test if the accuracy of points is according to your need or not.

**Comment by danj96dev** [comment]
> 
> 
> @danj96dev We already have a PR #95 , to update it, until PR is merged pull the code directly from this [branch](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/update_poseDetection). Though it is still implemented for android only, you can test if the accuracy of points is according to your need or not.

Thank you, just saw it got merged, will you push a new version to pub.dev soon?

**Comment by bharat-biradar** [comment]
@danj96dev Will publish it after updating `image labeling` on IOS.
