### ISSUE TITLE
Problem compiling in iOs for publishing

### ISSUE THREAD

**Issue by adriancsbna** [bharat-biradar/Google-Ml-Kit-plugin#97]
Hello.

I am trying to make the Archive to be able to publish the App but I get the following errors.
Doing flutter run or flutter run -release works correctly.

Any idea how to fix it?

![Captura de pantalla 2021-07-19 a las 22 51 33](https://user-images.githubusercontent.com/26508254/126225739-6c78c5ec-6371-40a6-8ae9-44b9d4289103.png)

**Comment by fbernaly** [comment]
Look at the readme, I added some tips: https://github.com/bharat-biradar/Google-Ml-Kit-plugin#ios.

Give them a try and let me know if that fixes your issue.

**Comment by adriancsbna** [comment]
Hello @fbernaly .

I tried what you indicated but it didn't work either.
When I run it normally it works, the problem is when doing the "Archive" in Xcode.

**Comment by fbernaly** [comment]
What is your minimum ios target? are you excluding armv7 in the Xcode project and in the pod file?

**Comment by adriancsbna** [comment]
Minimum ios Target: 10.0 
Yes, I exclude from both places

**Comment by fbernaly** [comment]
Try cleaning your DerivedData folder: https://programmingwithswift.com/delete-derived-data-xcode/
I was getting the same errors and after doing what I added to the readme and deleting the DerivedData it started to work

**Comment by CaoGiaHieu-dev** [comment]
i have a same this issue when build ios-framework and put it on my ios project

**Comment by CaoGiaHieu-dev** [comment]
@fbernaly  @adriancsbna 
hi . any update for this issue ?

**Comment by ShanibhanushaInfosoft** [comment]
undefined symbol: readBarcode

**Comment by Gbarago** [comment]
having this problem in my flutter app when i add qoreid sdk

**Comment by AmenaAlmasri22** [comment]
Hello.. I ran the iOS flutter application and it works perfectly. I am make  archive to uploading it to the Apple Store, so many errors of this type appear.
Showing Recent Errors Only
Undefined symbol: _objc_msgSend$
After referring to different names like this
![Uploading 11.jpg…]()
