### ISSUE TITLE
Can't run on android

### ISSUE THREAD

**Issue by CaoGiaHieu-dev** [bharat-biradar/Google-Ml-Kit-plugin#98]
Hi . I using FaceDetector on camera and it's work 100% on ios . But in android notthing happen . 
Im was reduce size app as same as issue #26 and some how it's cant detect face any more

**Comment by bharat-biradar** [comment]
@CaoGiaHieu-dev Please refer to this issue #89 from here on, it's the same one and you stay up to date with the changes there.
